### ISSUE TITLE
git effort bad substitution error

### ISSUE THREAD

**Issue by ifduyue** [tj/git-extras#1002]
Hello,

```bash
/opt/homebrew/bin/git-effort: line 272:  ${nJobs@P} >= nProcs : bad substitution
```

related code:

```bash
# send paths to effort
nPaths=${#paths[@]}
nProcs=$(procs)
nJobs="\j"
for ((i=0; i<nPaths; ++i))
do
    while (( ${nJobs@P} >= nProcs )); do
        wait -n
    done
    effort "${paths[i]}" &
done|tee $tmp
```

What does `nJobs="\j"` mean?

**Comment by spacewander** [comment]
It's Bash's PROMPTING syntax. For example, `\H` means "the hostname", `\j` means "the number of jobs currently managed by the shell". You can find them in `man bash`. 

What shell are you using?

**Comment by zijie0** [comment]
I also met this issue on Mac using zsh.

**Comment by ifduyue** [comment]
On macOS using zsh.

**Comment by spacewander** [comment]
Interesting, this command is expected to be executed under bash:
https://github.com/tj/git-extras/blob/2d1aa6daea420b74b305567ab0c5ae0094c336cd/bin/git-effort#L1

What is the `/usr/bin/env bash --version` output in your machine?

**Comment by zijie0** [comment]
```
/usr/bin/env bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

I also tried switching to bash:

```
bash

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ echo $SHELL
/bin/zsh
```

I think there's some setting need to be modified on Mac?

**Comment by ifduyue** [comment]
Maybe another way to achieve the same purpose? How about `jobs -r | wc -l`?

**Comment by ifduyue** [comment]
After `brew install bash` git-effort works again.

**Comment by spacewander** [comment]
> Maybe another way to achieve the same purpose? How about `jobs -r | wc -l`?

Pull request is welcome!

**Comment by spacewander** [comment]
@ifduyue @zijie0
Here is an interesting question: as we have `#!/usr/bin/env bash ` in every script, why zsh is used instead?

**Comment by ifduyue** [comment]
@spacewander Mac OS /bin/bash version is `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`,  it's too low that it doesn't support `${parameter@P}` syntax.

**Comment by chipweinberger** [comment]
I'm getting this error too! 

M1 MBP.

git version 2.32.0 (Apple Git-132)

git extras -v     
6.5.0
