### ISSUE TITLE
Feature: List all repos of a workspace with one line per repo

### ISSUE THREAD

**Issue by guenhter** [tj/git-extras#1006]
It would be very convenient to have an option for listing all bulk repos of a workspace where each repo is displayed in one line.
Additionally to the name of each repo it would be very helpful to have some status metrics of the repo in the same line as:
* Name of the current branch
* Number of not pushed commits
* Number of uncommitted changes
* Number of open branches (except the default branch)

What do you think?

**Comment by spacewander** [comment]
PR is welcome!

**Comment by guenhter** [comment]
Will be solved by https://github.com/tj/git-extras/pull/1017
