### ISSUE TITLE
hello, where can i find these commands(gst/ga ./gca) docs from tj’s introduce video?

### ISSUE THREAD

**Issue by moonlitusun** [tj/git-extras#1035]
like title.

**Comment by LucasLarson** [comment]
Does [this](https://web.archive.org/web/20230219181235id_/vod-progressive.akamaized.net/exp=1676834145~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F4101%2F1%2F45506445%2F107111328.mp4~hmac=065b68f23c4b6a222463097b36d1c346995a9559baa9b819972da95550018471/vimeo-prod-skyfire-std-us/01/4101/1/45506445/107111328.mp4) work?

**Comment by LucasLarson** [comment]
The old blog post is gone[^1], but there’s a copy of it available on the Internet Archive.[^2] I also see a copy of the post on Tumblr,[^3] and that’s archived, too, now.[^4]

[^1]: [`tjholowaychuk.com/post/26904939933/git-extras-introduction-screencast`](http://tjholowaychuk.com/post/26904939933/git-extras-introduction-screencast)
[^2]: [`web.archive.org/web/20130905225847/tjholowaychuk.com/post/26904939933/git-extras-introduction-screencast`](https://web.archive.org/web/20130905225847/tjholowaychuk.com/post/26904939933/git-extras-introduction-screencast)
[^3]: [`tjholowaychuk-blog.tumblr.com/post/26904939933/git-extras-introduction-screencast`](https://tjholowaychuk-blog.tumblr.com/post/26904939933/git-extras-introduction-screencast)
[^4]: [`web.archive.org/web/20230219184303/tjholowaychuk-blog.tumblr.com/post/26904939933/git-extras-introduction-screencast`](https://web.archive.org/web/20230219184303/tjholowaychuk-blog.tumblr.com/post/26904939933/git-extras-introduction-screencast)

**Comment by moonlitusun** [comment]
> The old blog post is gone[1](#user-content-fn-1-63d36b34adddaf0e9909d37eccc02d1f), but there’s a copy of it available on the Internet Archive.[2](#user-content-fn-2-63d36b34adddaf0e9909d37eccc02d1f) I also see a copy of the post on Tumblr,[3](#user-content-fn-3-63d36b34adddaf0e9909d37eccc02d1f) and that’s archived, too, now.[4](#user-content-fn-4-63d36b34adddaf0e9909d37eccc02d1f)
> 
> ## Footnotes
> 1. [`tjholowaychuk.com/post/26904939933/git-extras-introduction-screencast`](http://tjholowaychuk.com/post/26904939933/git-extras-introduction-screencast) [↩](#user-content-fnref-1-63d36b34adddaf0e9909d37eccc02d1f)
> 2. [`web.archive.org/web/20130905225847/tjholowaychuk.com/post/26904939933/git-extras-introduction-screencast`](https://web.archive.org/web/20130905225847/tjholowaychuk.com/post/26904939933/git-extras-introduction-screencast) [↩](#user-content-fnref-2-63d36b34adddaf0e9909d37eccc02d1f)
> 3. [`tjholowaychuk-blog.tumblr.com/post/26904939933/git-extras-introduction-screencast`](https://tjholowaychuk-blog.tumblr.com/post/26904939933/git-extras-introduction-screencast) [↩](#user-content-fnref-3-63d36b34adddaf0e9909d37eccc02d1f)
> 4. [`web.archive.org/web/20230219184303/tjholowaychuk-blog.tumblr.com/post/26904939933/git-extras-introduction-screencast`](https://web.archive.org/web/20230219184303/tjholowaychuk-blog.tumblr.com/post/26904939933/git-extras-introduction-screencast) [↩](#user-content-fnref-4-63d36b34adddaf0e9909d37eccc02d1f)

get，thanks
