### ISSUE TITLE
git summary --line "grep: warning: stray \ before white space"

### ISSUE THREAD

**Issue by rohitn** [tj/git-extras#1037]
> Apple M2 Max
> MacOS Ventura 13.2.1 (22D68)
> 

`git-extras --version`

> 6.5.0

`grep --version`

> grep (GNU grep) 3.8
> Packaged by Homebrew

cd to clone of git-extras
`cd git-extras`

`git summary --line`

>  project  : git-extras
> grep: warning: stray \ before white space
> grep: warning: stray \ before white space
> grep: warning: stray \ before white space
> grep: warning: stray \ before white space
> ...

**Comment by spacewander** [comment]
Fixed in https://github.com/tj/git-extras/pull/1010
It will be included in April's release.
