### ISSUE TITLE
Feature request: the continue integration

### ISSUE THREAD

**Issue by vanpipy** [tj/git-extras#1058]
Hi, guys,

There is nothing test with the command like the `git-abort`. It is hardly remember any detail of any command when time goes by.

> The Only Constant in Life Is Change.

So I think is useful to create the unit test for each command to leave the description how the command has been expected to run. For now, there are 74 commands, that means 74 uts needed. It is a big job. But first, we can find some ways to save life.

At least, three ways to create the unit test I think, the detials as below:

1. Integration tests in Bash
    * It is great and no more side effect, but i did not know the detail how to, so if someone gives a hand about how to, grateful!
2. Integration tests in Python
    * Save life always
3. Integration tests in Node
    * My favourite cause I use it a lot and so many pkgs to support the process

I think we can take a vote here, any new one is welcome!

One more, the github action or [Travis](https://travisonline.com/) or any other?

#### Reference
* [About continuous integration](https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration)
* [CI/CD explained](https://resources.github.com/ci-cd/)
* [pytest](https://github.com/pytest-dev/pytest/)

**Comment by spacewander** [comment]
I will vote for "ntegration tests in Python".

As for CI environment, GitHub Action is good enough. There have been several security accidents on Travis so I am not so confident to use it.

**Comment by vanpipy** [comment]
For `Integration tests in Python`, I prefer to choose [pytest](https://github.com/pytest-dev/pytest/), nice detailed info, auto-discovery, rich plugins, that means a `requirement.txt` and a directory `test` is enough. I love this, rather than the `package.json`, it is real simple a lot.

And another idea i got, is it require the git hook `pre-push` to support local integration?

**Comment by kang8** [comment]
> is it require the git hook `pre-push` to support local integration

Cool, If you want to introduce this integration, [pre-commit](https://pre-commit.com/) can do very well.

**Comment by spacewander** [comment]
> For `Integration tests in Python`, I prefer to choose [pytest](https://github.com/pytest-dev/pytest/), nice detailed info, auto-discovery, rich plugins, that means a `requirement.txt` and a directory `test` is enough. I love this, rather than the `package.json`, it is real simple a lot.
> 
> And another idea i got, is it require the git hook `pre-push` to support local integration?

git hook is great, but I don't think running the integration test each time a commit is pushed is a good idea. Because the integration test will have some side effects (cloning some repo, writing local files, etc.).

**Comment by spacewander** [comment]
> For `Integration tests in Python`, I prefer to choose [pytest](https://github.com/pytest-dev/pytest/), nice detailed info, auto-discovery, rich plugins, that means a `requirement.txt` and a directory `test` is enough. I love this, rather than the `package.json`, it is real simple a lot.
> 
> And another idea i got, is it require the git hook `pre-push` to support local integration?

git hook is great, but I don't think running the integration test each time a commit is pushed is a good idea. Because the integration test will have some side effects (cloning some repo, writing local files, etc.).

**Comment by vanpipy** [comment]
> git hook is great, but I don't think running the integration test each time a commit is pushed is a good idea. Because the integration test will have some side effects (cloning some repo, writing local files, etc.).

Yes, do like that have the side effect, the security issue will follow. I think should give the premisson to the devself. The developer can control it and decide how and when to run it.

**Comment by vanpipy** [comment]
> Cool, If you want to introduce this integration, [pre-commit](https://pre-commit.com/) can do very well.

Yes, the `pre-commit` do something like the same. And I would like to validate the commit with `pre-commit` and local integration with `pre-push` :D.

**Comment by vanpipy** [comment]
Sorry for the delay..., I am busy looking for a new job 🤣 

I will initialize the ci process as soon as possible, for now, I am doing some researchs and design the solution.

**Comment by hyperupcall** [comment]
I think it's worth looking into [lefthook](https://github.com/evilmartians/lefthook) - it's language agnostic as well and much faster than pre-commit. At [schemastore](https://github.com/SchemaStore/schemastore), I've had issues with the local environment's output failing to match the pre-commit environment's output.

I don't understand the side-effects comment - all these operations would be occuring in separate, ad-hoc Git directories, constructed just for the sake of testing, no?

**Comment by hyperupcall** [comment]
Concerning your comment about Bash integration tests, nearly everybody uses [bats](https://github.com/bats-core/bats-core) for that. Their documentation has a [page for writing your first test](https://bats-core.readthedocs.io/en/stable/tutorial.html#your-first-test) and I've found things to be very straightforward. At [asdf](https://github.com/asdf-vm/asdf), we have hundreds of Bats tests so feel free to look there or some of [my](https://github.com/bash-bastion/bash-object) [smaller](https://github.com/bash-bastion/bash-core) projects if you're looking for how to structure things. There are some extensions lilke [bats-assert](https://github.com/bats-core/bats-assert) and [bats-file](https://github.com/bats-core/bats-file), which make debugging and understanding tests much easier, but they're optional (we don't use them at asdf, for example).

So my vote would be for Bats, especially since this project is written in Bash/POSIX Shell. If you have any questions, feel free to let me know!

**Comment by spacewander** [comment]
> I don't understand the side-effects comment - all these operations would be occuring in separate, ad-hoc Git directories, constructed just for the sake of testing, no? In that case, nothing would trigger any of the Git hooks that we setup in `git-extras`.

Some tests may require creating unwanted files or writing to the global configuration, which is the side-effects. As the contributors may not be famous for the test scripts, requiring them to run the test case locally may scare them.

**Comment by spacewander** [comment]
> Concerning your question about Bash integration tests, nearly everybody uses [bats](https://github.com/bats-core/bats-core) for that. Their documentation is extensive and has a [page for writing your first test](https://bats-core.readthedocs.io/en/stable/tutorial.html#your-first-test) and I've found things to be very straightforward. At [asdf](https://github.com/asdf-vm/asdf), we have hundreds of Bats tests so feel free to look there or some of [my](https://github.com/bash-bastion/bash-object) [smaller](https://github.com/bash-bastion/bash-core) projects if you're looking for how to structure things. There are some extensions lilke [bats-assert](https://github.com/bats-core/bats-assert) and [bats-file](https://github.com/bats-core/bats-file), which make debugging and understanding tests much easier, but they're optional (we don't use them at asdf, for example).
> 
> So my vote would be for Bats, especially since this project is written in Bash/POSIX Shell. If you have any questions, feel free to let me know!
> 
> As for Node, I think that's a non-starter since that's not installed by default, unlike Python and Bash - and the ecosystem moves too fast.

@hyperupcall 
Thanks for your suggestion!

**Comment by hyperupcall** [comment]
> > I don't understand the side-effects comment - all these operations would be occuring in separate, ad-hoc Git directories, constructed just for the sake of testing, no? In that case, nothing would trigger any of the Git hooks that we setup in `git-extras`.
> 
> Some tests may require creating unwanted files or writing to the global configuration, which is the side-effects. As the contributors may not be famous for the test scripts, requiring them to run the test case locally may scare them.

Ohh I see - yeah writing to global configuration definitely is a side-effect to be concerned about. I wonder if writing to local configuration works - if not, that might br a bug

**Comment by hyperupcall** [comment]
@vanpipy Would you mind if I took a stab at implementing testing?

**Comment by vanpipy** [comment]
> @vanpipy Would you mind if I took a stab at implementing testing?

It is ok, but i did get your idea about the thing be took the stab. Means the `bats-core`?

**Comment by vanpipy** [comment]
Finally, first one for the `git-abort` is coming. And i do little research about the `bats-core`, i think it a good way to do the unit test for `git-extras`, because the main function needs are creating one repository and run some git commands. The detail is in the [PR](https://github.com/tj/git-extras/pull/1066/files).

**Comment by vanpipy** [comment]
And I think it is important to choose a good tool to support the CI and the cannot be replaced in a long time. Both the `pytest` and `bats-core` are good, or the `python` and `bash`. This is a direction decision. @spacewander @hyperupcall

**Comment by hyperupcall** [comment]
It looks like pytest was decided. Once the initial PR is merged, I can help author additional tests for some other executables

**Comment by vanpipy** [comment]
> It looks like pytest was decided. Once the initial PR is merged, I can help author additional tests for some other executables

Got that. Lots work here and i am glad to work here.

Are we need a big issue to include all cases or one by one?

**Comment by hyperupcall** [comment]
At least for me, an incremental / one by one case would be better and easier to keep track of

**Comment by vanpipy** [comment]
All right, i perfer to one issue one case too.

**Comment by spacewander** [comment]
We can use checkbox to track the PRs. Like:

- [ ] abort

**Comment by vanpipy** [comment]
> We can use checkbox to track the PRs. Like:
> 
> ```
> - [ ] abort
> ```
> 
> Here is what it looks like in issue:
> 
> * [ ]  abort

Which file to store the checklist?

Create a `TestChecklist.md`? Because i think the checklist is just a tempfile and it will be removed when the all jobs have been done, maybe not a good choice.

Create an issue? A good choice, tracing and close it when done.
