### ISSUE TITLE
Remove Build System?

### ISSUE THREAD

**Issue by hyperupcall** [tj/git-extras#1064]
As mentioned in a few other places, it can be difficult trying changes because there requires a small build step (using `is-git-repo`,  `has-git-commit` files) before the tools in `bin/` can be used.

This problem manifests itself in a few ways. It makes #1058 more difficult since the tests wouldn't be running on the source code, but some `usr` subdirectory where they are generated. I believe it has also been said somewhere that no new utility functions are planned to be added since currently it is too complicated to use them (integration with `Makefile`, and `is-git-repo`, etc. files).

I propose removing this build step in one of two ways:

- There is a common `util.sh` file (that we can place in `/usr/share/git-extras`) that contains all our shared functions. Executables that require it can source it first-thing
- We manually copy and paste these functions for every file. BUT, each function is prefixed with a common prefix (like `util_`, `common_`), and we have a check (run at build time and/or commit time) to make sure each function and its contents are identical. Making changes to these functions still isn't too hard because one can simply do a repository-wide find-and-replace in their favorite IDE

I'm leaning towards the second idea. @spacewander thoughts?

**Comment by spacewander** [comment]
To solve #1058, we can use a directory under `/tmp` as the `$PREFIX` and install the script during test, or run the test in a docker container.
To be frank, I wouldn't say I like to change the project structure as it can be solved by the test suite itself.

**Comment by hyperupcall** [comment]
@spacewander Yes, more code can be added to the test suite to handle this. But, what about the other issues I have mentioned? Complexity/fragility of the build system and difficulty of using common functions. The test suite isn't the only place where we see the problems from the build system

**Comment by spacewander** [comment]
> here is a common util.sh file (that we can place in /usr/share/git-extras) that contains all our shared functions. Executables that require it can source it first-thing

As there is no common utility directory for all unix system (Linux, Mac, BSD), and the user can specify the root by using `$PREFIX`, move them to a separate file and source it during execution may break the portability and make it harder to manage.

> We manually copy and paste these functions for every file. BUT, each function is prefixed with a common prefix (like util_, common_), and we have a check (run at build time and/or commit time) to make sure each function and its contents are identical.  Making changes to these functions still isn't too hard because one can simply do a repository-wide find-and-replace in their favorite IDE

The current build process is already guaranteeing the consistency of the utility. To be frank, the check and the find-and-replace could be also complex & fragile.

**Comment by hyperupcall** [comment]
I see where you are coming from - although I disagree with the approach, I will close this issue since you prefer the current approach.
