### ISSUE TITLE
Maybe change the default ARCHIVE_NAME of git-archive-file

### ISSUE THREAD

**Issue by halostatue** [tj/git-extras#1067]
The `$ARCHIVE_NAME` is set to `$(basename $PWD)`, which feels weird:

```console
$ # This assumes that I have git-extras and the GitHub CLI installed
$ gh repo clone tj/git-extras
$ cd git-extras/man
$ git archive-file
Building archive on branch "master"
Saved to "man.3.0.0-1034-gcb29c62c65bf.master.zip" (268K)
```

This feels like it should instead be set to `$(basename "$(git rev-parse --show-toplevel)")`.

**Comment by spacewander** [comment]
This change looks good to me. Would you submit a PR to change it? Thanks!

**Comment by spacewander** [comment]
This change looks good to me. Would you submit a PR to change it? Thanks!

**Comment by halostatue** [comment]
I didn't update the documentation for this one because the examples assumed running in the git root regardless.
