### ISSUE TITLE
[feature request] Add configurable feature branch separator

### ISSUE THREAD

**Issue by halostatue** [tj/git-extras#1069]
After having been burned a few too many times by the use of `/` to separate branch parts (it works, but it doesn't necessarily work the way that people think it should unless they're git experts), I have an aversion to this separator being used and do not allow it at the workplace. It would be useful to be able to have a default configuration and/or a flag to be able to specify this value.

`git config --get git-extras.feature.separator` and/or `-s|--separator` would be useful from my perspective.

This way I could do `git config git-extras.feature.separator -` and I would get `feature-branchname` instead of `feature/branchname`.

**Comment by spacewander** [comment]
LGTM. 
PR is welcome!
