### ISSUE TITLE
Test(git-alias): add the unit test for it

### ISSUE THREAD

**Issue by vanpipy** [tj/git-extras#1076]
## File
[git-alias](https://github.com/tj/git-extras/blob/master/bin/git-alias)

## Test cases
* list all aliases
* list the matched aliases
* set an alias globally
* set an alias locally

The original `git-alias` did not implement the forth one, so refactor it together.

## Problem
<del>Maybe need to create a test.md to track the process?</del>

No more, but anyone has more?

**Comment by spacewander** [comment]
> Maybe need to create a test.md to track the process?

Is there something can't be tracked in this issue?

**Comment by vanpipy** [comment]
Never mind, I though set a file as a checklist to mark the state of the unit test whether done or not. But i think now, a `tests/test_*.py` represents one unit test has been finished.
