### ISSUE TITLE
Feature: shellcheck in the CI

### ISSUE THREAD

**Issue by vanpipy** [tj/git-extras#1082]
The shellcheck give an idea that checking scripts with it.

I just want to ask it is useful or not.

* [python shellcheck wrapper](https://pypi.org/project/shellcheck-py/)
* [shellcheck on the ubuntu](https://manpages.ubuntu.com/manpages/jammy/man1/shellcheck.1.html#:~:text=It's%20mainly%20focused%20on%20handling,ShellCheck%20gives%20shell%20specific%20advice.)

**Comment by hyperupcall** [comment]
There are about ~40 ShellCheck violations so we would either need to fix/ignore those or we would need to add a way so _lines_ are incrementally checked. The former would be the easier solution

**Comment by vanpipy** [comment]
Is that means something like `# shellcheck disable=SC2086`? Because I handle some voilations and found there is no way to fix it except modify the code..., but a modification is totally a risk.

> there are about ~40 violations so we would either need to fix/ignore those

This means ~40 violations in a file or in all files?

> lines are incrementally checked

I did not figure out a way to do like that cause how to split the scope is a problem I cannot solved now.

Maybe a checklist for the shellcheck could be better. Fix it step by step?

**Comment by spacewander** [comment]
We can only focus on the `error` one:

```
In bin/git-scp line 179:
	git-rscp)                  reverse_scp $@;;
                                               ^-- SC2068 (error): Double quote array expansions to avoid re-splitting elements.
```

Only 13 violations for this.

**Comment by vanpipy** [comment]
This error checked from `shellcheck` should be resolved step by step in the unit tests manually.

So close it here.
