### ISSUE TITLE
Allow override temp file location in `git cp`

### ISSUE THREAD

**Issue by weiw005** [tj/git-extras#1090]
When running `git cp` it will create a temp file following a certain convention. 

E.g. running `git cp a/b/c.kt d/e.kt` will create a temp file like this: `a__b__c.kt-move-to-d__e.kt`

While this behavior works most of the time, it may run into path-too-long error when the src/dest file path is very deep. 

Suggestion: allow a third parameter to specify a temp file location override.

**Comment by spacewander** [comment]
PR is welcome!

**Comment by MattiasEh** [comment]
@spacewander Would you like a PR from https://github.com/tj/git-extras/compare/main...MattiasEh:git-extras:main ?  That approach avoids the need for a messy temporary file and therefore eliminates the class of problems that includes this issue.  It also makes for a cleaner history (at least IMHO) and should affect the original branch atomically.

My changes seem to work well for me, but I don't have a great way to test regressions for this fairly significant approach-change.  What's the best way to move forward?

References:
* https://stackoverflow.com/a/46484848/32841
* https://devblogs.microsoft.com/oldnewthing/20190919-00/?p=102904

**Comment by spacewander** [comment]
@MattiasEh 
Thanks for your work on this. Would you submit a pull request?

**Comment by MattiasEh** [comment]
Happy to!  PR #1169 created.

**Comment by spacewander** [comment]
Consider solved.
