### ISSUE TITLE
Autocompletion after `brew install git-extras`

### ISSUE THREAD

**Issue by krlmlr** [tj/git-extras#1101]
For some reason, `git d<TAB>` doesn't offer me `git delete-squashed-branches` in zsh. I installed via `brew install git-extras` .

`which git-delete-squashed-branches` shows me the correct path (under `/opt/homebrew/bin`), and I do get autocompletion for binaries in `~/bin` (which is also on my `$PATH`):

```
/usr/lib/ccache:/Users/kirill/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/quarto/bin:/Applications/iTerm.app/Contents/Resources/utilities
```

How to troubleshoot? Thanks!

**Comment by vanpipy** [comment]
Without any installation, just adding one more line in the `~/.zshrc`

```
source $(CODE_DIR)etc/git-extras-completion.zsh'

An example below:
source /home/leroy/Project/git-extras/etc/git-extras-completion.zsh
```

**Comment by krlmlr** [comment]
Thanks! I don't have this file after `brew install git-extras` . Completion for the commands themselves is also important, of course.

**Comment by vanpipy** [comment]
> Thanks! I don't have this file after `brew install git-extras` . Completion for the commands themselves is also important, of course.

I got your idea and let's fulfill the autocompletion first.

1. clone the git extras repo in your device
2. addsource `/home/leroy/Project/git-extras/etc/git-extras-completion.zsh` into `.zshrc`

The `/home/leroy/Project` bases on your real dir stored for the git extras repo.

I think after this, it should be work.

**Comment by krlmlr** [comment]
I will install from a local clone if I must, but shouldn't this work out of the box after `brew install git-extras` ?

**Comment by vanpipy** [comment]
> I will install from a local clone if I must, but shouldn't this work out of the box after `brew install git-extras` ?

I am not familiar with the part of the installation via `brew`, but from the result it should be not the expected you want. And here is a way to activate the autocompletion manually.

**Comment by hyperupcall** [comment]
@krlmlr It seems common to not automatically handle completions when using Homebrew. For example, [zsh-completions](https://github.com/Homebrew/homebrew-core/blob/master/Formula/z/zsh-completions.rb) and [autoenv](https://github.com/Homebrew/homebrew-core/blob/d88a6f06b04708465dc6f4e1d8fb4fbd38a6505a/Formula/a/autoenv.rb) tells the user to add a `source` to their shell configuration. We do this [as well](https://github.com/Homebrew/homebrew-core/blob/d88a6f06b04708465dc6f4e1d8fb4fbd38a6505a/Formula/g/git-extras.rb#L33).

**Comment by krlmlr** [comment]
Brilliant, thanks!

TIL I need to read `brew install` output.
