### ISSUE TITLE
git standup recursive search fails if -L missing

### ISSUE THREAD

**Issue by rm--** [tj/git-extras#1106]
[macOS 14.1.1, zsh, git-extras v7.1.0]

If I run `git standup` in a parent directory of some git-repositories.
`git standup` fails with:

```
find: : No such file or directory
```

If I run `bash -x /usr/local/bin/git-standup`, I see:

```
++ find '' . -maxdepth 2 -mindepth 0 -name .git
find: : No such file or directory
```

That's because of the quoted empty value of: `$INCLUDE_LINKS` in 
`PROJECT_DIRS=$(find "$INCLUDE_LINKS" . -maxdepth "$MAXDEPTH" -mindepth 0 -name .git)`
(https://github.com/tj/git-extras/blob/main/bin/git-standup#L243)

Since `$INCLUDE_LINKS` is only set if `-L` option is used, IMO there should be a handling of the empty value or the variable should have some valid value which `find` can handle.
(https://github.com/tj/git-extras/blob/main/bin/git-standup#L124)

**Comment by spacewander** [comment]
PR is welcome!
