### ISSUE TITLE
New git-utimes is broken on Mac

### ISSUE THREAD

**Issue by spacewander** [tj/git-extras#1118]
When I run `git-utimes` on Mac, I get this error:
```
awk: cmd. line:10: fatal: not enough arguments to satisfy format string
	` t=$(date %s$1 "+%Y%m%d%H%M.%S")
'
	                     ^ ran out for this one
```

CC @rasa 

![20231121110017](https://github.com/tj/git-extras/assets/4161644/616e9707-dfcb-4058-a4bc-886161603498)

**Comment by rasa** [comment]
@spacewander Thanks for the catch! I didn't have a Mac to test this, but now I do, and my latest commit fixes this issue. The issue was I hadn't doubled the '%'s in the date format string for printf.
