### ISSUE TITLE
[Feature Request] git absorb

### ISSUE THREAD

**Issue by COil** [tj/git-extras#1166]
Hello,

Any chance to have this one integrated ? This would be a time saver.

https://github.com/tummychow/git-absorb

**Comment by hyperupcall** [comment]
`git absorb` looks very useful, but it's written in Rust (and is spread out over multiple files). Right now, `git-extras` only has binaries that are written in a scripting language (nearly all are written in Bash or POSIX shell). So, unfortunately integrating something like `git absorb` would not be straightforward

**Comment by COil** [comment]
OK, thanks for the answer. And many thanks for `git-extras`, I use it almost every day. :)
