### ISSUE TITLE
git-safeclean

### ISSUE THREAD

**Issue by rauchg** [tj/git-extras#135]
Do exactly what `git clean -fd` does but first create a temporary directory under `$TMPDIR` that gets printed to stdout, and back the cleaned files there.

Example:

``` bash
$ git safeclean
… moved 103 files to /var/tmp/…/woot
$ git safeclean
… nothing to do
```

**Comment by vanpipy** [comment]
The safeclean cannot be declared cause the using scope of `git clean` bases on the user. The user should understand what the safe or not when use the `git clean -fd`. So I prefer the `git clean -fd --dry-run` to `git safeclean`. So closed it now and anyone interests, open it again.
