### ISSUE TITLE
git-gh-pages delete uncommited files

### ISSUE THREAD

**Issue by jespino** [tj/git-extras#137]
git-gh-pages is _really_ dangerous - If you run git-gh-pages in your
git directory it will delete all files (also uncommited!).

git-gh-pages should confirm that operation and also use stash to stash
that uncommited changes.

**Comment by shawnam** [comment]
+1 for this incredibly old request. I just lost a bunch of work, never imagining that git-gh-pages would delete my files.

**Comment by hemanth** [comment]
Need to re-check, strange that this still exists! 
@shawnam @cironunes Interested in doing a PR for this?

**Comment by cironunes** [comment]
I can do it later today. :smile:

**Comment by hemanth** [comment]
@cironunes  Awesome!
