### ISSUE TITLE
Packaging for GNU/Linux Debian based systems

### ISSUE THREAD

**Issue by frandieguez** [tj/git-extras#17]
I have packaged the git-extras utilities into one deb-file and I'll make it accesible from https://edge.launchpad.net/~frandieguez/+archive/mabishu when I solve some problems with the Makefile
There are some points that needs improvement:
- insert all the authors with mails
- improve the Makefile to support deb packaging
- create manpages for all commands.

**Comment by bittner** [comment]
This issue can be closed.

**Comment by spacewander** [comment]
@bittner 
Thank you for your notice. Closed.
