### ISSUE TITLE
git-changelog: spews errors on first usage, when there are no tags yet

### ISSUE THREAD

**Issue by sam-github** [tj/git-extras#176]
Fix is here:

https://github.com/sam-github/git-extras/commit/ea7cf7215f06e8d439cb54b2ef89a5be81431b6d

**Comment by limianwang** [comment]
I believe this is still occurring I'm getting this:

```bash
$ git changelog
fatal: ambiguous argument 'HEAD -> master..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

The version i'm using:
```bash
$ brew info git-extras
git-extras: stable 3.0.0 (bottled), HEAD
Small git utilities
https://github.com/tj/git-extras
/usr/local/Cellar/git-extras/3.0.0_1 (110 files, 480K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/git-extras.rb
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```

**Comment by pmalek** [comment]
@sam-github Can you create PRs from your fixes?

**Comment by sam-github** [comment]
@pmalek Sorry, no, they don't rebase cleanly (and I don't use this changelog generator anymore). The code looks pretty different, but I think that someone who wanted to could take the changes I made and rework them for the current master.

**Comment by markeissler** [comment]
So, the current version of changelog is a complete rewrite that was submitted this year (Mar 9, 2015). Any open issues for the old version should be closed.

**Comment by limianwang** [comment]
That's understandable. It looks like other people previously experience this issue, so I would assume the proposed fix is no longer applicable, and we should have a new fix in place?

**Comment by markeissler** [comment]
Yes. Before I look at this, are you absolutely certain you are calling the correct git-changelog?

**Comment by limianwang** [comment]
Sorry, I'm not understanding. What do you mean by "correct changelog"?

**Comment by markeissler** [comment]
Whether or not you have another copy of git-changelog somewhere in your PATH, perhaps a copy of the old version.

**Comment by limianwang** [comment]
Ah i see. No. I don't have another git-changelog in my PATH other than this one.

**Comment by qw3rtman** [comment]
Closing this to separate the old and current version.

@limianwang could you open a new issue for this if the error is still occurring?

**Comment by limianwang** [comment]
@qw3rtman Done. :bow:
