### ISSUE TITLE
git effort > ambiguous argument

### ISSUE THREAD

**Issue by xionglun** [tj/git-extras#182]
when i use `git effort` at [requirejs](https://github.com/jrburke/requirejs) repo, some issues will occur:
```
fatal: ambiguous argument 'dist/fonts/PT-Sans/Paratype': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
......
```

**Comment by nicolaiskogheim** [comment]
`git effort` has been completely rewritten since the last comment was posted. I doubt this issue is still reproducible.

**Comment by marcamillion** [comment]
I just installed `git effort` today, and I am still having this issue on the [angular.js](https://github.com/angular/angular.js) repo.

This is the full error:

```
$ git effort --above 20

  path                                          commits    active days

  .gitignore................................... 35          35
  CONTRIBUTING.md.............................. 47          41
  .travis.yml.................................. 58          49
  CHANGELOG.md................................. 374         282
  Gruntfile.js................................. 102         91
  README.md.................................... 30          28
  angularFiles.js.............................. 127         111
  bower.json................................... 25          21
  css/angular.css.............................. 27          25
  docs/app/assets/css/docs.css................. 33          31
  docs/config/index.js......................... 29          27
fatal: ambiguous argument 'docs/content/error//nocb.ngdoc': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'docs/content/error//notcsel.ngdoc': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'docs/content/error//iid.ngdoc': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
  docs/content/api/index.ngdoc................. 37          35
```

@nicolaiskogheim Thoughts?

**Comment by nicolaiskogheim** [comment]
Hahah, yes, I know what this is. This is incredible. Of course people have folder names with a `$` sign in them. 🙃 

```
angular.js/docs/content/error/$animate/nocb.ngdoc
```

becomes

```
angular.js/docs/content/error//nocb.ngdoc
```

which, of course, doesn't exists.


Well, this is a nasty one. I think I managed to solve it. Will post a PR tomorrow.

**Comment by marcamillion** [comment]
Awesome. Yeh...folder names with a `$` seems a bit funky to me :|

Thanks!

**Comment by nicolaiskogheim** [comment]
I have fixed the dollar issue, but suspect there is something worse. I think i found a file with an actual newline in it. That crashes git-effort, of course.

It looks like this

```sh
fatal: ambiguous argument '
': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

`git` is not at fault here. I have checked that it handles files with newlines, and it does.

If I'm not able to fix this, I'll just mute errors from git, ignore any and all of them, and leave a note in the man page about this.

**Comment by nicolaiskogheim** [comment]
> I think i found a file with an actual newline in it.

I take that back. Still have no idea what's going on 🙃

**Comment by nicolaiskogheim** [comment]
Okay, I think I've solved it now. I'll need to clean up the code a bit, and add some comments as there are a lot of special cases now. Tuesday is my busiest day, but I'll try and get a PR up tomorrow anyway.

**Comment by xionglun** [comment]
Good job, @nicolaiskogheim Thanks!

**Comment by marcamillion** [comment]
Awesome @nicolaiskogheim. Thanks for the work on this.

I look forward to seeing the PR and an updated gem :)
