### ISSUE TITLE
git-feature/bug/refactor does not create remote branch

### ISSUE THREAD

**Issue by stuplum** [tj/git-extras#186]
I would expect using the git-feature/bug/refactor alias to create both a local and remote branch, like git-create-branch does. Is this by design?

**Comment by gphat** [comment]
I would love for this to be an option!

**Comment by nicolaiskogheim** [comment]
Hi,

I think this is a valid feature request, and I'll take care of it after we agree on how this should look, IF we do, that is.

> Is this by design?

I would guess it just didn't occur to the creator of this command.


Anyway, I propose to add a flag to create the remote branch.
It could be called `-c/--create-remote-branch`, or `-p/--push(-branch)`.

Now, people tend to have multiple remotes with all kinds of names, and we cannot assume that the created branch should use the same remote as the branch it was based on.

For example, if I fork a repo and want to create a feature based off `master`, I would like the branch pushed to my fork, and not to `upstream` (which may or may not be the remote that `master` is pointing to).

And sometimes I might want to push to the `upstream` remote, so we cannot assume `origin` either.

As the examples show, we might want to let our new option take an argument. We should add autocompletion on remote names in that case.


We need to figure out how this is supposed to work. Feedback is much appreciated.

**Comment by mapitman** [comment]
Any movement on this? This seems broken to me as when I type:
```
git feature finish my-feature-branch
```
I receive this:
```
Deleted branch feature/my-feature-branch (was ea6e433).
error: remote-tracking branch 'origin/feature/my-feature-branch' not found.
remote: warning: Deleting a non-existent ref.
```

It seems as though the `finish` command is expecting that the `feature` command created a remote branch.

**Comment by mapitman** [comment]
PR #664 should close this issue.
