### ISSUE TITLE
Bash completion

### ISSUE THREAD

**Issue by FND** [tj/git-extras#20]
Would it be possible to make Bash completion aware of git-extras, allowing for commands like *git-graft* to recognize available branches?

It seems to me there's no simple way to do this - but my *bash_completion.d* fu is weak, so perhaps there's a solution after all?

**Comment by nicolaiskogheim** [comment]
Close?

**Comment by hemanth** [comment]
@nicolaiskogheim you want to work on this?

**Comment by nicolaiskogheim** [comment]
I thought this issue was about something that were merged in #64.

Tell me what needs to be done, and I'll have my best shot at it.

**Comment by hemanth** [comment]
You are right, closing this, thanks.
