### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by hemanth** [tj/git-extras#209]
@visionmedia 

Would it be better to add util script that each of the script import and check if the giving dir is a git repo or not and fail with a one line message?

May be something as simple as : 

`$ git rev-parse --is-inside-work-tree &>/dev/null; echo $?` if it returns `128` then it's not a git repo, if it returns a `0` then it's a git repo.

**Comment by nicolaiskogheim** [comment]
This can be closed.
