### ISSUE TITLE
git-extras on windows

### ISSUE THREAD

**Issue by fibo** [tj/git-extras#211]
Is it possible to link this article on `git/extras` documentation?

[Git extras on Windows](http://blog.g14n.info/2014/02/git-extras-on-windows.html)

Installation is different and some commands does not work, but, it is worth to add it to Git shell on Windows.

http://youtu.be/ed0_QuZJjS4

**Comment by nicolaiskogheim** [comment]
This article doesn't appear to exist anymore. Probably closing time for this issue then.
@hemanth

**Comment by fibo** [comment]
Hi, some time passed and I changed to a naked domain. Please cobsider to open the issue again qnd add the link to the article. Here it is the url: http://g14n.info/2014/02/git-extras-on-windows/

**Comment by spacewander** [comment]
Great! I think we can put it into the wiki.

**Comment by hemanth** [comment]
:+1:

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/
