### ISSUE TITLE
bash completion

### ISSUE THREAD

**Issue by khornberg** [tj/git-extras#233]
Not sure if this is a bug or not.
I just ran the one liner on Ubuntu 14.04 which worked well.
Upon opening terminal, I got an error:

```
: command not found
bash: /etc/bash_completion.d/git-extras: line 3: syntax error near unexpected token `$'{\r''
'ash: /etc/bash_completion.d/git-extras: line 3: `_git_bug(){
````

Fixed by running `dos2unix` on the file.

**Comment by nicolaiskogheim** [comment]
Closing as this is old, and I'm pretty sure this isn't an issue anymore.
If anyone still experiences this, please let us know.
