### ISSUE TITLE
ronn is required

### ISSUE THREAD

**Issue by jmarca** [tj/git-extras#269]
suggestion to modify README that ronn is required to make and install this, and that ronn itself installed by: 

```
gem install ronn
```

**Comment by nicolaiskogheim** [comment]
Ronn is only a  dev-dependency. As long as people run `make install` and devs remember to run `make docs` before they commit new stuff, this should't be a problem.

As long as you don't delete the docs, you don't have to build them @jmarca.

**Comment by jmarca** [comment]
Okay.  fine with me.  I just cloned the repo into a clean directory and followed the install docs and everything worked fine.  

So as you say, as long as the "devs" remember to run make docs...

However, isn't the idea of github that everybody can download the source and be a dev?  So again, a short note somewhere saying that ronn is a dependency to make the docs might be helpful.  So how about another link in the main readme, something like:

```

# Regenerating the documentation

The docs are already included in the repository and they should be installed automatically.  If you are a developer and want to expand or add additional documentation, see [Documentation](man/Readme.md)

```


My misstep was running git pull in a local clone repository, rather than deleting it and re-cloning.  After pull, it makes sense to me to run make clean to clear out any old cruft, but that also wipes the docs...

**Comment by nicolaiskogheim** [comment]
The `make clean` only cleans docs. But that should be mentioned somewhere.
If you want to build yourself (assuming docs are up to date), it should suffice to pull new changes and run `[sudo] make install`.

I'm going to do something about this. I understand the confusion. Thank you for reporting this.

**Comment by ansell** [comment]
I am still confused about why ronn (and the rest of the full build instructions) cannot appear in the README.md file. No novice users should ever be required to look at the README.md file, there should be an HTML website for that, which GitHub provides for free if you don't have hosting available. 

Those who do find the README.md file at GitHub can be expected to distinguish between the build dependencies compared to the runtime dependencies. There is no difference on GitHub between "devs" and other people who are interested in the source code, and they may want to contribute and have found that this lack of information is an artificial barrier to that.

**Comment by qw3rtman** [comment]
Now `make` defaults to `make install` (see #425), so unless someone runs `make docs`, this should not be an issue.

@ansell, novice users most likely wouldn't be installing this way anyway (cloning from GitHub and building from source), they would most likely be installing via Homebrew (`brew install git-extras`).
