### ISSUE TITLE
git revert multi commit

### ISSUE THREAD

**Issue by flyfree80** [tj/git-extras#28]
revert multi commit like git-revert.

now I use flowing steps to revert multi commit:
git reset --hard A
git reset --soft @{1}  # (or ORIG_HEAD), which is D
git commit -a

**Comment by nicolaiskogheim** [comment]
This hasn't received any attention, and therefore I don't think it's not worth it to do this at the moment.

If people believe this to be a useful feature, don't hesitate to say so and we'll reopen this issue.
