### ISSUE TITLE
Add merge-to

### ISSUE THREAD

**Issue by adius** [tj/git-extras#321]
How about adding a `merge-to` command like described here: http://stackoverflow.com/questions/3672073/git-merge-to-another-branch ?

**Comment by hemanth** [comment]
SGTM. Would like to hear it from @tj and @spacewander.

**Comment by pfctgeorge** [comment]
:+1:

**Comment by spacewander** [comment]
That will be useful. I will try to implement it next week.

**Comment by hemanth** [comment]
Cool, @adius might also be interested.

**Comment by adius** [comment]
Interested in implementing? I would if I have to, but if someone is more eager to implement it … sure, go ahead. =P
I was just wondering if merge-to is the right term. Maybe rather merge-into?

**Comment by hemanth** [comment]
heh heh! `merge-into` is a better name.
