### ISSUE TITLE
git-effort on a old codebase

### ISSUE THREAD

**Issue by andreicristianpetcu** [tj/git-extras#326]
Hi, 

git effort is an awesome tool! :D I am running it on the LibreOffice codebase and I started yesterday and it is still running. The purpose of running it is to find what are the most actively commited files so I can figure out what are the most important files that I need to understand. The problem is the fact that it takes TOOO long.

A proposed solution is to pass as an argument an interval for what commits to check since the latest commits are more relevant. Passing `--since` to `git log` seems like a simple sollution.
```bash
git effort --since='last month'
git effort --since='last year'
```
Do you think this is possible/useful?
Thank you!

**Comment by hemanth** [comment]
You be a useful flag to have AFAIK, are you interested in doing a PR?

**Comment by andreicristianpetcu** [comment]
Sorry, I do not have the time to contribute :( At least not in the near future.

**Comment by andreicristianpetcu** [comment]
Thank you! I will test it soon.

**Comment by nicolaiskogheim** [comment]
Yes, please :)

If there are a lot of files in your repo you should try specifying the ones you care about. This can speed up the command by orders of magnitude.

**Comment by andreicristianpetcu** [comment]
@nicolaiskogheim thank you! The problem is not the speed, this is not a command I run often, but the relevance. If I land on an old project, I am interested where most of the edits have gone to in the past 6 months. I really don't care that 5 years ago, a file got 1000 commits and nobody touched it since.

This tool is great! Thank you again!
