### ISSUE TITLE
git summary --line fails ("unrecognized argument")

### ISSUE THREAD

**Issue by paulschreiber** [tj/git-extras#329]
OS: Mac OS X 10.10.2 (14C1510)
git: 2.2.1

```
$ git summary --line
fatal: unrecognized argument: --line
error: unknown option `--line'
usage: git shortlog [<options>] [<revision range>] [[--] [<path>...]]

    -n, --numbered        sort output according to the number of commits per author
    -s, --summary         Suppress commit descriptions, only provides commit count
    -e, --email           Show the email address of each author
    -w[<w[,i1[,i2]]>]     Linewrap output


 project: foobar
 commits: 0
 authors: 
```

**Comment by sanusart** [comment]
@paulschreiber 
It looks like if you have an alias `summary` for `git shortlog` in *~/.gitconfig* from the message above.

**Comment by paulschreiber** [comment]
`git alias` shows nothing matching either `summary` or `shortlog`.

**Comment by hemanth** [comment]
Not able to reproduce, has @sanusart said, you might of aliased it.

**Comment by paulschreiber** [comment]
* `git summary` with no arguments works as expected.
* I disabled all aliases and I'm still seeing the error.

How can I debug this?

**Comment by hemanth** [comment]
Which version are you on?

**Comment by paulschreiber** [comment]
Which version of what? Git and OS details are in the original problem description.

**Comment by hemanth** [comment]
`git-extras`

**Comment by paulschreiber** [comment]
2.2.0. I cloned master.

**Comment by hemanth** [comment]
Works fine in the latest version.

**Comment by paulschreiber** [comment]
Still seeing this problem. Installed on a different Mac (OS X 10.10.3/14D136, git 2.2.1).

```
$ git summary --line
fatal: unrecognized argument: --line
error: unknown option `--line'
usage: git shortlog [<options>] [<revision range>] [[--] [<path>...]]

    -n, --numbered        sort output according to the number of commits per author
    -s, --summary         Suppress commit descriptions, only provides commit count
    -e, --email           Show the email address of each author
    -w[<w[,i1[,i2]]>]     Linewrap output


 project: blahblah
 commits: 0
 authors: 
```

**Comment by hemanth** [comment]
Works fine, for the below versions:

![screen shot 2015-04-29 at 9 24 55 am](https://cloud.githubusercontent.com/assets/18315/7384481/b0225ea8-ee51-11e4-9697-13abae465fc1.png)

Sorry, I don't have the specified version.

//cc @spacewander Any chance you have those?

**Comment by spacewander** [comment]
@paulschreiber 
Did you paste the full log of `git summary --line`?
I just notice a minor difference.

The recent version of `git summary` will output:
```
project  : something
repo age : ...
active   : ...
commits  : ...
files    : ...
authors  :
```

And the pasted log shows:
```
project: blahblah
commits: 0
authors:
```
It lacks of `repo age` and some others. So maybe there are mutiply version of `git-extra` installed in your machine. An older version of `git-summary`,  which doesn't support `--line`,  always overrides the new one.

Why not try `locate git-summary` to figure it out?

**Comment by paulschreiber** [comment]
Yes, that's the full output. Here's output with versions of everything:
```
Pauls-MBP-2:pdf-stamper paul$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D136
Pauls-MBP-2:pdf-stamper paul$ bash --version
GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin10.0)
Copyright (C) 2007 Free Software Foundation, Inc.
Pauls-MBP-2:pdf-stamper paul$ git --version
git version 2.3.5
Pauls-MBP-2:pdf-stamper paul$ git summary --line
fatal: unrecognized argument: --line
error: unknown option `--line'
usage: git shortlog [<options>] [<revision range>] [[--] [<path>...]]

    -n, --numbered        sort output according to the number of commits per author
    -s, --summary         Suppress commit descriptions, only provides commit count
    -e, --email           Show the email address of each author
    -w[<w[,i1[,i2]]>]     Linewrap output


 project: pdf-stamper
 commits: 0
 authors: 


Pauls-MBP-2:pdf-stamper paul$ git-extras --version
3.0.0
```

**Comment by spacewander** [comment]
@paulschreiber 
Will you run `cat $(which git-summary)` and send the output to us?

**Comment by paulschreiber** [comment]
Yes, multiple git-summary commands exist:
```
$ locate git-summary
/usr/local/bin/git-summary
/usr/local/git/bin/git-summary
/usr/local/share/man/man1/git-summary.1
```

```
Pauls-MBP-2:~ paul$ which git-summary
/usr/local/git/bin/git-summary
Pauls-MBP-2:~ paul$ cat $(which git-summary)
#!/bin/sh

COMMITISH=""
test $# -ne 0 && COMMITISH=$@
project=${PWD##*/}
commit_count=`git log --oneline $COMMITISH | wc -l | tr -d ' '`
file_count=`git ls-files | wc -l | tr -d ' '`
authors=`git shortlog -n -s $COMMITISH`

echo
echo " project: $project"
echo " commits: $commit_count"
if test "$COMMITISH" = ""; then
    echo " files  : $file_count"
fi
echo " authors: "
echo "$authors"
echo
```

`/usr/local/bin/git-summary --line` works as expected.

**Comment by spacewander** [comment]
@paulschreiber 
Nice, now you can remove them with `sudo make uninstall PREFIX=/usr/local/git`(which will also remove `/etc/bash_completion.d/git-extras`, you may need to reinstall `git-extra`), or remove them one by one.

**Comment by paulschreiber** [comment]
Solved!

**Comment by hemanth** [comment]
:+1:
