### ISSUE TITLE
It's time for a new version

### ISSUE THREAD

**Issue by chernjie** [tj/git-extras#336]
@hemanth :)

**Comment by hemanth** [comment]
Yup, will be doing in this weekend :)

**Comment by chernjie** [comment]
Awesome

**Comment by chernjie** [comment]
#343

**Comment by hemanth** [comment]
After #337 and #338 are fixed.

**Comment by chernjie** [comment]
@hemanth I suggest we revert #325 until the above issues are resolved. What do you think?

**Comment by hemanth** [comment]
@chernjie How long would it take to resolve those? Looks like it's shaping up well, right?

**Comment by chernjie** [comment]
@hemanth wait and see?

Say, we should look into some testing framework, e.g. travis, various versions of Git etc... It would help protect you from issues such as backward compatibility.

**Comment by markeissler** [comment]
@chernjie But what would that look like? If we consider the comment for git 1.9.2 not supporting "%D" for  a pretty format placeholder... (https://github.com/tj/git-extras/pull/355#issuecomment-94010021), then some of this testing could get down in the weeds pretty quickly. Testing would require knowing which functionality is required by each git-extra, and then knowing which installed versions of system utilities are required to support that functionality.

I think a start would be to outline, project-wide, which minimal version of git, grep, sed, etc., must be supported by each git-extra. That's easier to work with. Just looking at grep and sed, for instance, there's GNU and BSD versions of each.

**Comment by spacewander** [comment]
I agree with @markeissler 
We should have a project-wide requirements. 
Therefore we can have a limited range to test for, and stop the support if the version of git/bash/other tools is too old.

**Comment by chernjie** [comment]
@markeissler I agreed with you and @spacewander.

One step at a time :)

**Comment by chernjie** [comment]
@hemanth so what's the verdict? Are we going to tag a new release?

**Comment by hemanth** [comment]
Revert 325 and release?

**Comment by chernjie** [comment]
I'm fine with either. To revert you can merge #352

**Comment by markeissler** [comment]
@hemanth @chernjie Just rebased and repushed better-changelog branch #355.

**Comment by hemanth** [comment]
Thanks @markeissler merged it. Was it checked on GNU/Linux?

**Comment by markeissler** [comment]
Just  tested it on CentOS 7. Looks good.

**Comment by hemanth** [comment]
Cool, will be doing the new release by tomorrow.

**Comment by spacewander** [comment]
@hemanth 
Well, there is a pr to fix a broken regex: https://github.com/tj/git-extras/pull/360
Will you have a look at it before the release?

**Comment by hemanth** [comment]
@spacewander  I just merged it sir ;) :+1:

**Comment by spacewander** [comment]
@hemanth 
Great!

**Comment by hemanth** [comment]
What about #359 ?

**Comment by markeissler** [comment]
Hrmmm. Just found a bug on OSX using the installed BASH (3.2.57), introduced via the patch from @spacewander.

I'm looking at it but think, realistically, it might be best to just revert #355 (yes, again) and hold off for the next release so more testing can be done across platforms and combinations (I'm developing on OSX with BASH 4.3, and testing on CentOS 7, and OSX BASH 3.2...unless I forget that last one).

**Comment by markeissler** [comment]
Alright. Fixed again. PR #361

**Comment by hemanth** [comment]
Thanks @markeissler :+1:

**Comment by hemanth** [comment]
Guys can you quickly review -> [rid-star](https://github.com/tj/git-extras/releases/tag/3.0.0) before we tweet about it and close this issue? 

Thank you all!
