### ISSUE TITLE
`git effort` is priting twice.

### ISSUE THREAD

**Issue by hemanth** [tj/git-extras#339]
```
± |master ✓| → git effort --above 15 bin/

  file                                          commits    active days

  bin/......................................... 345        193



  file                                          commits    active days

  bin/......................................... 345        193

```

//cc @spacewander @chernjie

**Comment by spacewander** [comment]
Maybe it is a feature? The second one is sorted, and before printing out the second one, it will clear the terminal screen to hide the first one.

**Comment by hemanth** [comment]
Right, but it does not make sense when we have only one item to display?

**Comment by Lonenso** [comment]
Hi, I want to reopen this due to printing twice isn't friendly to pipe, to redirect output to files.
Let's say 
`git effort > effort.txt`
There will be twice output inside it.
