### ISSUE TITLE
[feature] git guilt

### ISSUE THREAD

**Issue by robertwhitebit** [tj/git-extras#341]
> Calculates the change in blame between two revisions.

> git-guilt is a little tool I wrote that lets you see the transfer of blame in a repository caused by a range of commits. For example, if you wanted to see how blame shifted from one author to another during your last commit

Maybe this should be added to the git-extras? It's very useful to find reviewers for pull requests.

Detailed explanation:
https://www.atlassian.com/git/articles/git-guilt-blame-and-code-review#introducing..-git
https://www.npmjs.com/package/git-guilt

**Comment by hemanth** [comment]
Nice name, seems like a legitimate use case, would like to here it from @spacewander.

**Comment by spacewander** [comment]
@hemanth @robertwhitebit 
It is a very good idea! I will start to look at its js source code and try to convert it into shell.

**Comment by hemanth** [comment]
:+1:

**Comment by robertwhitebit** [comment]
@hemanth @spacewander 
Awesome, thank you guys!

**Comment by jojomi** [comment]
:+1: 

Seems to be a useful feature to me

**Comment by robertwhitebit** [comment]
Wow, I don't know what to say. That was quick. Thanks a lot! :smile_cat:

There are still two problems I'm facing. I freshly cloned the repository and run make install. That's all.
I can create issues if you want for each one or pack them into a single issue.

I c&p the command line output 1:1 from the terminal
```
[1] ~/Downloads/git-test [branch]$ git diff @~
diff --git c/README.md w/README.md
@@ -1,5 +1,5 @@
 First line
-Second line
+Not first line
 Third line
 Fourth line
 Yet another line
+Last line
[2] ~/Downloads/git-test [branch]$ git-guilt @~ @
[3] ~/Downloads/git-test [branch]$ git-guilt -d @~ @
git blame README.md
1 Robert Whitebit
[4] ~/Downloads/git-test [branch]$ git-guilt -d @~
git blame README.md
-5 Robert Whitebit
```

[1] One line has been added and one line has been modifed.
[2] No output is given. I don't know why :crying_cat_face: I also tested other projects (e.g. git-extras). Never getting an output.
[3] Adding the debug flag, an output is given.
[4] ```git guilt @~ @``` and ```git guilt @~``` should maybe generate the same output. So if you checkout a PR, you can run ```git guilt master``` to determine the best candidates to review the PR -> The second parameter default value should be @.

Additional: The tmp files can get very big. Maybe they should be deleted manually at the end of the run instead of waiting for the OS doing so?

**Comment by spacewander** [comment]
Strange...

I test it on my machine:
```
/tmp/t(master ✔) git diff @~
diff --git a/README.md b/README.md
index 1b779cb..582f1ca 100644
--- a/README.md
+++ b/README.md
@@ -1,5 +1,6 @@
 First line
-Second line
+Not first line
 Third line
 Fourth line
 Yet another line
+Last line
/tmp/t(master ✔) git-guilt @~ @                
spacewander                   +
/tmp/t(master ✔) git-guilt -d @~ @
git blame README.md
spacewander                   +
1 spacewander
```

So maybe it is the problem with awk, what kind of awk on your machine?

About other problems:
1. `git guilt` need two arguments, it will forward them to `git blame`. If you need, I will set up a defult value.
2. I should change the code to reduce tmp files and keep data in process, for example, filter commiter before writing all logs into tmp files.

**Comment by robertwhitebit** [comment]
> So maybe it is the problem with awk, what kind of awk on your machine?

man awk says I'm using mawk v1.2
It's the default installation of awk on Ubuntu I guess. I also have a fresh installation of Ubuntu 15.04 running in a virtual box which is running, by default, the same awk. Also no output :crying_cat_face:
Nevertheless, debug prints the correct and sorted output.

> 1.

The nodejs version does so as well. Imo, @ as default value for the second parameter makes sense. If you don't specify a second revision, the head is chosen. But you are the one who has to decide :wink:

> 2.

That would be awesome. I ran the command ```git-guilt @~ @``` over this commit https://github.com/Catrobat/Catroid/commit/c40c887e76bbbd04a6579e8e810ddef7509baf44 (3 changed files, 10 additions, 10 deletions) which already produces a total filesize of 879,4kB

**Comment by robertwhitebit** [comment]
> 2.

Maybe I'm just worrying too much. :wink: I got ~60MB of tmp files for a long living branch which isn't that bad.

**Comment by spacewander** [comment]
@robertwhitebit 
Aha, I figure out why! The lost of output is caused by a regex which works on gawk but not on mawk. I change the regex and it works well now. Please wait for me to handle the rest issues.

**Comment by robertwhitebit** [comment]
@spacewander 
Awesome! Thanks. I'm excited to see the real guilt output :scream_cat:

**Comment by spacewander** [comment]
@robertwhitebit 
Will you have a try with the [latest version](https://github.com/tj/git-extras/pull/345)?

**Comment by robertwhitebit** [comment]
@spacewander
Works like a charm! And also looks great. :kissing_cat:

and the size has been decreased drastically. Awesome!

jfi: If you run ```git guilt @~``` on the PR commit, the output is empty, of course, since you only modified your own code. It scared me for a second :smile_cat:

**Comment by hemanth** [comment]
:+1:
