### ISSUE TITLE
[git-guilt] Indentation errors with printf and utf-8 characters

### ISSUE THREAD

**Issue by robertwhitebit** [tj/git-extras#346]
There are some indentation errors for names with utf-8 characters when running e.g. ```$ git guilt 2.2.0 master```.

Code: https://github.com/tj/git-extras/blob/master/bin/git-guilt#L81 (and also line 95)
Part:```%-29s```

### mawk as default awk:
(also the default awk on ubuntu machines)
```
Andrew Starr-Bochicchio       ++++++++++++++++++
Valérian Galliat             ++++++++++++++++
...
dead-horse                    ++++++++++
Jon Ander Peñalba            ++++++++
Rasmus Wriedt Larsen          ++++++
...
Stephen Mathieson             ---
Patryk Małek                 ---
Jesús Espino                 ---
James Manning                 ----
```

Since printf in mawk counts bytes (not characters), every name containing a multi-byte character (utf-8) will f*ck up the indentation. I don't see a build in solution for this problem. ```LC_ALL=C.UTF-8 mawk ...``` didn't work for me.

Maybe using ```wc -m``` could solve the problem?
```printf Hello | wc -m``` = 5
```printf H€llö | wc -m``` = 5

Also ```${#VAR}``` would work.
```VAR="Hello" && echo ${#VAR}``` = 5
```VAR="H€llö" && echo ${#VAR}``` = 5

### gawk as default awk:

```
Nate Jones                    ------------
Julio Napurí                 --------------
Kevin Woo                     ---------------
```

Does a nearly perfect job. The only character giving all commands a bad time, is í. Imo it's not worth fixing it nor researching for a solution. So git guilt with gawk doesn't need a fix :wink:
```printf í | wc -m``` = ```VAR="í" && echo ${#VAR}``` = 2

ping @spacewander 
(btw: I already switched to gawk :wink:)

**Comment by hemanth** [comment]
hmm...

**Comment by spacewander** [comment]
`í` looks like actually two characters:
```sh
~ pry
[1] pry(main)> 'í'.length
=> 2
~ node        
> 'í'.length
2

```
Seeing is not believing!

I did some research, and find out that `mawk`'s `printf` is based on ANSI C, which is unfriendly with Unicode, `gawk`'s `printf` is based on built-in `printf` function.
To get rid of this problem, I plan to rewrite the 'printf' part with pure shell code. Therefore, the output will be the same with `gawk`.

And we can use `\t` as the delimiter between name and number. so even if there is a few special characters like `í`, we still obtain a good indent.

**Comment by robertwhitebit** [comment]
Damn you í :smile_cat:

Using a tab is a really smart idea! I like that. :+1:
Maybe temporarily setting the tab size to 30 or so would also be a good idea?
```
$ tabs -30
$ echo -e 'a\ta'
a                             a
$ echo -e 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaa\ta'
aaaaaaaaaaaaaaaaaaaaaaaaaaaaa a
$ echo -e 'ííííííííííííííííííííííííííííí\ta'
ííííííííííííííííííííííííííííí a
```
So you just need to shorten the person string to 30 (or 29) characters and the tab does the rest for you. Still not sure how to temporarily set the tab size.

**Comment by spacewander** [comment]
Set tab size works well awesomely! It just like a magic. Thanks for @robertwhitebit 

But instead of shorten people or their email, I perfect to use space if they are longer than 30 characters.
It will break the ident, but the infomation of people remain and can be reused with other CLI tools.

**Comment by spacewander** [comment]
Still need to rewrite with pure shell code...

Assume we have changed tab size:
We still need to know the length of string, so that we can strip it or use space.
But the built-in `length` is unreliable.
So we should add a filter, to calculate string's length and add it as a field of data. Then awk will parse this field and get correct length.

It seems more complex than rewriting with pure shell code.

**Comment by robertwhitebit** [comment]
Yes, you are right. name|email should never be cut.

We could call the ```wc -m``` command inside of awk to get the length of a person.
```
awk 'BEGIN {
person = "H€llö"
"printf \""person"\" | wc -m" | getline person_length
printf("%s is %d chars long\n", person, person_length)
}'

H€llö is 5 chars long
```
The output still has to be adapted.

**Comment by robertwhitebit** [comment]
Oh, forgot to test it with mawk. I get a '/bin/sh: 1: Syntax error: Unterminated quoted string' error. But it works with gawk. So I'm not sure how to quote the variable person...

**Comment by spacewander** [comment]
@robertwhitebit 
Thanks for your idea, but I still think that writing with pure shell code will be easier, since we just need to print something pretty.

**Comment by robertwhitebit** [comment]
@spacewander 
:+1:

**Comment by hemanth** [comment]
Fixed in the new release.
