### ISSUE TITLE
.gitignore without an initialized repo

### ISSUE THREAD

**Issue by matthewmueller** [tj/git-extras#347]
A lot of times when I'm just creating a project, I want to add a few files and directories to the `.gitignore`, before setting up git.

The behavior before was to just run `git ignore node_modules` and it would create a `.gitignore` file, not it's errors out with `Not a git repo!`. I understand why this is here, but it forces you to manually create the file and add these files before committing.

**Comment by spacewander** [comment]
Well, we can change the behaviour.
Instead of exiting, we can just warn the user that they are outside of a git repo.(Or there should be a git repo, in your case).
What about your opinion? @hemanth

**Comment by hemanth** [comment]
Well, I would just do `git init && git ignore node_modules` anyway one would have to do a `git init` and add the required.
