### ISSUE TITLE
require('child_process').exec('git summary')

### ISSUE THREAD

**Issue by zxdong262** [tj/git-extras#348]
get nothing, but `require('child_process').exec('git summary --line')` will get the right stdout.

``` javascript
var exec = require('child_process').exec
exec('git summary', function(err, stdout) {
    //nothing in here works
})

exec('git summary --line', function(err, stdout) {
    //works fine
    assert(stdout)
})
```

When I try use node to get the stdout from `git summary`, I find this strange thing, do not know why.
I hope it can be fixed.
Thanks.

**Comment by hemanth** [comment]
hmm?

**Comment by spacewander** [comment]
I just wrote some code to reproduce it:
```js
var exec = require('child_process').exec
exec('git summary', function(err, stdout) {
    console.log(stdout);
})
```
Got nothing.

However, 
```ruby
exec "git summary" if fork.nil? # ruby code
```
This time it output correct result.

So, I guess it is not a bug of `git-extras`.
@zxdong262 Maybe you need to dive into `child_process`?
