### ISSUE TITLE
Feature Request? git remote set-url to git@github.com format

### ISSUE THREAD

**Issue by mmocny** [tj/git-extras#350]
Whenever I use git-extras to fork a repo and submit a PR, the default format for remote is to use https, which requires login.  I prefer ssh, and am currently manually updating the remote format.

Also, often I copy-paste `git clone` instructions online and use the default http url.

Would you appreciate a new git-extra to update all remotes to the ssh format for github hosted repos?  Or, is there already a config option I could use to default to ssh which I do not know about?

Thanks!

**Comment by chernjie** [comment]
Sounds like what you need is https://github.com/github/hub

**Comment by mmocny** [comment]
I use hub already.. But git-extras sets the default remote urls. I don't
think hub has a simple way to set-url on existing remotes after the fact?

**Comment by mmocny** [comment]
Nevermind, user error.  I was using hub to fork!

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/
