### ISSUE TITLE
Git-ignore treats arguments as regular expressions instead of file names

### ISSUE THREAD

**Issue by rkennedy** [tj/git-extras#353]
Suppose we want to ignore the file *preview.c*:

```bash
git ignore preview.c
```

Now suppose we want to ignore the file *view.c*.

```bash
git ignore view.c
```

But *view.c* isn't actually ignored. The *.gitignore* file contains just one entry:

```
preview.c
```

This is because `git-ignore` uses `grep` to check for duplicate entries before adding new ones. The pattern `view.c` matches the existing `preview.c` line, so the new entry is treated as a duplicate of the old one.

Note that it's not just a substring match. The command `git ignore e.*c` also has no effect because `e.*c` is a regular expression that matches the value `preview.c`.

The command should use the `grep` settings that disable regular expressions and substring matches. After all, once the pattern is added to *.gitignore*, it's not treated as either of those; it's treated as a shell glob.

**Comment by hemanth** [comment]
@rkennedy Nice catch, can you please do a PR?

**Comment by hemanth** [comment]
Fixed.

**Comment by rkennedy** [comment]
Thanks, but I'm afraid I don't see *where* it's fixed (besides in my own fork). I don't see the change in tj/git-extras. Did I do the pull request wrong?

**Comment by chernjie** [comment]
@rkennedy you'll need to submit a pull request to tj/git-extras, and not to your own fork.
Try this link: https://github.com/tj/git-extras/compare/master...rkennedy:bug-ignore-regex
You might also want to [rebase your branch](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) before creating a pull request.
