### ISSUE TITLE
git: 'merge-into' is not a git command. 

### ISSUE THREAD

**Issue by ryandeussing** [tj/git-extras#366]
For some reason `git merge-into` fails with the above error. No other commands cause any problems. Thx.

**Comment by spacewander** [comment]
Maybe there is not `git-merge-into` installed in an appropriate place?

Try 
`which git-merge-into` 
and 
`which git-extras`

**Comment by ryandeussing** [comment]
That appears to be the case, `which git-merge-into` returns not-found. Even though `which git-extras` returns `/usr/local/bin/git-extras`. Guess I'll live without it, as reinstalling doesn't change anything.

**Comment by spacewander** [comment]
Will you tell me the way you install `git-extra`? Maybe I can reproduce the problem.

**Comment by ryandeussing** [comment]
`brew install git-extras` - I also deleted the cache and re-installed to make sure I had the latest.

**Comment by spacewander** [comment]
@hemanth 
Well, we need to update `git-extras`'s brew package from 2.2.0 to latest 3.0.0.
And its deb package also need to be updated.

**Comment by hemanth** [comment]
@spacewander Alright!

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by qw3rtman** [comment]
Can this be closed, @hemanth?
