### ISSUE TITLE
git 2.4 backwards incompat change breaks git-changelog

### ISSUE THREAD

**Issue by birdspider** [tj/git-extras#367]
A git change in [git 2.4.0](https://github.com/blog/1994-git-2-4-atomic-pushes-push-to-deploy-and-more) specifically https://github.com/git/git/commit/46d403f13e5cb6d2b6bee6f942a679ea8978b9fa breaks git-extras' `git-changelog`. 
Somewhere in the tag-extraction bash parts.

The new `HEAD -> master` tag format (which shows where the HEAD points to) seems to be the culprit.

**Comment by hemanth** [comment]
//cc @spacewander @chernjie @markeissler

**Comment by markeissler** [comment]
@birdspider  I'm looking at this using `git 2.4.2` and on both OSX and CentOS, everything appears to work fine. Can you provide more details?

**Comment by birdspider** [comment]
@markeissler Uh, I'm sorry - it might have been that I used an old `git-extras` install, seems to work fine after update. Sorry for the timewaster :/ .

I described the bug after taking a look a the `/usr/bin/` scripts which I had installed, which, so it seems, were out-of-date. It didn't occur to me at that time.

````
aur/git-extras-git 1.9.0.9.ge91da7c-1 (5) [installed]
~$ aura -A git-extras-git
installing git-extras-git-3.0.0.12.gaecef0e-1
```
