### ISSUE TITLE
Install latest release version instead of latest code in manual way

### ISSUE THREAD

**Issue by spacewander** [tj/git-extras#371]
The installation guide's `one-liner way` use command below to install `git-extras`:
```
(cd /tmp && git clone --depth 1 https://github.com/tj/git-extras.git && cd git-extras && sudo make install)
```

However, it will install the latest code, instead of the latest release version, which may contain some bugs.

There are three ways to install the latest release version (all has problem with it):

1. checkout the latest tag
    ```
    (cd /tmp && git clone https://github.com/tj/git-extras.git && cd git-extras && git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) && sudo make install)
    ```

    Problem: This way need to fully clone the repo, with all its history message. It will increase the size of data (from 125k to 746k) and slow down installation.

2. clone release branch
    ```
    (cd /tmp && git clone -b release --depth 1 https://github.com/tj/git-extras.git && cd git-extras && sudo make install)
    ```

    Problem: This way requires us to maintain a release branch.

3. clone latest tag
    ```
    (cd /tmp && git clone -b $(git ls-remote --tags https://github.com/tj/git-extras.git | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | sort -V | tail -1) --depth 1 https://github.com/tj/git-extras.git && cd git-extras && sudo make install)
    ```

    Problem: 1. too complex 2. force tags to match `[0-9]+\.[0-9]+\.[0-9]+`.

@hemanth 
Any other suggestions?

**Comment by hemanth** [comment]
I would vote for checking out the latest tag.
