### ISSUE TITLE
git-changelog --all gives error

### ISSUE THREAD

**Issue by mauvm** [tj/git-extras#374]
I'm trying to generate the History.md (changelog) for my entire project. However I get the following error:

```bash
$ git changelog --all
mv: invalid option -- 'a'
Try 'mv --help' for more information.
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  5 2014 21:00:28)
Unknown option argument: "-a"
More info with: "vim -h"
```

It seems like `git-changelog` execs the editor with its own flags.

I'm running Mac OS X Yosemite Version 10.10.3 and have tried both Fishshell v2.1.2 and GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14).

**Comment by spacewander** [comment]
What is your `git-extras` version?
Try `git extras -v`.

**Comment by mauvm** [comment]
Oops! Totally slipped my mind.

git version 2.4.0
hub version 2.2.1
git extras version 2.2.0

And the repository is: https://github.com/documark/documark

**Comment by spacewander** [comment]
Well, only the latest version of `git-extras`(3.0.0) supports `git changlog -a`.
I recommand you to install it via one-line bash code:
```
$ (cd /tmp && git clone https://github.com/tj/git-extras.git && cd git-extras && git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) && sudo make install)
```
Unfortunately, there is still a bug https://github.com/tj/git-extras/issues/367 related to `git changlog`. If you don't mind, you can correct the `History.md` manually.

**Comment by mauvm** [comment]
Awesome! It works. Thanks for the quick response. :+1:

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/
