### ISSUE TITLE
Upgrade ZSH completion

### ISSUE THREAD

**Issue by GuillaumeSeren** [tj/git-extras#376]
Hey there,
I open a new issue to start from something fresh, but this follow (few years laters) this issue: https://github.com/tj/git-extras/issues/70

So to sum up I am a git-extras user, which recently switch from bash to zsh.

So after digging on the web, I realized that the zsh completion file is not the same in bash, and is not up-to-date by 3 year old:
- https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git-extras/git-extras.plugin.zsh

So despite the fact it is quite disappointing to see that breaking, I try to use the bash completion file with zsh with no success, so I think upgrading the zsh completion is not a big deal, so started it.

While it's not finish, I am really asking if you (there's probably other zsh user), find a way to get the completion working ?

Other question, what do do you think about getting this file here in the upstream project ?

Guillaume.

**Comment by hemanth** [comment]
Definitely.

**Comment by spacewander** [comment]
@GuillaumeSeren 
Long time ago, I have seen a pr to oh-my-zsh to update the git-extras completion: https://github.com/robbyrussell/oh-my-zsh/pull/3408

It have not been merged because of the conflict with gitfast plugin, and now it is far behind the development of `git-extras`, too.

IMHO, I think this zsh completion script should only depend on zsh itself, to avoid  unpredictable conflict with other completion script.

**Comment by GuillaumeSeren** [comment]
Ok thank for your quick feedback @hemanth , I've upgrade a good 30% of the functions but if I will reply here when it's done.

**Comment by GuillaumeSeren** [comment]
@spacewander Oh great !
I will test it, and add my feedback on your PR.

I've upgrade the whole command list and maybe if I implement each missing command it's quite some work, so maybe I can add my work on your PR but if they do not want your upgrade maybe I will have the same issue.

I use antigen to load only needed plugin but if both define the same completion, it may override on option or an other :/

About where keeping the completion file, I think the best should be the upstream because it's easier to find and maintain, but I just discovered this part of zsh, and maybe I miss something, but I find it strange to have an other *layer* between upstream and you, so at least hosting it here will prevent, from conflicts with other git plugin in oh-my-zsh (and there is a lot).

Doing this way will not prevent, user community to make their own version at all, it's quite new for I was to much used to the bash system.

For an additional example I suggest to have a look at the zsh completion for git upstream vs oh-my-zsh:
* upstream: https://github.com/git/git/blob/master/contrib/completion/git-completion.zsh
* oh-my-zsh: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git


Guillaume.

**Comment by teto** [comment]
Hi,
I get a bit confused by the discussion, what's the authorative/recommended completion script ? Even if outdated, shouldn't it be upstream so that contributors can help ?

**Comment by spacewander** [comment]
@teto @hemanth @qw3rtman @nicolaiskogheim 
Maybe we can place the completion script here and tell the user to copy it into `$fpath` after installation.

**Comment by teto** [comment]
fine by me, looks like what most projects do

2016-07-18 16:26 GMT+02:00 罗泽轩 <notifications@github.com>:

**Comment by GuillaumeSeren** [comment]
@spacewander I just arrived, but happy to see some activity on this issue !

I agree the *best* way should be to keep a basic completion script in the upstream source,
and if we have better or we want to override that according to the zsh way we can put it in the userspace.

That way we still can have userspace libs to have 'our own' completion but upstream can provide one, and it can easier for people to commit back upgrade to upstream.

**Comment by GuillaumeSeren** [comment]
@spacewander 
I've just checked again the git project and they added the zsh and tcsh completion file in the upstrream,
so maybe it should be 'a safe move' to follow that practice here !

cf: https://github.com/git/git/tree/master/contrib/completion

**Comment by spacewander** [comment]
I have submitted a zsh completion script in pr #551 
What we need is just source it in `~/.zshrc`.

**Comment by GuillaumeSeren** [comment]
Thank you @spacewander  !
I will test it, instead of the zsh module, but I think this is really the best way (simplest) to do it,
when I switch to zsh, I start complaining about that people tell me "That's the zsh way", 
I was disapointing wich, in the end, lead me to creating this issue.

I am happy to see there no only one road here !

**Comment by slhck** [comment]
I've just installed `git-extras` via `apt-get` on Ubuntu 16.04, and I do not get automatic completion with zsh, whereas I do with Bash.

I understand that when building from source, there is a message that tells users to manually source the completion file in their `.zshrc`. I guess this works, even though it seems a bit intrusive — I've never had to do this for any other project and usually relied on completions from either Oh-my-zsh or automatically installed ones.

For example, from OS X and using Homebrew I'm used to having these kinds of completions be copied to `/usr/local/share/zsh/site-functions`, where they're picked up automatically. Couldn't you do something similar for installs via package managers?

I'm not sure what the most Linux-y way to go is here and how this process could be improved for end-users. (I'm sorry if I've missed something obvious.)

**Comment by spacewander** [comment]
@slhck 

The version of `git-extras` installed via `apt-get` in Ubuntu 16.04 is `4.1.0`. However, the zsh completion script was added later in `4.2.0`.
Sigh, this package is maintained by Ubuntu developer instead of git-extras developer. They just pick up the latest version at that time and never upgrade it.

For the other question, I think your suggestion is reasonable. Instead of requiring users to manually set up the completion script, do it automatically by git-extras is better. I will try to implement this later.

**Comment by slhck** [comment]
Ah, I see. Not sure how to have these Ubuntu packages maintained better.
I don't know if `/usr/local/share/zsh/site-functions` is portable enough, but thanks for considering it!

**Comment by spacewander** [comment]
The progress to set up zsh completion script automatically is blocking now... :cry: 
If I rename the script and put it into `$fpath` with `#compdef git` at the first line, the original git completion would be overrided.
If I don't add `#compdef git`, the script would not be loaded.

**Comment by xtaran** [comment]
@spacewander: I'm sorry, but your comment about git-extras in Ubuntu is wrong in several ways:

* The package is _not_ maintained by an Ubuntu developer. It's based on the according Debian package (well, actually it's identical to it) and that's maintaintained by a Debian developer.
* The package follows upstream releases rather well. Debian Unstable as well as Ubuntu Bionic (future 18.04 LTS) both have the current upstream release 4.4.0.

(Of course, neither Ubuntu nor Debian will pull in new upstream releases into their stable releases. That's the idea behind _stable_ releases. If you don't want that, you need to use the development releases.)

**Comment by spacewander** [comment]
@xtaran 
I agree with the part about Debian package. But if someone is still using Ubuntu 16.04, he/she could only be able to install release 4.1.0. So `pick up the latest version at that time and never upgrade it` is still correct in some ways.

Anyway, it is expected to have a older version installed from package manager.

**Comment by sarpik** [comment]
Hello,
I know this is old, but

1. I've failed setting up zsh completions manually (using $fpath and sourcing), and
2. it'd be great if this could be done automatically on installation

any chance to do so?

Thanks!

**Comment by spacewander** [comment]
@sarpik 
You can open a new issue.
Could you offer us more details about how you set up the zsh completions? For example, the commands you run in each step.

**Comment by spacewander** [comment]
My latest idea about the zsh completion script automatic installation:
Let's follow what the package manager provides.

For homebrew, we can take advantage of the `zsh_completion.install` method to install the script: https://github.com/Homebrew/homebrew-core/blob/master/Formula/youtube-dl.rb#L19
