### ISSUE TITLE
Brew package outdated

### ISSUE THREAD

**Issue by niftylettuce** [tj/git-extras#387]

**Comment by nwinkler** [comment]
It's pointing to release 3.0, which is the most recent one here. I guess someone would have to create a new release (3.1?) and then update the Homebrew formula...

**Comment by nicolaiskogheim** [comment]
Yes. There will be a release pretty soon, and then we update the brew package.

**Comment by apjanke** [comment]
...and if you want to get the latest development version with Homebrew, you can use `brew install --HEAD git-extras`. #454 fixed the build on OS X so it'll work now.

**Comment by qw3rtman** [comment]
Working on it! See #487.
