### ISSUE TITLE
git-changelog should exit with an error code if the editor does

### ISSUE THREAD

**Issue by dominicbarnes** [tj/git-extras#393]
We have a script that wraps around things like `bump`, `git-changelog`, `npm publish`, etc to craft new releases for things. Right now, if I make a mistake in the invocation of this script, it's hard to abort midway.

I discovered that `git-changelog` is optimistic and will ignore the exit code of the editor, even if it's a failure code. I was hoping to force my editor (vim in this case) to exit with a code, and thus abort all subsequent steps of the process.

The point is, if the editor exits with a non-zero, `git-changelog` should propagate that code.

**Comment by markeissler** [comment]
So just to be clear, when you refer to "editor" you mean the editor that's launched by git-changelog?

**Comment by dominicbarnes** [comment]
Yeah, I am talking about the editor opened so you can edit the contents of the changelog.

**Comment by markeissler** [comment]
Take a look at this branch and see if it addresses your requirement...

https://github.com/markeissler/git-extras/tree/changelog-signal-trap

**Comment by dominicbarnes** [comment]
Looks like that works!

**Comment by hemanth** [comment]
@markeissler Would you like to do a PR?
