### ISSUE TITLE
git-release: support adding a prefix to the version tag name

### ISSUE THREAD

**Issue by dominicbarnes** [tj/git-extras#397]
Some teams like to use `v1.0.0` instead of `1.0.0` for the tag name, and I think that should be supported by `git-release` if someone wants to use that convention.

My initial proposal is something like:

```sh
git-release --prefix v 1.0.0
```

**Comment by hemanth** [comment]
`git-release <version>` would be fine, if they need `v` they would pass `v1.0.0` or else just `1.0.0`, addition flag seems like a pain to me.

**Comment by dominicbarnes** [comment]
Oh, that's a good point. I hadn't considered that. (derp)
