### ISSUE TITLE
git effort errors out with bash errors on FreeBSD 10.1

### ISSUE THREAD

**Issue by yggdr** [tj/git-extras#402]
Hi,

running `git effort` yields this:

      file                                          commits    active days

    bash: Skipping importing function definition for `effort': --import-functions required.
    bash: Skipping importing function definition for `active_days': --import-functions required.
    bash: Skipping importing function definition for `date': --import-functions required.
    bash: Skipping importing function definition for `color_for': --import-functions required.
    bash: Skipping importing function definition for `effort': --import-functions required.
    bash: Skipping importing function definition for `active_days': --import-functions required.
    bash: Skipping importing function definition for `date': --import-functions required.
    bash: Skipping importing function definition for `color_for': --import-functions required.
    bash: effort: command not found
…
repeated oftentimes, depending on repository size.

    GNU bash, version 4.3.39(2)-release (amd64-portbld-freebsd10.1)

**Comment by nicolaiskogheim** [comment]
This only happens with `git effort`?

**Comment by yggdr** [comment]
Yes, only `git effort` seems to be affected.

I use `zsh`, but when I run bash manually, define a function in it, then `export -f` still outputs nothing. All the while `type export` reports it being a shell builtin.

**Comment by nicolaiskogheim** [comment]
I'll have this done by the day.

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/
