### ISSUE TITLE
merge-into: change option --ff to --ff-only

### ISSUE THREAD

**Issue by nicolaiskogheim** [tj/git-extras#421]
Our `git merge-into` takes an option `--ff`, which forces fast-forward,  as in, it fails if fast forwarding is not possible. 

1. Should we call it `--ff-only`?
2. If yes, keep support for `--ff` a while?

**Comment by hemanth** [comment]
Yes `--ff-only` makes sense, what do you feel @spacewander ?

**Comment by spacewander** [comment]
I am in favour of this.
