### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by shkm** [tj/git-extras#431]
Hi there,

I was wondering if you might consider supporting settings. In particular, I'd like to use `git feature`, but we use `features/` instead of `feature/`. Having the option to change this would be great, but on the other hand it's quite a simple command and you may prefer to keep it that way.

Thanks.

**Comment by spacewander** [comment]
In my opinions, there are three ways to do it:
1. add an option called `-a|--alias`.
2. use environment variable. But I think it is too complex.
3. add a command called `git grow`(or something like that). We can use `git grow feature` to replace `git feature`, and `git chore`, and more. I like this idea most.

More ideas? @hemanth @nicolaiskogheim

**Comment by hemanth** [comment]
I would vote for `-a|--alias`

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by jldugger** [comment]
@shkm, does the merged PR meet your need?

**Comment by shkm** [comment]
Perfect! Thanks!
