### ISSUE TITLE
Is possible to disable some commands?

### ISSUE THREAD

**Issue by ooopscc** [tj/git-extras#442]
I install git-extras from brew.
And I already map git-pr and git-pull-request to my own command. But this overrides mine.
Because I use Stash often instead of Github.
Is there a way to disable some of these, or make my command (alias in ~/.gitconfig) have a high priority?
Or just delete, rename those conflict ones from `/usr/local/bin`?
Below is my script in git global config file
```shell
[alias]
      pull-request = "!f() { git fetch $1 refs/pull-requests/$2/from:pull-requests/$2; }; f"
      pr = "!f() { git pull-request origin $1; git checkout pull-requests/$1; }; f"
```

**Comment by hemanth** [comment]
Well, not as of now.

We must have a prompt in case of conflicts.

//cc @spacewander

**Comment by ooopscc** [comment]
Thanks, I just rename these two in `/usr/local/bin` with a suffix "github", my aliases work now.

**Comment by spacewander** [comment]
@hemanth 
`$(COMMAND) conflicts with an alias, still install it and disable the alias? [y/n]`
Is this prompt lucid?

**Comment by hemanth** [comment]
:100:

**Comment by spacewander** [comment]
@ooopscc 
When a conflict with `alias` detected, #444 will prompt you to solve it.
Though it may not fully meet your requirement, at least it can avoid overriding existed aliases.

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by ooopscc** [comment]
Thanks.

**Comment by perlun** [comment]
Long time no see, but for the record, I also ran into this now. I've been using `git-extras` for some time (probably a couple of years) and it's working nicely; I appreciate things like `rename-branch`. Now as I upgraded to Debian Bullseye, `git-extras` was also updated and I noted today that one of my existing git aliases stopped working:

```gitconfig
[alias]
    cp = cherry-pick
```

I guess I'll have to `rm /usr/bin/git-cp` for now, but it does feel like a bit of a hack.

If it was possible to somehow make aliases from `~/.gitconfig` take precedence over the choices made by `git-extras`, it would be extremely appreciated.

**Comment by apolzon** [comment]
> Long time no see, but for the record, I also ran into this now. I've been using `git-extras` for some time (probably a couple of years) and it's working nicely; I appreciate things like `rename-branch`. Now as I upgraded to Debian Bullseye, `git-extras` was also updated and I noted today that one of my existing git aliases stopped working:
> 
> ```gitconfig
> [alias]
>     cp = cherry-pick
> ```
> 
> I guess I'll have to `rm /usr/bin/git-cp` for now, but it does feel like a bit of a hack.
> 
> If it was possible to somehow make aliases from `~/.gitconfig` take precedence over the choices made by `git-extras`, it would be extremely appreciated.

fwiw, I was able to just mv `git-cp` to `git-copy` and now `git copy` works as extra's `git cp` did, and restores my cp alias to its previous behavior -- I didn't look at their source, but I would guess their plugin just looks for anything in that folder with the `git-` prefix, so you can effectively rename any of their commands that you want (obviously these changes would get overwritten if you upgrade the plugin)
