### ISSUE TITLE
/usr/local/bin/git-effort: line 165: test: : integer expression expected

### ISSUE THREAD

**Issue by trimtab613** [tj/git-extras#461]

**Comment by nicolaiskogheim** [comment]
1. How did you install git-extras?
2. What was your input when you got this error?
3. What OS are you running on?

**Comment by trimtab613** [comment]
1. `brew install git-extras`
1. `git effort`
1. OS X Yosemite 10.10.5

Cheers!

**Comment by nicolaiskogheim** [comment]
Thank you.

1. Which version of git-extras do you have?
`brew info git-extras`

2. Do you have any files with special symbols in the name? I don't think that should matter, but who knows.

You can try to specify a folder at a time to narrow it down.
`git effort folder/*`


There have been a lot of changes in that file since the last release, so chances are that this won't be an issue once we make a new release. You could try to download and build git-extras if you want to. It's a lot faster and supports some more options.

**Comment by apjanke** [comment]
Can we get an exact copy of the output, with the error messages you're seeing?

Could be related to #455: the BSD `test` and `expr` commands, which OS X uses, don't support all the things the GNU ones do.

**Comment by trimtab613** [comment]
Yes, git-extras 3.0.0. No special characters that I'm aware of. Unfortunately I can't reproduce it today on any of several repos, but the error printout was quite short, if not just that one line in the issue title.

**Comment by shime** [comment]
Happening on my OSX machine too, git-extras version 3.0.0. Here's the output

```
$ git effort

  file                                          commits    active days

  .gitignore................................... 1          1
  LICENSE...................................... 1          1
  README.md.................................... 2          1
  package.json................................. 3          1
  test/features.js............................. 1          1
/usr/local/bin/git-effort: line 165: test: : integer expression expected
```

**Comment by apjanke** [comment]
Looks like the problem was this line.

```
test "$(wc -l $tmp | cut -d' ' -f1 )" -gt 1 && sort_effort
```

The BSD version of `wc` outputs some leading spaces before the line count, so `cut` sees the column structure as different, and gets an empty value for column 1. Fixed by #370.

**Comment by qw3rtman** [comment]
Looks like this was fixed, closing.

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by Restuta** [comment]
```
 git effort --above 15 app/*

  file                                          commits    active days

  app/adapters................................. 52         31
  app/app.js................................... 18         13
  app/components............................... 250        113
  app/controllers.............................. 348        150
  app/mixins................................... 22         13
  app/models................................... 142        84
  app/router.js................................ 45         29
  app/routes................................... 274        123
  app/styles................................... 216        101
  app/templates................................ 456        159
  app/utils.................................... 77         46
/usr/local/bin/git-effort: line 165: test: : integer expression expected
```

`brew install git-extras`
`git effort --above 15 app/*`
`OS X El Capitan 10.11.1`

```
$ git extras --version
3.0.0
```

Should it be reopened or should I create a new one?

**Comment by cztomsik** [comment]
I'm still on mavericks but it happens too...

**Comment by Restuta** [comment]
@qw3rtman  ^^

**Comment by qw3rtman** [comment]
@Restuta and @cztomsik, sorry for the late response!

Looks like the error has been fixed on `master`, but has not been updated on Homebrew (along with a lot of other modifications). As a temporary fix, I would recommend building directly from the repo itself (`git clone https://github.com/tj/git-extras.git`, `cd git-extras`, and then `make install`).

Sorry about the confusion, we'll get a release out on Homebrew as soon as possible!

**Comment by cztomsik** [comment]
Np, thx!

**Comment by apjanke** [comment]
> Alternatively, I think you can run `brew install git-extras --HEAD`, but I'm not 100% sure about that.

You are correct. That will install from the head of the `git-extras` repo. Probably the best option if you currently have it installed with Homebrew.

**Comment by apjanke** [comment]
I take that back... the `brew install git-extras --HEAD` installation is currently broken, because its patch set isn't updated to be compatible with the current head of master.

I'll see if I can fix that.

**Comment by qw3rtman** [comment]
Thanks! :+1:

**Comment by apjanke** [comment]
Okay, I [fixed the Homebrew formula](https://github.com/Homebrew/homebrew/commit/20444af83cd102125d82d77c35cb26fd9c06b521) to be compatible with current head. Do a `brew update` and then `brew install git-extras --HEAD` will work.

**Comment by qw3rtman** [comment]
Great, thanks!

**Comment by Restuta** [comment]
awesome @apjanke
