### ISSUE TITLE
`git touch` with multiple filenames does not work as expected

### ISSUE THREAD

**Issue by al-the-x** [tj/git-extras#467]
Little gotcha:

    $> git touch A B
    $> git status -s
    A  A B

WTF? Internally, the `git-touch` script uses `filename="$*"` and `touch "$filename"`, which turns the argument list `A B` into `"A B"`: a _single_ file named `"A B"` not _two_ files named `A` and `B`).

Patch / PR accepted?

**Comment by al-the-x** [comment]
I ask because I've already fixed for _my_ usage, but I'd like to contribute that upstream.

**Comment by qw3rtman** [comment]
From `man bash`, under the section "Special Parameters":

* `$*` is equivalent to `"$1c$2c..."`
* `$@` is equivalent to `"$1" "$2" ...`

So `A B` becoming `"A B"` is expected.

Regardless, I think `git touch` should follow the functionality you expect, so I would vouch if you sent in a PR. :+1:

**Comment by al-the-x** [comment]
Happy to submit a PR... It's an easy fix.

**Comment by al-the-x** [comment]
Do you mind leaving this issue open until I have a PR to replace it (and link it appropriately)? I don't want to lose track of this issue...

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by qw3rtman** [comment]
No problem, reopened.

**Comment by al-the-x** [comment]
Closed by #481
