### ISSUE TITLE
changelog: option to only show (second line from) merge commits

### ISSUE THREAD

**Issue by JanSchulz** [tj/git-extras#470]
I would like to show only the merge commits and there only the second line, which on github seems to be the title of the PR:

```
commit f799e969108799f0a92c9f7355f3222a7306fa13
Merge: dfe0c79 4b795fc
Author: hemanth.hm <hemanth.hm@gmail.com>
Date:   Sat Oct 10 09:43:36 2015 +0530

    Merge pull request #466 from anarcat/master

    add simple sed command
```

**Comment by spacewander** [comment]
What do you like to name this option?

**Comment by JanSchulz** [comment]
`--only-merges` or  `--merges-only`? I tried to implement it via 

```diff
+      -m | --only-merges )
+        GIT_LOG_OPTS='--merges'
+        ;;
```

but that is completely useless for github merges, as the real information is in the second line. :-/

**Comment by JanSchulz** [comment]
Ok, I tried to include the whole body of the merge commit message: #471
