### ISSUE TITLE
Combine README

### ISSUE THREAD

**Issue by qw3rtman** [tj/git-extras#477]
Combining the README into one file (instead of `Readme.md`, `Commands.md`, and `Installation.md`) would not only reduce the number of files, but would also allow the content in `Commands.md` and `Installation.md` to be seen more, as the README is displayed on the project page itself.

Thoughts?

**Comment by spacewander** [comment]
I vote for it :smile:

**Comment by hemanth** [comment]
I was a singel `README` before, time to go back.
