### ISSUE TITLE
broken git extras commands

### ISSUE THREAD

**Issue by abhisekp** [tj/git-extras#483]
I'm getting this error after installing git extras. This error is shown for all git extras commands.

```sh
▶ git alias                      
: No such file or directory
fatal: 'alias' appears to be a git command, but we were not
able to execute it. Maybe git-alias is broken?
```

I apt-get removed git and reinstalled but no fix. All commands based on git extras are broken.

How to restore or remove git extras to my default programs?

**Comment by qw3rtman** [comment]
What OS are you running? Also, could you provide the version of Git (`git --version`) and git-extras (`git extras --version)`?

**Comment by abhisekp** [comment]
@qw3rtman As i wrote, git extras is all broken. Shows that error with all git extras commands. I simply cloned the master branch and ran `sudo make install`. The `install.sh` was giving the following error.

```sh
▶ sudo sh ./install.sh
[sudo] password for abhisekp: 
: not foundh: 2: ./install.sh: 
./install.sh: 13: ./install.sh: Syntax error: "&&" unexpected
```

I'm using
git version 2.6.3
Ubuntu 15.10 x64

**Comment by abhisekp** [comment]
@qw3rtman any updates on this issue? How to remove git extras?
I used `sudo apt-get install git-extras` this time. But i still see the same error :worried: 
```text
▶ git extras
: No such file or directory
fatal: 'extras' appears to be a git command, but we were not
able to execute it. Maybe git-extras is broken?
```

Shall I just delete the files found using `ls /usr/local/bin/git*`?

**Comment by ktaragorn** [comment]
@abhisekp have you tried `sudo make uninstall`? You might also want to do `apt-get uninstall` as well, and try to remove any other traces of the git command files

**Comment by abhisekp** [comment]
@ktaragorn thanks a lot :smiley: 
`sudo make uninstall` works. 
Then i used `sudo apt-get install git-extras` Perfect.

**Comment by ktaragorn** [comment]
Great! Glad I could help

**Comment by abhisekp** [comment]
@ktaragorn yep! I want to know why it was not working installing from the repo.

**Comment by abhisekp** [comment]
@qw3rtman thanks 
> But I never knew why it was not working when installing using the repo :worried: .

**Comment by qw3rtman** [comment]
@abhisekp Sorry about that, didn't read into this well enough!

Did you checkout the latest tag before you ran `make install`?
```
git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
```

Let me know if that fixes things for you.

**Comment by abhisekp** [comment]
@qw3rtman Everything is fixed using https://github.com/tj/git-extras/issues/483#issuecomment-166532882

And the command you showed was in wiki. That's the first thing i did when I first installed `git-extras` which corrupted my git files.

It's alright. Consider the matter closed for now. And, thanks for the concern.

**Comment by qw3rtman** [comment]
Thanks for bringing this to our attention. We'll keep looking for anything that may be the cause.
