### ISSUE TITLE
Git flow

### ISSUE THREAD

**Issue by sergeysova** [tj/git-extras#486]
Need commands such as `git feature` for git flow

![image](https://cloud.githubusercontent.com/assets/5620073/11546678/cccbe7b8-995f-11e5-8478-354c9f0e6c2c.png)

``` bash
git bugfix AD-123 Drop document after upload
git hotfix AD-543 User not authorise
```

**Comment by spacewander** [comment]
Give [git feature](https://github.com/tj/git-extras/blob/master/Commands.md#git-featurerefactorbugchore) a try?

**Comment by hyperupcall** [comment]
I think that would be out of scope for this project - other projects provide this, such as [nvie/gitflow](https://github.com/nvie/gitflow) and [petervanderdoes/gitflow-avh](https://github.com/petervanderdoes/gitflow-avh).
