### ISSUE TITLE
[RELEASE] v4.0.0

### ISSUE THREAD

**Issue by qw3rtman** [tj/git-extras#487]
Hey all! It's time for a new release, `v4.0.0`!

Here's a list of all the changes made in this release; the full changelog can be found in [`History.md`](https://github.com/tj/git-extras/blob/master/History.md). Please let me know if there are any errors below.

* (#365) prevent `git ignore` from avoiding files it thinks are already in `.gitignore`, but aren't – @rkennedy
* (#368) fix printing special characters (from `git blame` output) in `git line-summary` – @zlx
* (#369) fix hashbangs for `git guilt` and `git merge-into` – @phigoro
* (#370) move from `wc` to `awk` in `git-effort` to avoid `wc`'s different behavior on diffent platforms – @phigoro
* (#372) add installation one-liner that installs latest release from GitHub – @spacewander
* (#373) add documentation for `git line-summary` – @zlx
* (#377) fix `mktemp` behavior on Linux in `Makefile` – @go2null
* (#377) fix `grep` syntax in `git contrib` – @go2null
* (#378) update installation in `git-extras update` – @spacewander
* (#380) keep installation silent – @spacewander
* (#381) modify installation to work with `curl` and `bash` – @spacewander
* (8a3f988) create shorter URL for one-liner installation – @hemanth
* (#383) use more portable `mktemp` implementation in `Makefile` – @somasis
* (#385) add `install.cmd` for installation on Windows – @gisphm
* (#386) use https for `git fork` – @rstacruz
* (#392) improve speed of `git effort` – @nicolaiskogheim
* (#390) fix `git effort` color formatting with `--above` – @nicolaiskogheim
* (#394) make `git changelog` respect status code of editor – @markeissler
* (#396) make sure `git changelog` always looks at `HEAD` – @tocker
* (#399) cleaner way to current branch in `git archive-file` – @nicolaiskogheim
* (#398) require destination branch in `git graft` – @nicolaiskogheim, @muhtasib
* (#388) update all man pages – @chernjie
* (#391) extend `git effort` to accept `git log` options, such as `--since` – @nicolaiskogheim
* (#400) prevent `git effort` from counting untouched files – @nicolaiskogheim
* (#401) make `git effort` exit early to prevent messy error – @nicolaiskogheim
* (#403) write documentation for `git effort --since` – @andreicristianpetcu
* (#406) fix `git extras`, `git changelog`, `git info`, and `git alias` on Windows (`msysgit`) – @southly, @nicolaiskogheim
* (#404) fix `git effort` on FreeBSD – @nicolaiskogheim
* (#405) allow `git effort` to accept filenames with spaces – @nicolaiskogheim
* (#408) rely on `git shortlog` for `git contrib` – @nicolaiskogheim
* (#409) fix `git alias <search-term>` - @nicolaiskogheim
* (#409, #414) update `git alias` documentation – @nicolaiskogheim
* (#415) update dates on `git contrib` man page – @nicolaiskogheim
* (#416) update `git fork` documentation – @nicolaiskogheim
* (#418) fix URL conversion in `git fork` – @nicolaiskogheim
* (#420) update `git line-summary` documentation – @nicolaiskogheim
* (#419) update `git guilt` documentation – @nicolaiskogheim
* (#422) fix "active days" reported by `git effort` – @nicolaiskogheim
* (#424) update examples in `git fork` documentation – @nicolaiskogheim
* (#423) clarify that `git effort` accepts any path, not just filenames – @nicolaiskogheim
* (#426) abort `git-alias` when too many arguments given – @spacewander
* (#411) add `git psykorebase` command – @Natim
* (#429) change `git merge-into` syntax – @nicolaiskogheim
* (#428) update `Commands.md` – @spacewander
* (#430) fix `git-extras update` for Windows users – @spacewander
* (#425) set default for `make` to `install` (`make` -> `make install`) – @nicolaiskogheim
* (#432) fix `git feature` link in documentation – @stevemao
* (#433) add `git clear` command – @grindhold
* (#435) update `git pr` documentation – @nwinkler
* (#437) fix typo in installation script (`install.sh`) – @nwinkler
* (#436) update `git ignore` documentation – @nwinkler
* (#441) don't hide `git checkout` output and prevent running `git checkout` twice in `git bug`, `git chore`, `git feature`, and `git refactor` – @spacewander
* (#440) add alias to `git feature` – @spacewander
* (#445) clean up `git effort` – @nicolaiskogheim
* (#447) alphabetize command list in `Commands.md` – @RichardLitt
* (#446) correctly estimate the number of active days n `git effort` and `git summary` – @ssssam
* (#444) add `git alias` command conflict prompt to `Makefile` – @spacewander
* (#443) make sure `git authors` doesn't return same author twice – @Natim
* (#452) pass `git summary`options to `git line-summary` – @akimd
* (#453) checkout pull requests using a GitHub URL (`git pr https://github.com/tj/git-extras/pull/453` -> makes branch `pr/453`) – @jhnns
* (#454) escape `$` in `Makefile` to fix building on OS X – @apjanke
* (#459) use portable terminal escape sequences in `git effort` – @apjanke
* (#458) refactor `is-git-repo` inclusion logic in `Makefile` – @apjanke
* (#460) protect against character encoding issues in `git summary` – @apjanke
* (#465) fix color formatting in `git effort` and `git scp` – @spacewander
* (#466) add `git sed` command – @anarcat
* (#468) fix purplish color formatting in `git effort` – @spacewander
* (#469) use default installation path in `install.cmd` – @JanSchulz
* (#471) add option to only use merges in `git changelog` – @JanSchulz
* (#448) add `git ignore-io` command – @Lee-W
* (#479) add more information on how to set global `.gitignore` in `git ignore` – @JanSchulz
* (91ca995) update all man pages – @qw3rtman
* (#488) fix missing shebang in `git clear` and permissions on `git show-merged-branches` and `git show-unmerged-branches` (set as executable) – @apjanke
* (#489) allow customizing of `$SYSCONFDIR` (`/etc`) location in `Makefile` – @apjanke
* (#490) put `$SYSCONFDIR` (`/etc`) under `$PREFIX` by default in `Makefile` – @apjanke
* (#481) make `git touch` handle multiple files properly – @al-the-x
* (176ebf9, bb02bdc) update AUTHORS for release – @qw3rtman

Some statistics:
* added **4 new commands** (`git psykorebase`, `git clear`, `git sed`, and `git ignore-io`)
* updated man pages or documentation **16 times**
* fixed installation/update **15 times**
* **30 unique contributors** this release

Here are some things I think we should get in place before the next release. Please let me know if there are any items you think should be added or removed from this list.
* standardize the asking of "yes/no" and make it safer (see a66c944)
* assimilate `Installation.md`, `Commands.md` into one `REAMDE.md` (see #477)
* come up with a release plan (see below)

Additionally, I think we should come up with a release plan and keep up with it to get new features and fixes out on Homebrew sooner (see #461). Also, looking through 208 commits for a release isn't fun. :wink:

Also, I think it'd be cool to have a release name like we did with `v3.0.0 (rad-star)`. I was thinking about `wookiee` in light of the new Star Wars movie that just came out. Thoughts?

![wookiee](https://cloud.githubusercontent.com/assets/1139621/12011600/e37d4a30-ac9a-11e5-9f67-340703c1f3a2.gif)

Lastly, just to confirm: is there anything else we need to do before the release?

Thanks,
Nimit

**Comment by apjanke** [comment]
Technical issue: "wookiee" is spelled with two e's. :)

As far as the release plan, it might be nice to bump [`$VERSION`](https://github.com/tj/git-extras/blob/91ca995edc4d360e5b3b71987d9bf10d65c4e4d4/bin/git-extras#L3) right away after making a release, so installs from `master` are distinguishable from the tagged releases. E.g. after this 4.0.0 release, make it `4.1-dev`, and flip it to `4.1.0` only when making the actual release, and then immediately bump it to `4.2-dev`.

**Comment by apjanke** [comment]
One more minor fix I'd like to get in before the release: `git-clear` is being installed with wrong permissions (mode `444` instead of `555`), which will produce annoying warnings under Homebrew. Just found this while testing `brew install git-extras --HEAD` now. Let me put together a quick PR for that; hold on...

**Comment by qw3rtman** [comment]
@apjanke, oh no! Let me fix that technical issue right away! :wink: 

That release plan sounds like a great idea to me. /cc @hemanth, thoughts?

How often do you think the release cycle should be? I was thinking about a new release every 2 weeks, (following [semver](http://semver.org))? Whenever an issue/PR is created, we can add those to the next release milestone. If it's ready by the 2 weeks, we can merge it in and release; if not, we can push it to the next release.

**Comment by qw3rtman** [comment]
Great! We'll wait for that, @apjanke.

**Comment by apjanke** [comment]
Here you go: #488. It was because `bin/git-clear` was missing a shebang line.

**Comment by apjanke** [comment]
I'm a fan of semver in general.

I don't know `git-extras` well enough to have an opinion on the release cycle timing.

**Comment by qw3rtman** [comment]
@apjanke merged #488 and added the PR to the list up there.

**Comment by rstacruz** [comment]
> How often do you think the release cycle should be? I was thinking about a new release every 2 weeks, (following semver)? 

Releasing immediately when there's anything new might be easier... less things to keep track of, and there's no danger in that anyway.

**Comment by qw3rtman** [comment]
@rstacruz, then users have to update much more often. Additionally, that means we have to test everything (as we do before a release) each time w feature is added. Also, the versions would bump too quickly. Each time an API change is made, we have to bump major according to semver.

**Comment by spacewander** [comment]
We can have a look at the commit frequency with `git log --format="%ci %s" --no-merges`.
IMHO, I think release every two weeks is too rapid, release every month may be better.

**Comment by hemanth** [comment]
SGTM.

I would also vote for monthly release, unless there is a breaking bug (indeed).

**Comment by qw3rtman** [comment]
I'm good with monthly releases as well.

Anything we need to do before the release, @hemanth? If not, I'm ready to do that tomorrow!

**Comment by hemanth** [comment]
@qw3rtman If all is well with #407 we could do a release tomorrow.

**Comment by qw3rtman** [comment]
@spacewander 

- average of **0.878 commits/day**
  - **215 commits** since last release
  - **245 days** since last release
- average of **2.829 *features*/commit** *(bug fix, new functionality, etc.)*
  - **76 pull requests** since last release
  - **215 commits** since last release

Supposing we go with a monthly release cycle (30 days), that's <code>(30 * 0.878) / 2.829 = **9.311**</code> *features* per month. Definitely manageable, IMO. Also, keeping Homebrew up-to-date reduces the number of issues we get that have already been solved on `master` but not yet pushed to Homebrew.

**Comment by Natim** [comment]
> Also, keeping Homebrew up-to-date reduces the number of issues we get that have already been solved on master but not yet pushed to Homebrew.

This is also try with Debian packages.

**Comment by qw3rtman** [comment]
Released `v4.0.0 wookiee` on GitHub! @apjanke, could you work your magic with Homebrew?

**Comment by apjanke** [comment]
The PR is in for the Homebrew update: Homebrew/homebrew#47506. Testing is taking a while tonight.

**Comment by apjanke** [comment]
The Homebrew formula is updated. Homebrew users will now get 4.0.0 the next time they install or upgrade git-extras.

**Comment by qw3rtman** [comment]
Perfect. Thanks, @apjanke! :tada:
