### ISSUE TITLE
Cannot make under FreeBSD 8.1

### ISSUE THREAD

**Issue by henrywood** [tj/git-extras#498]
Hello !

I have trouble building under FREEBSD 8.1:

#/tmp/git-extras-4.0.0 # make install
... installing bins to /usr/local/bin
... installing man pages to /usr/local/share/man/man1
Unknown modifier '-'

Unclosed substitution for eval TEMPFILE  () missing)

Any suggestions ?

Thanks

**Comment by phigoro** [comment]
You may try this port: https://freshports.org/devel/git-extras/

**Comment by spacewander** [comment]
@henrywood 
What is your version of `bash` and `make`?

**Comment by henrywood** [comment]
Make version:

[web118/root] /usr/ports/devel/git-extras # strings `which make` | grep -B1 MAKE_VERSION
5200408120
MAKE_VERSION


Bash version:


[web118/root] /usr/ports/devel/git-extras # bash --version
GNU bash, version 4.1.7(0)-release (amd64-portbld-freebsd8.1)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by spacewander** [comment]
Are you using GNU `make`?
Can you make the Makefile below?
```Makefile
install:
	$(eval TEMPFILE := $(shell mktemp -q $${TMPDIR:-/tmp}/git-extras.XXXXXX 2>/dev/null || mktemp -q))
	@echo $(TEMPFILE)
```

**Comment by henrywood** [comment]
Such a Makefile complains about the $(eval TEMPFILE line):
(in vim at least)

Trying to build yields:

[web118/root] /tmp/git-extras-4.0.0 # make install
Error expanding embedded variable.
[web118/root] /tmp/git-extras-4.0.0 # whereis gmake
gmake: /usr/local/bin/gmake /usr/local/man/man1/gmake.1.gz /usr/ports/devel/gmake
[web118/root] /tmp/git-extras-4.0.0 # whereis make
make: /usr/bin/make /usr/share/man/man1/make.1.gz

Not sure about if it uses GNU make, but it appears not to be the case.

**Comment by spacewander** [comment]
It seems your `make` is the BSD `make`, and it can not recoginize the GNU makefile syntax.
Try `gmake install` and tell us what happen.

**Comment by henrywood** [comment]
Building using gmake install ran smoothly.
Thank you for your help.

**Comment by qw3rtman** [comment]
@phigoro, that port is quite old. I will add the steps @spacewander produced to the installation instructions.

**Comment by qw3rtman** [comment]
I will add the steps @spacewander produced to the installation instructions.
