### ISSUE TITLE
git-count flag for displaying only the number

### ISSUE THREAD

**Issue by adius** [tj/git-extras#510]
There should be flag to output only the number without the "total" in front of it

**Comment by nicolaiskogheim** [comment]
I'll consider adding a `-q` flag to only output the number, but I'm not sure how that would translate to the output of `git count --all`.

All `git count` does is ```echo total `git rev-list --count HEAD` ```. If you want this option for scripting purposes I really suggest you use `git rev-list --count HEAD` instead.
