### ISSUE TITLE
Specify folder for the effort command

### ISSUE THREAD

**Issue by binarykitchen** [tj/git-extras#516]
When I run `git effort --above 15` in my root folder of a nodejs project I get plenty of those warnings

```
fatal: ambiguous argument 'node_modules/babel/test/fixtures/babel-external-helpers/--output-type': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'global/options.json': unknown revision or path not in the working tree.
```

But my source code is in a `./src` folder. Can we have an additional parameter to specify a folder?

**Comment by spacewander** [comment]
You can try wildcard like `git effort --above 15 src/**/*`. Could it work now?

**Comment by binarykitchen** [comment]
@spacewander this does not work for me either. It just tells me the commits of subfolders but I want it to collect the stats for any files in them, recursively.

**Comment by spacewander** [comment]
@binarykitchen 
If you are using bash, you may need to enable `globstar` to expand `**` to zero/more directories. Add it to your `～/.bashrc`:
`shopt -s globstar`

Another way:(maybe easier)
`find ./src -type f -exec git effort --above 15 {} +`

Just list all your source files as additional parameters to `git effort`

**Comment by binarykitchen** [comment]
@spacewander Not sure about globstar since I use zsh instead of bash here.

`find ./src -type f -exec git effort --above 15 {} +` didn't work for me either, getting empty results.

**Comment by spacewander** [comment]
Maybe there is something wrong in `git effort`. However, I could not reproduce it for you.
Could you specify the filename manually and tell us what happened?
Just like `git effort ./src/xxx`.
By the way, what is your `git extra --version`?

**Comment by spacewander** [comment]
Maybe there is something wrong in `git effort`. However, I could not reproduce it for you.
Could you specify the filename manually and tell us what happened?
Just like `git effort ./src/xxx`.
By the way, what is your `git extra --version`?

**Comment by spacewander** [comment]
Maybe there is something wrong in `git effort`. However, I could not reproduce it for you.
Could you specify the filename manually and tell us what happened?
Just like `git effort ./src/xxx`.
By the way, what is your `git extra --version`?

**Comment by binarykitchen** [comment]
@spacewander 

```
~ ❯❯❯ git-extras --version
1.9.1
```

```
~/D/smx3-frontend ❯❯❯ git effort ./src/modules/portal.coffee                                    feature/SCL-1335 ✭

  file                                          commits    active days

  ./src/modules/portal.coffee.................. 1          1
```

**Comment by spacewander** [comment]
Aha! Please update `git-extras` to the latest version.
`git effort` under 1.9.1 supports only one additional file argument.

**Comment by binarykitchen** [comment]
well, i installed it via apt-get and there is no newer version out yet. do you know who manages the git-extra packages for apt-get?

**Comment by spacewander** [comment]
Unfortunely, the package from apt-get is out of date.
The best way to install the latest version is [buiding from source](https://github.com/tj/git-extras/blob/master/Installation.md#building-from-source). It is easy.

**Comment by binarykitchen** [comment]
@spacewander can't you tell the guy who manages the apt-get package to update it?

**Comment by spacewander** [comment]
@hemanth @qw3rtman 
Shall we update the ubuntu package to the latest version, just like the one in debian?
http://packages.ubuntu.com/trusty/git-extras

**Comment by hemanth** [comment]
@spacewander Yup.

**Comment by elalemanyo** [comment]
Hi,
is it possible to filter file type? Just get the commits done to .txt files for example?
By the way: is there a function to get total commits from the effort function?

Thanks!

**Comment by spacewander** [comment]
@elalemanyo 
1.You can use wildcard to specific files, for example, `git effort *.txt`
2. `git effort` doesn't show total commits. You can use `git summary` instead.

**Comment by elalemanyo** [comment]
works great! Thanks!
