### ISSUE TITLE
Rename author in history

### ISSUE THREAD

**Issue by adius** [tj/git-extras#518]
It would be cool if there was a way to rename an author/committer in the history:
[help.github.com/articles/changing-author-info](https://help.github.com/articles/changing-author-info)

Maybe there should also be flags to switch between renaming an author, a committer or both (standard should be both).

**Comment by hemanth** [comment]
PR welcomed :)

**Comment by tardypad** [comment]
@nicolaiskogheim This one can be closed now that my PR is merged

**Comment by nicolaiskogheim** [comment]
Yes 🎉
