### ISSUE TITLE
git fork failed due to two factor authentication

### ISSUE THREAD

**Issue by gogames** [tj/git-extras#521]
Is it possible to add a flag that indicate `ssh` or `https` should be used when `git fork`?

Or is there any way to handle 2fa authentication? Personal access token is not good enough.

**Comment by nicolaiskogheim** [comment]
We have recently changed `git fork` to use ssh when configured, but that is only when setting addresses of remotes. Ref #563.

Forking is only available over https, and we don't have plans for supporting 2fa. I may look into it in the future.

We will be accepting PR's for supporting 2fa authentication with `git fork`. Documentation here: https://developer.github.com/v3/auth/#working-with-two-factor-authentication

**Comment by MaicolBen** [comment]
It would be great to be fixed in `git pull-request` as well

**Comment by spacewander** [comment]
@MaicolBen
2fa support is added in `git pull-request`: https://github.com/tj/git-extras/commit/a88958ba2062503ced49d5515c122d6b517463f1
Could you give the latest release of git-extras a try?

**Comment by MaicolBen** [comment]
it worked! thanks
