### ISSUE TITLE
Clear removes ignored files

### ISSUE THREAD

**Issue by Addvilz** [tj/git-extras#531]
Pretty self-explanatory. Clear removes all untracked files, even the ones ignored. That probably shouldn't happen, or at least there should be a flag for that.

**Comment by hemanth** [comment]
There is a prompt for the same reason with that [command](https://github.com/tj/git-extras/blob/master/bin/git-clear#L3)

**Comment by Addvilz** [comment]
Yes, I get that, but the command would be infinitely more useful with option of not deleting whatever is ignored.

**Comment by hemanth** [comment]
Feel free to do a PR 😇

**Comment by Addvilz** [comment]
@hemanth  the point of opening the issue was to inform about that there is, in my opinion, an issue. If I will find time to implement a fix, I most certainly will do so, however, if someone is willing to address this before me, the info is here.
