### ISSUE TITLE
Cursor disappears on OSX, iTerm2

### ISSUE THREAD

**Issue by sheerun** [tj/git-extras#538]
Hey,

I noticed for some cursor disappears when running `git effort --above 10` command.

Env: OSX 10.10, newest iTerm 2, git extras 4.1.0, git 2.8.3, zsh 5.2

**Comment by hemanth** [comment]
Screenshot?

**Comment by sheerun** [comment]
https://v.usetapes.com/XiYqsCPkKI

**Comment by nicolaiskogheim** [comment]
`git-effort` runs `tput civis` to hide the cursor, which, apparently is working. Then it runs `tput cvvis` to reveal the cursor.

What happens if you run those two in sequence?

```sh
$ tput civis
$ # cursor should be hidden
$ tput cvvis
$ # cursor should be visible
```

**Comment by sheerun** [comment]
The effect is the same, cursor doesn't appear.

It seems it only happens when using newest tmux 2.1 (default configuration of zsh and tmux).

**Comment by sheerun** [comment]
It happens also on Terminal app, so most likely the issue is with tmux (or tput?)

**Comment by sheerun** [comment]
I filed the issue on tmux repo. Could you disable cursor hiding when $TMUX is set?

**Comment by sheerun** [comment]
tmux guy says it may halpe to use `cnorm` instead of `cvvis`

**Comment by sheerun** [comment]
It helped when I changed following:

```tmux
set -g default-terminal "screen-256color"
```

to 

```tmux
set -g default-terminal "xterm-256color"
```
