### ISSUE TITLE
Time to add nicolaiskogheim as a collaborator. 

### ISSUE THREAD

**Issue by hemanth** [tj/git-extras#539]
Based on the awesome activities of @nicolaiskogheim on `git-extras` he would be one of the collaborators, in case one of use get hit by a truck (touch wood) there still will be collaborators to take care of this project ;) 

//cc @tj

**Comment by tj** [comment]
added!

**Comment by hemanth** [comment]
Thanks!

Welcome to the club, @nicolaiskogheim.

**Comment by nicolaiskogheim** [comment]
Much appreciated! Thank you, guys :)
