### ISSUE TITLE
git-pull-request needs user.email but does not check global includes

### ISSUE THREAD

**Issue by smemsh** [tj/git-extras#546]
In `git-pull-request` there is on L29:
```
user=$(git config --global user.email)
test -z "$user" && abort "git config user.email required"
```

but if I set `user.email` from an include section via `~/.gitconfig`, this is not shown due to this default behavior of git:

```
--[no-]includes
        Respect include.*  directives in config files when looking up
        values. Defaults to off when a specific file is given (e.g., using
        --file, --global, etc) and on when searching all config files.
```
this would force me to set `user.email` directly in `~/.gitconfig` and not in an `[include]` section.  I think this is not really a sane default for git, but nonetheless, that's what they chose.  Therefore `git-pull-request` needs to add `--includes` to this line to pull it in.  What might also work is removing `--global` (which works fine, and pulls in includes).  I don't see why it's needed; only the value is really needed, it should not matter if it comes from repo-local, global, include, or wherever.

**Comment by smemsh** [comment]
note, I did not look elsewhere in the source tree to see if this same problem exists in other subcommands; it may.  The tools shouldn't require the user to use a single-file flat `.gitconfig`.

**Comment by spacewander** [comment]
Would you like to send a pr?

**Comment by nicolaiskogheim** [comment]
I've opened a PR that should resolve this issue.

**Comment by nicolaiskogheim** [comment]
@smemsh Please re-open if your issue still persist.
