### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by tardypad** [tj/git-extras#549]
Following the start of the discussion in #548: it reminded me to be more careful about compatibility between OSes, and as well to check not to use any Bash 4 specific feature for example.

Maybe as a suggestion, it would be a good start to have a CONTRIBUTING kind of file in the repo to offer general guidelines about:
- the kind of operating systems contributors should try to support
- same with Bash versions
- same with Git versions
- usage of non builtin commands
- ...

**Comment by spacewander** [comment]
Let's start a discussion on it :)

* Should support Mac and Linux
* Should support Bash 3 or newer
* Should support Git 2.1+

Could everyone agree on these? Anything else?

**Comment by nicolaiskogheim** [comment]
I'm not very familiar with the differences between Bash 3 vs Bash 4, and I imagine few are, so here is a reference link we can put alongside the document: [Bash versions](http://tldp.org/LDP/abs/html/bash2.html)

I briefly looked over the Bash 4 notes, and it's almost only features I've never used, and never seen here, so we should be safe, but we have to test all our code somehow. At the least we should run every command with some standard arguments on travis with Bash 3 and Git 2.1.

As for Git: I think most people have at least 2.1, but the servers we use at my university has 1.9. Supporting <2.0 might not be worth it; I agree on 2.1, and if a lot of people want it for <2.0 we can look at it then.

**Comment by spacewander** [comment]
@nicolaiskogheim 
Great job! Thanks for your link.

**Comment by tardypad** [comment]
Thanks, I guess we can close this one now then.
Or do you keep __discussion__ label issues always open?

**Comment by nicolaiskogheim** [comment]
No, this should be closed as well. Good spot. I should've done it when we merged #555.

We may want to improve our guidelines, but we will create new issues when that happens.
