### ISSUE TITLE
`git missing` using `--no-merges` doesn't seem to work as expected

### ISSUE THREAD

**Issue by nuragic** [tj/git-extras#562]
Hello,

I'm trying to use the `git missing` with the `--no-merges` param but it doesn't work as (at least I)  expected: it returns the same list as calling it without the `--no-merges` param, listing all the commits including the merge ones.

I'm using `git missing branch1 branch2 --no-merges`.

If I try to run  `git missing branch2 --no-merges` or `git missing --no-merges branch2` it throws, respectively:

`fatal: unrecognized argument: --no-merges...branch2`

````
fatal: ambiguous argument 'branch2...--no-merges': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I don't know if it's a bug or I've just misunderstood the command, however in the man page it says that the same parameters as `git log` can be used.

Thanks! 😄

**Comment by nicolaiskogheim** [comment]
Thank you for bringing our attention to this one. `git-missing` is definitely not supposed to behave like that :)

There are two bugs (that I was able to spot, at least). The first is that the two first arguments to `git missing` is always assumed to be branch names. The second is that arguments after that are discarded.
