### ISSUE TITLE
git standup is not a git command

### ISSUE THREAD

**Issue by mawaldne-surge** [tj/git-extras#582]
Hello, 

I'm on git extras version 4.1.0. I try to run `git standup` and it doesn't work.

```
➜  git-extras git:(master) git extras --version
4.1.0
➜  git-extras git:(master) git standup
git: 'standup' is not a git command. See 'git --help'.
➜  git-extras git:(master) git standup --help
No manual entry for gitstandup
```

**Comment by spacewander** [comment]
`git standup` is introduced after version 4.2.0-dev, which is not released yet. If you need it, you can install it via source.

**Comment by mawaldne-surge** [comment]
Thanks. I saw it on https://github.com/tj/git-extras/blob/master/Commands.md but assumed it would be on the 4.1 version.
