### ISSUE TITLE
git release not pulling commit history

### ISSUE THREAD

**Issue by eman6576** [tj/git-extras#593]
Hi,

When performing `git release v0.1.0 -c` in the terminal and taken to VIM to edit, it doesn't show the latest commit messages. Is there something that needs to be configured correctly?

**Comment by spacewander** [comment]
Could you tell us the way to reproduce it? What is your environment?

**Comment by eman6576** [comment]
I am running OS X, and using Bitbucket. Now when using other repos, it does work. But this particular repo doesn't. So I think it is an issue with the configuration but I'm not sure exactly.

**Comment by spacewander** [comment]
I could not reproduce it with repo cloned from Bitbucket under OS X. So I guess it may be a repo specific problem. `git release` will show the commit messages since most-recent untagged commit. Therefore, could you run `git log --oneline --decorate --tags` to show the latest tag?

**Comment by eman6576** [comment]
It doesn't show the latest tag

**Comment by spacewander** [comment]
@eman6576 
Could you checkout this [version](https://github.com/spacewander/git-extras/tree/fix_release) and confirm if your problem is fixed?
