### ISSUE TITLE
git author --no-email flag is not working

### ISSUE THREAD

**Issue by h2non** [tj/git-extras#607]
Running latest `git-extra` running in OSX and installed via homebrew:

When running command from documentation:
`git authors --list --no-email`

Emails are always printed.

**Comment by troystevenhunt** [comment]
607'_678*

**Comment by spacewander** [comment]
@h2non
The `--no-email` option is added after `4.2.0`, the latest release.
If you want to use this feature, you can install it via source.

**Comment by hemanth** [comment]
@spacewander We need to make a new release soon!

**Comment by spacewander** [comment]
@hemanth 
Great! Maybe at the end of this year? We can open a new issue to discuss it.

**Comment by hemanth** [comment]
#534 has been in open state for a decent amount of time now! @spacewander

**Comment by h2non** [comment]
Thank you, guys. Feel free to close this issue.
