### ISSUE TITLE
[Support] git-extras not installed on Windows 10

### ISSUE THREAD

**Issue by Kristinita** [tj/git-extras#612]
### 1. Summary

I can not install git-extras to my Windows 10.

### 2. Expected behavior

Successfully begin to use git-extras.

### 3. Actual behavior

```
SashaChernykh@DESKTOP-0G54NVG E:\git-extras
$ install.cmd "E:\Chocolatey\tools\msys32\mingw64"
Using git install path "E:\Chocolatey\tools\msys32\mingw64" as PREFIX, please make sure it's really a
path to the mingw64 directory...

Installing to E:\Chocolatey\tools\msys32\mingw64
Installing binaries...
Installing man pages...

done
Invalid code page
```

```
SashaChernykh@DESKTOP-0G54NVG E:\git-extras
$ install.cmd "C:\Program Files\Git"
Using git install path "C:\Program Files\Git" as PREFIX, please make sure it's really a
path to the mingw64 directory...

No mingw64 folder found in C:\Program Files.

Please supply a proper "Git for Windows 2.x" install path:
"install.cmd c:\[git-install-path]"
Invalid code page
```

```
SashaChernykh@DESKTOP-0G54NVG E:\git-extras
$ git-extras
'git-extras' is not recognized as an internal or external command,
operable program or batch file.
```

### 4. Steps to reproduce

I install via Chocolatey [**git**](https://chocolatey.org/packages/git) to `"C:\Program Files\Git"` folder and [**msys2**](https://chocolatey.org/packages/msys2) to `"E:\Chocolatey\tools\msys32\mingw64"` folder. I have not problems with git before.

In the root directory of `E` disk I run command `git clone https://github.com/tj/git-extras.git`. `cd git-extras` → I get actual behavior.

### 5. Feature request

Please, review [**this pull-request**](https://github.com/tj/git-extras/issues/611). Now installation for Windows users much harder than for others operation systems.

### 6. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**git:**
git version 2.11.0.windows.1
**MSYS2:**
20160719.1.1

Thanks.

**Comment by boutmansb** [comment]
I have the same issue while trying to install on Windows 10. I have both just running the install.cmd and running with the path. Both give me the same result:
`Installing binaries...
Installing man pages...

done
Invalid code page`

**Comment by spacewander** [comment]
@boutmansb 
Do you try the latest code from the master branch?
Maybe your problem is fixed after this pr: https://github.com/tj/git-extras/pull/676

**Comment by boutmansb** [comment]
@spacewander Yes! Installing works. Thank you for the help.
