### ISSUE TITLE
[Git Summary] Comma in author name is always shown as spaces

### ISSUE THREAD

**Issue by Dark-Water** [tj/git-extras#618]
When author names have a comma inside (e.g. surname, forename) the summary show always spaces instead of a comma.

* Only author names with a comma -> the commas are parsed into two spaces
* Differed author name pattern -> the commas are parsed into to 20+ spaces

**Comment by spacewander** [comment]
@Dark-Water 
Just submit #619 to fix it.
Does it work well as you prefer?

**Comment by TobiasSekan** [comment]
Thanks :-) It's perfect

**Comment by Dark-Water** [comment]
fixed :-)
