### ISSUE TITLE
[Git summary] Invalid or incomplete multibyte or wide character

### ISSUE THREAD

**Issue by TobiasSekan** [tj/git-extras#620]
Hello,

when there is a `é`  inside a author name, git-summary break with error:

> column: read failed: Invalid or incomplete multibyte or wide character

`git shortlog -n -s` parse the `é` in `<C3><A9>`

Is there a way to fix that?

**Comment by spacewander** [comment]
Have you set `LC_CTYPE` to something with `.UTF-8` suffix?
It seems that your terminal doesn't support UTF-8.

**Comment by TobiasSekan** [comment]
Hello,

My settings are:

> $ locale
> LANG=de_DE.UTF-8
> LC_CTYPE="C"
> LC_NUMERIC="C"
> LC_TIME="C"
> LC_COLLATE="C"
> LC_MONETARY="C"
> LC_MESSAGES="C"
> LC_PAPER="C"
> LC_NAME="C"
> LC_ADDRESS="C"
> LC_TELEPHONE="C"
> LC_MEASUREMENT="C"
> LC_IDENTIFICATION="C"
> LC_ALL=C

> $ sudo locale-gen                                                                                                                                  
> Generating locales...
>   de_DE.UTF-8... done
>   de_DE.ISO-8859-1... done
>   de_DE.ISO-8859-15@euro... done
>   en_US.UTF-8... done
> Generation complete.

System:
Arch Linux -> LXDE -> guake -> zsh -> oh-my-zsh

**Comment by spacewander** [comment]
@TobiasSekan 
Try set `LC_CTYPE` to `de_DE.UTF-8`.
Does it work for you?

**Comment by TobiasSekan** [comment]
Hello,

Perfect, it works now :-)

Thank you.

> $ locale
> LANG=de_DE.UTF-8
> LC_CTYPE=de_DE.UTF-8
> LC_NUMERIC="de_DE.UTF-8"
> LC_TIME=de_DE.UTF-8
> LC_COLLATE=de_DE.UTF-8
> LC_MONETARY="de_DE.UTF-8"
> LC_MESSAGES="de_DE.UTF-8"
> LC_PAPER="de_DE.UTF-8"
> LC_NAME="de_DE.UTF-8"
> LC_ADDRESS="de_DE.UTF-8"
> LC_TELEPHONE="de_DE.UTF-8"
> LC_MEASUREMENT="de_DE.UTF-8"
> LC_IDENTIFICATION="de_DE.UTF-8"
> LC_ALL=
