### ISSUE TITLE
Stop release if pre-release hook fails

### ISSUE THREAD

**Issue by breneser** [tj/git-extras#650]
`git release 1.0.0` does not fail even if pre-release hook exits with error. It should continue with release if pre-release hook fails.

**Comment by bersace** [comment]
Actually, i don't understand why all script don't have `set -eu` at least. This lead to such odd behaviour.

**Comment by breneser** [comment]
@bersace I agree myself. I always use `set -euo pipefail`

**Comment by spacewander** [comment]
@bersace 
Some scripts expect to fail and then make a fallback, so we could not simply apply `set -eu` to all scripts.

Anyway, these `fail quickly` options are really useful!
For shell scripts that used in production environment, `set -e` is required in my team's code style guide.
In the next code review, we should force every contributor to use them if possible.
