### ISSUE TITLE
git-delete-merged-branches

### ISSUE THREAD

**Issue by jairhenrique** [tj/git-extras#653]
```fish
git-extras -v
4.3.0
```

```fish
git-delete-merged-branches
xargs: illegal option -- r
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
```

**Comment by spacewander** [comment]
@jairhenrique 
Would you like to confirm whether #654 fixes the problem?
Just need:
1. `git clone https://github.com/spacewander/git-extras -b replace-xargs-r && cd git-extras && sudo make install`.
2. try `git-delete-merged-branches` again.

**Comment by hemanth** [comment]
Oops, I was too fast ;)?
