### ISSUE TITLE
git delete-merged-branches is broken on OSX

### ISSUE THREAD

**Issue by rgreinho** [tj/git-extras#655]
https://github.com/tj/git-extras/pull/602 added the `-r` switch to the `xargs` command, but it is not available on OSX.
```
$ git delete-merged-branches
xargs: illegal option -- r
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
```
System info:
```system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.6 (15G1421)
      Kernel Version: Darwin 15.6.0
```

**Comment by spacewander** [comment]
@rgreinho 
Could you install `git-extras` directly from source?
1. download [git-delete-merged-branches](https://raw.githubusercontent.com/tj/git-extras/master/bin/git-delete-merged-branches)
2. cp it to `/usr/local/bin/git-delete-merged-branches`

We just fixed the problem earlier this week.

**Comment by rgreinho** [comment]
Done! It works like a charm.

Thank you!

**Comment by ecbrodie** [comment]
@spacewander any idea when this will be released (ie, to Homebrew)?

**Comment by ecbrodie** [comment]
I will move this question into its own issue.
