### ISSUE TITLE
publish 4.4.0

### ISSUE THREAD

**Issue by stephenmathieson** [tj/git-extras#657]
it's been quite awhile since a release has been cut, and [4.4.0-dev is over a month old](276a30778053a2f2e23a1f68e4c632a275dce0cf). any way you could publish a proper release soon?

**Comment by spacewander** [comment]
@stephenmathieson
We adopt a long release cycle, only release a new version half a year.
If you want to use the latest feature, you could install it from source.

**Comment by stephenmathieson** [comment]
ah, ok 

out of curiosity- is there any reason you chose to do this? it's a very different policy than what was previously in place

**Comment by spacewander** [comment]
IMHO, there is no significant reason to do it.
Perhaps because git-extras is mature, and few features are required in each release cycle.
So the release cycle slows down, and finally stop at half a year.

**Comment by stephenmathieson** [comment]
since there is no "no significant reason to do it", it seems to me that maybe we should go back to the regular release cycle?

not a big deal either way, as i can just install from source. i'm just updating my dotfiles and wanted to pin a specific version of this repo... i'll use 4.3 for now
