### ISSUE TITLE
git bulk only in git repo locations possible

### ISSUE THREAD

**Issue by nschlimm** [tj/git-extras#661]
Hello,
currently git bulk is only available when you are in a git repository location. However, to setup the workspace for git bulk, one need to be in non-git-repo locations, for instance in the parent directory of your development workspace. These directories typically aren't git repository locations. Currentli git-extras does not permit to execute any git extras command in non git-repo location. For git bulk, this is not correct. Git bulk needs to be available in non-git repo directories ...
regards,
niklas

**Comment by spacewander** [comment]
@nschlimm 
You could add `git-bulk` to https://github.com/tj/git-extras/blob/master/not_need_git_repo.
Would you submit a pr? Thanks!

**Comment by nschlimm** [comment]
Done
