### ISSUE TITLE
[Question] Flexibility on contributing guidelines

### ISSUE THREAD

**Issue by nickolasburr** [tj/git-extras#663]
Hi all,

I was reading through the Contributing guidelines and I see there's a requirement to use Bash 3.2+. Is there any flexibility on that? I have a Perl script (see [here](https://github.com/nickolasburr/git-follow)) which I think would make a nice addition to git-extras.

**Comment by spacewander** [comment]
Although `git flow` is a nice tool, I am afraid we could only accept bash script.

**Comment by spacewander** [comment]
Just close it now. Please reopen the issue if you need.
