### ISSUE TITLE
git delete-merged-branches fails due to xargs

### ISSUE THREAD

**Issue by ecbrodie** [tj/git-extras#665]
I'm not entirely sure if this issue is directly related to **git-extras** or due to something else. Anyway, I am unable to run `git delete-merged-branches` successfully. I always get this error:

```
$ git delete-merged-branches
xargs: illegal option -- r
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
```

I can confirm that `git branch --merged` works successfully. Thank you for the help in advance.

**Comment by spacewander** [comment]
@ecbrodie 
It's a bug of `git-extras`. See https://github.com/tj/git-extras/issues/655.
Currently, you could re-install `git-delete-merged-branches` from source to fix it:
1. download [git-delete-merged-branches](https://raw.githubusercontent.com/tj/git-extras/master/bin/git-delete-merged-branches)
2. cp it to `$(which git-delete-merged-branches)`

**Comment by ecbrodie** [comment]
Thank you @spacewander. I will close this because it is a dupe.
