### ISSUE TITLE
FEATURE REQUEST: command to view the repo online

### ISSUE THREAD

**Issue by ecbrodie** [tj/git-extras#666]
It would be great if there was a command to view the repo online. It would help me save some clicking around on my computer (ie, open up browser, type URL, press enter; versus a single simple CLI command that I could even alias to something shorter).

This is essentially going to be the equivalent of [git town repo](https://github.com/Originate/git-town/blob/master/documentation/commands/repo.md).

I don't mind personally working on a PR to introduce this, I just want to check first if there is interest to adding this command. Thank you.

**Comment by ecbrodie** [comment]
...and now I feel bad about having an unlucky issue number 😞

**Comment by spacewander** [comment]
@ecbrodie 
A tool to view the repo online is useful.
I am glad to see such a pull request.

Note that we only accept bash script. There might be some difficulties to implement it. Good luck!

**Comment by nicolaiskogheim** [comment]
My initial thought was to use `open(1)` on mac and `xdg-open(1)` for linux.
So we can read the remote url, convert it to a url if it's not, and pass it to the open command.

Keep in mind:
**Different protocols**:
 - https: `https://example.com/gitproject.git` (These can all just be `open`ed, I think)
 - ssh: `ssh://user@server/project.git` and the more common `user@server:project.git`
 - git: `git://` (I didn't find a proper example here)
 - local: `/opt/git/project.git` and `file:///opt/git/project.git`. We should not crash on those, but it's probably not wanted to open the 

**Different hosts with different formats**:
This only matters for the `ssh` (and maybe `git`) protocol, as `https` can just be opened in the browser.
- Github `ssh`: `git@github.com:tj/git-extras.git`
- Bitbucket `ssh`: `git@bitbucket.org:tj/git-extras.git`

I don't know if it's enough to just get the *url* and *dir* from `git@url:dir` in every case, but it's a start.

**Different remotes:**
- No remotes: Fail gracefully
- One remote: open that remote (people usually have origin)
- Multiple remotes: I can have `upstream`, `origin` and possibly more forks. Maybe require the remote to be specified and not just default to `origin`.

**Comment by derimagia** [comment]
We recently converted @paulirish's https://github.com/paulirish/git-open to be more generic with the online repos. It's just a bash script. I'm pretty happy with how it turned out although I'm sure there could be improvements.

**Comment by mapitman** [comment]
Is there still any interest in adding this to git-extras? I am writing a script at the moment that is fairly simple and just supports opening the website for the repo. It uses sed, is that allowed in git-extras scripts? If so, I'll submit a pull request soon.
