### ISSUE TITLE
Requesting release of version 4.4.0

### ISSUE THREAD

**Issue by ecbrodie** [tj/git-extras#667]
I would like to request that a release of version 4.4.0 of git-extras be cut. There are some new changes that git-extras users could benefit from (my main interest is the `git remove-merged-branches` fix from #655), without needing to build from source.

What are the guidelines for determining when a new version should be cut? Is there any way that I could personally help out with this?

**Comment by spacewander** [comment]
Obviously, we have to make a release eariler than original plan now...
I will try to get it done this weekend.

**Comment by spacewander** [comment]
@ecbrodie 
We just released the version 4.4.0. 😃
