### ISSUE TITLE
Git pull-request doesn't work if 2-factor auth is enabled

### ISSUE THREAD

**Issue by dragGH102** [tj/git-extras#673]
As per the title.

# Error

```
{
  "message": "Must specify two-factor authentication OTP code.",
  "documentation_url": "https://developer.github.com/v3/auth#working-with-two-factor-authentication"
}

```

**Comment by spacewander** [comment]
@dragGH102 
Could you take some time to verify whether #674 fix your problem?

You could install it from source like this:
```
$ git clone https://github.com/spacewander/git-extras.git -b pull-request-two-factor-auth
$ cd git-extras
$ [sudo] make install
```

Reference: [Building from source](https://github.com/tj/git-extras/blob/master/Installation.md#building-from-source)

**Comment by dragGH102** [comment]
@hemanth where do I find "two factor auth code"?

Thanks in advance
