### ISSUE TITLE
Customize the format of the History.md file ? 

### ISSUE THREAD

**Issue by matzew** [tj/git-extras#677]
Hi,

I generally like the style of the `git-changelog`, like:
https://github.com/tj/git-extras/blob/master/History.md

But, I was wondering what's the best way to customize it ? 

I am interested in having the short hash of the commit at the end of the line, like:
```
* the commit message subject (the-hash)
```

Any thoughts ?

**Comment by spacewander** [comment]
You could use `git config changelog.format $format` and `git config  changelog.mergeformat $format` to customize the changelog format.  The format string `$format` will be passed to `git log --pretty=format:xxx`. The default value of them are `  * %s` and `  * %s%n%w(64,4,4)%b`.

**Comment by spacewander** [comment]
I updated the doc in commit https://github.com/tj/git-extras/commit/46bc0959e1f7ff9c8c39a4694a5fe122f1d0e199. Please reopen this issue if you still have question.
