### ISSUE TITLE
git-release semver support

### ISSUE THREAD

**Issue by tjaartvdwalt** [tj/git-extras#683]
It would be useful if `git-release` could automatically calculate the next semantic version, without having to specify it explicitly.

```shell
# if our current latest tag is `1.0.0` 
git-release --semver patch # releases 1.0.1
git-release --semver minor # releases 1.1.0
git-release --semver major # releases 2.0.0
```

A simpler solution may be to drop the `--semver` option and pass `patch|minor|major` as reserved keywords instead of `<tagname>`.

```shell
git-release patch
git-release minor
git-release major
```

The only downside with this usage is that you cannot release tags with the names `patch|minor|major`.

**Comment by spacewander** [comment]
@tjaartvdwalt 
Please correct me if I am wrong.
AFAIK, there is no `--semver` option in `git-release`...

**Comment by tjaartvdwalt** [comment]
Yes, I propose that we should add it.

**Comment by spacewander** [comment]
I will spend some time on it this weekend.

**Comment by spacewander** [comment]
@tjaartvdwalt 
Could you verify the pull request #686?
Just pull it down and install from source.

**Comment by tjaartvdwalt** [comment]
@spacewander thank you for implementing this so quickly! It works great!

One small comment I have, is that some projects release with some text in front of the version number. For example: a tag may be `v1.0.0` instead of just `1.0.0`. 

If you use the current version of the script, the `v` will get stripped in subsequent releases.

Personally it does not bother me, but  I just thought I would mention it.

If you are happy, we can close this issue.

**Comment by spacewander** [comment]
@tjaartvdwalt 
Well, the `semver` format requires the MAJOR part should be non-negative number. Anyway, I just submit a new pr #687 to fix in this scenario.

**Comment by spacewander** [comment]
Considered solved. Feel free to reopen this issue if there is any question.
