### ISSUE TITLE
git undo should preserve/restore the staging area

### ISSUE THREAD

**Issue by bittner** [tj/git-extras#689]
Current Behavior
----------------
When I run `git undo` after just having committed some changes, that commit is undone and the _changes are unstaged_. (This potentially mixes the changes committed earlier with changes that I did not intend to commit, i.e. changes that I intentionally did not put in the staging area.)

Expected Behavior
----------------
It would be nice if the commit could simply be undone and the changes were left there _in the staging area_. This way I could, e.g., open a new branch and commit the changes there. (This is my very common use case, when I erroneously commit to the protected `master` branch).

I currently get the expected behavior with the following _git alias_:
```ini
undo-commit = reset --soft HEAD^
```

**Comment by spacewander** [comment]
@bittner 
> commit is undone and the changes are unstaged

This behavior is documented in `git help undo`, it is intentional and I don't want to break the compatibility.

**Comment by bittner** [comment]
Well, the man page doesn't say anything about that behavior. In fact, the description of the `--soft or -s` option suggests that the default behavior would be keeping the changes in the staging area:
```
OPTIONS
       --soft or -s

       This is the default, only rolls back the commit but changes remain un-staged.
```
It's a bit irritating, actually. I would expect that the text said, _"... but changes remain staged"_.

**Comment by spacewander** [comment]
@bittner 
Well, it looks like that the `but changes remain un-staged` is misleading. What  actually happens is `and make changes un-staged`.
Maybe we should update the documentation to make it clear.

**Comment by bittner** [comment]
If this is possible in any way I'd rather make the documentation more clear (i.e. change to _"... but changes remain staged"_) for the `--soft` option, and make Git keep the changes in the staging area.

I think this would make sense, because otherwise what is the difference between the default behavior and `--soft`?

Also, the `--soft` should ideally match the behavior of `git reset --soft HEAD^`, don't you think so? That would be the case then. And currently this is not the case, which is a little irritating, maybe even contradictory.

**Comment by spacewander** [comment]
@bittner 
Yes, pull request welcome!

**Comment by bittner** [comment]
Would it be okay to include the changes re the `--soft` option that I suggested above?

1. keep the default behavior as it is (i.e. `git undo` un-does the latest commit _and_ unstages the changes)
1. make the `--soft` option behave like `git reset --soft HEAD^` (so that the changes remain staged)
1. change the documentation of the `--soft` option to `Rolls back the commit and keeps the changes in the staging area.`

Why?
----
This would allow the following use case:

1. I make a commit and figure out I did it on, say, the wrong branch
1. I run `git undo --soft`
1. I checkout or create the appropriate branch (e.g. a new feature branch)
1. I make the commit again (`git commit -m '...'`)

With the current behavior I would need to add a "I add the changes to the staging area" step between step 3. and 4. above.

**Note** that I'm reluctant to use `git commit -a -m '...'`, because I sometimes have unstaged changes that I don't want to commit. Actually, that is one of the main reasons why I don't want the undone changes from the last commit to be unstaged: They would mix up with the currently unstaged changes. Chaos results thereafter!

**Comment by spacewander** [comment]
@bittner 
I know it's good to follow the behavior of `git reset --soft`. But change the behavior of `git undo --soft` will break the backward compability.

Well, you could mention the difference between `git undo --soft` and `git reset --soft`, and the history issue.

**Comment by bittner** [comment]
> change the behavior of `git undo --soft` will break the backward compability.

Well, if we assume nobody used the `--soft` switch explicitly since it was the default anyway we could change its meaning, somewhat, safely.

Otherwise, we may need another switch to provide the behavior I described above.

I would advise against the latter, though, based on the fact that `git reset` _alone_ has a behavior other than with `--soft` by default. By making the `--soft` switch _not_ the default we would align `git-undo`'s behavior with `git reset`'s behavior, if I'm not completely mistaken.

**Comment by bittner** [comment]
If that's okay I would prepare a PR updating [code](https://github.com/tj/git-extras/blob/master/bin/git-undo#L28-L37) and [documentation](https://github.com/tj/git-extras/blob/master/man/git-undo.md).

**Comment by bittner** [comment]
Just stumbled upon it again. It absolutely makes sense to have a `--soft` option that provides additional value - and keep the current default behavior. I'll prepare a PR.

**Comment by bittner** [comment]
Just had a case right now with `git undo`, having added a Git submodule beforehand. Re-adding the files removed from the staging area prints out a frightening message, and you pray to the lords of gitkind that everything will work out later (with the submodule): :worried:

```bash
$ git undo
$ git add -v .
add '.gitmodules'
warning: adding embedded git repository: foobar
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint:   git submodule add <url> foobar
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint:   git rm --cached foobar
hint:
hint: See "git help submodule" for more information.
```
It would have helped to have a `git undo --soft`.

Anything missing in my PR #723?

**Comment by druud** [comment]
Add a '--keep-staged' option, and document that --soft sets that?

**Comment by spacewander** [comment]
Merged #723 as a break change.

**Comment by bittner** [comment]
OMG!! OMG!! Thank you! :heart_eyes: :tada: :clinking_glasses: :champagne: :balloon:

**Comment by spacewander** [comment]
@bittner 
You are welcome!
