### ISSUE TITLE
git-extras does not list all commands

### ISSUE THREAD

**Issue by adius** [tj/git-extras#701]
e.g. `git obliterate` is not listed when I run `git extras`

**Comment by spacewander** [comment]
@adius 
Fixed in https://github.com/tj/git-extras/commit/f5d99bcac94b6dc14bd96e15c37773b3ff1719db

**Comment by sergiomb2** [comment]
hum btw git-pull-request is also missing but I ask to rename it https://github.com/tj/git-extras/issues/702

**Comment by spacewander** [comment]
@sergiomb2 
`git-pull-request` is added in https://github.com/tj/git-extras/commit/f5d99bcac94b6dc14bd96e15c37773b3ff1719db too.

**Comment by spacewander** [comment]
Consider it fixed. Be free to reopen it if it is not solved.
