### ISSUE TITLE
git-unlock synopsis is "git-lock"

### ISSUE THREAD

**Issue by BenWiederhake** [tj/git-extras#710]
How to reproduce: `git help unlock`
Expected behavior: Synopsis says something like `git-unlock <filename>`
Actual behavior: Synopsis says `git-lock <filename>`

Just a minor issue, but confusing.

Also, after reading its manpage, the manpage of it's twin `git-lock`, and the source code of both `git-lock` and `git-unlock`, I still don't feel like I know what it does, and what a typical usage looks like.  After reading the relevant part of `git-update-index`, and a bit of [googling](https://stackoverflow.com/questions/13630849/git-difference-between-assume-unchanged-and-skip-worktree/13631525#13631525), I think I have a good idea.

But still: Hey $PersonFixingThis, could you add what this *means*, on an intuitive basis?  Maybe also an example, like with `git init`?

**Comment by spacewander** [comment]
@BenWiederhake 
Sorry for missing your issue. Maybe there is too many notifications for me to handle.
Since you have digging the meaning of `git-(un)lock`, would you spend sometime to send us a pull request?
Thanks!

**Comment by tfendin** [comment]
The PR #947 has been merged now, this issue can be closed.
