### ISSUE TITLE
git changelog add argument to show changes since a specified commit and add author of commit

### ISSUE THREAD

**Issue by thisisshi** [tj/git-extras#719]
something like 

```bash
$ git changelog --start-commit b4e5d317d8cebf5dd6a203e2023d3ceb0bd105fe
```

to find commits from now to that commit or build it in to the `--start-tag` and `--end-tag` args.

Also, It would be great to include an option to also include the author of the change in the output like so:

```
n.n.n / 2018-06-07
==================

  * s3 - toggle-versioning: add error handling for put_bucket_versioning (#2462) (thisisshi)
  * azure - docs + c7n-org docs (#2453) (tbarlow12)
  * azure - prevent tagging arm resources directly (#2485) (stefangordon)

```

**Comment by spacewander** [comment]
@thisisshi 
For the first feature request, I will try to implement it when I have spare time. Maybe in the next week, so you need to wait some days.

For the second feature request, you could achive it via `changelog.format`. See the description from `git help changelog`.

**Comment by thisisshi** [comment]
thanks for the quick response! I'll definitely take a look :)

**Comment by spacewander** [comment]
@thisisshi 
For `--start-commit`,  do you prefer
```
n.n.n / 2018-06-07
==================
* commit
* commit
...
* start commit
```
or
```
n.n.n / 2018-06-07
==================
* commit
* commit

tagx / 2017-06-07
==================
...
* commit
* start commit
```
?

The latter one will also display the tags.

**Comment by thisisshi** [comment]
the first
