### ISSUE TITLE
Time to make a new release

### ISSUE THREAD

**Issue by spacewander** [tj/git-extras#724]
If everything goes well, I will make a new release in this weekend. The new release will be 4.6.0.
@hemanth @nicolaiskogheim

**Comment by hemanth** [comment]
👍

**Comment by spacewander** [comment]
A new release is published:
https://github.com/tj/git-extras/releases/tag/4.6.0

Here is the corresponding homebrew pr: https://github.com/Homebrew/homebrew-core/pull/31007

**Comment by spacewander** [comment]
git-extras 4.6.0 Homebrew package is already published!
