### ISSUE TITLE
Add optional squash flat to git feature finish

### ISSUE THREAD

**Issue by breneser** [tj/git-extras#726]
Is it possible to add --squash support to `git feature finish` ? If not, what is the best way to achieve this ?

**Comment by spacewander** [comment]
@breneser 
Maybe you could replace the `git merge --no-ff` with `git merge --squash` to implement `git feature finish --squash`?
https://github.com/tj/git-extras/blob/master/bin/git-feature#L41

Pull request is welcome!

**Comment by cpradog** [comment]
Already implemented: #829

**Comment by spacewander** [comment]
Closed. Thanks for @cpradog.
