### ISSUE TITLE
tab completion no longer works for delete-merged-branches

### ISSUE THREAD

**Issue by paulschreiber** [tj/git-extras#748]
tab completion no longer works for delete-merged-branches

EXPECTED
`git del`<tab> --> `git delete-merged-branches`

ACTUAL
`git del`<tab> --> `git del` [beep]

CONFIG
macOS 10.13.6 (17G5019)
git 2.21.0
git-extras 4.8.0-dev

I believe this broke after updating to git 2.21, but am not 100% certain.

**Comment by spacewander** [comment]
Sorry, I could not reproduce it in Ubuntu 18.10.
I don't have Mac environment to verify the issue.

The `git $subcommand` auto completion is implemented by the git command itself, not implemented by `git-extras`. Does the auto completion work well with other third party subcommands?

**Comment by paulschreiber** [comment]
I reproduced the problem on a second machine (Mojave 10.14.4 (18E226), git 2.21, git-extras 4.8.0). Machine #2 did not have the problem moments earlier, with git 2.17.0.

Should I file against git?

**Comment by spacewander** [comment]
Maybe you could move the issue to https://github.com/git/git?
The `git $subcommand` auto completion is implemented in https://github.com/git/git/blob/master/contrib/completion/git-completion.bash

I guess they introduced something broken to the old version of bash. Mac ships an antiquated bash by default.

**Comment by paulschreiber** [comment]
Submitted: https://public-inbox.org/git/E4A677E6-E624-464B-9BC6-AAAE0A77EFFE@gmail.com/T/#u

GIt's GitHub repo doesn't take bug reports.
