### ISSUE TITLE
SUGGESTION: Prompt for two-factor authentication code after password

### ISSUE THREAD

**Issue by ecbrodie** [tj/git-extras#750]
While using `git fork`, I noticed that the prompt for the _two-factor authentication code_ came after the _password_ prompt. This ordering is a little awkward because it introduces a possible race condition: while inputting my password, there is a chance that the authentication code may have expired, most codes don't last more than 20 seconds.

The CLI tool `hub` has similar prompts for authenticating to github.com and it asks for the password before the code. I would like to suggest that `git-extras` does the same thing.

There is a chance that this issue may be related to #540, in that both are related to improved UX specific to how `git fork` authenticates with github.com.

**Comment by spacewander** [comment]
PR is welcome!
The password prompt is introduced by the `curl`'s `-u` option: https://github.com/tj/git-extras/blob/master/bin/git-fork#L36. You may need to pass the password in this option or use other better way to implement the same result.
