### ISSUE TITLE
git-rename-branch arguments are in wrong order

### ISSUE THREAD

**Issue by btmurrell** [tj/git-extras#759]
this command takes "new branch" as first arg and "old branch" as second arg. these arguments are reverse what they should be.  In all cli's you should have the first argument as "the thing you have" and the second argument as "the thing you want".  look at all unix commands as examples (`mv`, `cp`, `ln`).  Also look at `git-mv` from git, and  `git-rename-remote` and `git-rename-tag` in this project.

i know this argument inversion is a breaking change, but i think future users will appreciate it.

**Comment by spacewander** [comment]
@btmurrell 
Would you like to submit a pull request? Thanks!

**Comment by btmurrell** [comment]
@spacewander yes, I am planning to submit one -- i have one question on the docs tho -- do you have any tooling to generate the man and html docs? ronn? something else? thanks.

**Comment by spacewander** [comment]
@btmurrell 
The docs are generated via `ronn` and `make`: https://github.com/tj/git-extras/blob/master/man/Readme.md#how-to-generate-documentation

**Comment by spacewander** [comment]
Closed as #767 is merged.

**Comment by btmurrell** [comment]
Sorry @spacewander , i got busy with work, then vacation. Thanks for putting that one in.
