### ISSUE TITLE
_Forking_ some Osse/git-scripts

### ISSUE THREAD

**Issue by bric3** [tj/git-extras#770]
Hi,

I stumbled upon this git script [git-brv](https://github.com/Osse/git-scripts/blob/master/git-brv), which I found quite interesting, I think this script will fit nicely in git-extras. 

* git-extras is installable via homebrew
* git-extras has possible more visibility and hence more maintainers

Of course proper credits must be given.
![Screen Shot 2019-08-13 at 16 49 35](https://user-images.githubusercontent.com/803621/62951486-640bc280-bdea-11e9-9aca-7d7a17c5f724.png)

**Comment by spacewander** [comment]
@bric3 
I think we should contact the author first and get he/she's permission.

**Comment by bric3** [comment]
Sure I agree !

**Comment by Osse** [comment]
Hi, guys. Sorry for the delay. The issue over at my repo has gone completely unnoticed. 

By all means go ahead! :)
