### ISSUE TITLE
git-authors: line 92: $EDITOR: command not found

### ISSUE THREAD

**Issue by sarpik** [tj/git-extras#782]
In my `~/.gitconfig`, I've set my editor to `"$EDITOR"`, which works fine with git commands, like `git commit`:

```.gitconfig
[core]
	editor = "$EDITOR"
```

However, once I try to use some commands from git-extras, like `git authors`, the command errors:

```sh
$ git authors
/usr/bin/git-authors: line 92: $EDITOR: command not found
```

`/usr/bin/git-authors` @ `92` (https://github.com/tj/git-extras/blob/master/bin/git-authors#L55)

```bash
  test -n "$EDITOR" && $EDITOR $FILE
```

---

I've tried messing with bash's variable expansions, `eval` etc., but wasn't able to fix the issue.

I don't know if this is even possible to fix.

---

What worked in the terminal was this:

`open_editor` (taken from https://github.com/git/git/blob/master/contrib/git-jump/git-jump#L21-L24, just without the `-q` option):

```bash
#!/usr/bin/env bash
# open_editor

open_editor() {
	editor=`git var GIT_EDITOR`
	eval "$editor \$1"
}

open_editor "$@"
```

```sh
$ chmod +x open_editor
$ ./open_editor someFile
```

---

See also:

* https://stackoverflow.com/a/55275106/9285308
* https://stackoverflow.com/questions/13799789/expansion-of-variable-inside-single-quotes-in-a-command-in-bash
* https://unix.stackexchange.com/a/23117/332452

**Comment by spacewander** [comment]
Look like we could change `$EDITOR` to
```
editor=$(git var GIT_EDITOR)
$editor blah blah
```

@sarpik 
Will you submit a pull request? Thanks!

**Comment by spacewander** [comment]
@sarpik 
Could you paste your output of `git var GIT_EDITOR` here?
The `EDITOR` variable is already set to `git var GIT_EDITOR`: https://github.com/tj/git-extras/blob/master/bin/git-authors#L6
Or maybe you are using an old version of `git extras`?

**Comment by sarpik** [comment]
Hello, thanks for your information & sorry for the late reply @spacewander!

I figured out that the problem was with my git configuration itself, and not `git extras` nor `git`.

Basically, I set my `editor` in `~/.gitconfig` to `$EDITOR`, which does **NOT** expand into my actual editor, `nvim`.

```bash
$ git var GIT_EDITOR
$EDITOR
```

I suppose that the problem arises in this issue's case is that `git var GIT_EDITOR` actually returns a single-quoted string, meaning `'$EDITOR'`, which is unable to expand into the actual variable's value once used in scripts/shell etc.

```bash
# working example
foo=$EDITOR
$foo file.txt
# -> opens file
```

```bash
# not working example
foo='$EDITOR'          # notice the single quotes around $EDITOR !
$foo file.txt
bash: $EDITOR: command not found
# fails
```
