### ISSUE TITLE
[Feature Request] git-squash with concat messages of commits

### ISSUE THREAD

**Issue by razbensimon** [tj/git-extras#794]
Is it possible to add an option to `git squash` that will produce a squashed commit with concatenating messages string of the selected commits?

something like gitkraken's squash option

**Comment by spacewander** [comment]
If you only want to squash and concatenate the messages of current branch, you could use `git rebase -i` and change `pick` to `squash` in the editor.

**Comment by razbensimon** [comment]
I can. But what is the point?
I want the process to be easy, quick and user friendly. And of course automatic - I don't want to change every commit from pick to squash manually.

**Comment by spacewander** [comment]
@razbensimon 
I just submitted the PR: #795 

Could you try this feature and give us your feedback? You can use the commands below to update it:

```bash
git clone https://github.com/spacewander/git-extras -b git-squash-commit-msg
cd git-extras && make install
```

**Comment by razbensimon** [comment]
Yes it works great!

**Comment by spacewander** [comment]
Solved.
