### ISSUE TITLE
Zsh completions when `git` is aliased to `hub`

### ISSUE THREAD

**Issue by sarpik** [tj/git-extras#797]
(Originally from https://github.com/tj/git-extras/issues/376#issuecomment-554642055)

I have `git` aliased to [`hub`](https://github.com/github/hub).
I cannot get zsh completions for `git-extras` to work, using

```sh
fpath=($HOME/.config/zsh/completions $fpath)
[ -f "$HOME/.config/zsh/completions/git-extras-completion.zsh" ] && source "$HOME/.config/zsh/completions/git-extras-completion.zsh"
```

however, if I unalias git, then the completions work:

```sh
unalias git
```

Is there any way to make completions work even though I've aliased `git` to `hub`?
Thanks!

See also:
https://github.com/tj/git-extras/issues/196
https://github.com/tj/git-extras/issues/70#issuecomment-23539601

**Comment by spacewander** [comment]
It seems to be a behavior of zsh completion:

> By default, zsh expands aliases before performing completion.
https://unix.stackexchange.com/a/250489

As the answer suggests, you can
* alias git with a function like:
```bash
git() {
    hub $*
}
```
* `setopt complete_aliases`

**Comment by sarpik** [comment]
Thanks @spacewander - setting a function for `git` instead of an alias did indeed help!

I didn't want to `setopt complete_aliases` because of https://stackoverflow.com/a/20643204.

Last problem - I used to alias `g` to `git` for shorter use.
I've now tried to set a function for it

```sh
g() {
	hub $*
}
```

and I've tried adding `compdef g="hub"` (or doing the same but replacing `hub` with `git`), but neither helped:
without `compdef`, `g` provides 0 auto-completions and just completes a folder/file name.
With `compdef`, it provides `git`s + `hub`s completions, but does not provide ones for `git-extras`.

Sorry for being such a noobie at zsh and thanks for your time!

**Comment by spacewander** [comment]
After I change the
```
zstyle -g existing_user_commands ':completion:*:*:git:*' user-commands

zstyle ':completion:*:*:git:*' user-commands $existing_user_commands \
```
to
```
zstyle -g existing_user_commands ':completion:*:*:g:*' user-commands

zstyle ':completion:*:*:g:*' user-commands $existing_user_commands \
```
, and source the `git-extras-completion.zsh`, the completion works again.

Maybe there is some interesting detail hidden in the zsh's completion implementation.

**Comment by sarpik** [comment]
@spacewander u da best <3

here's a patch if you want to include it. Maybe a little comment noting that you can extend this to fit your alias would be great inside the completions file.

```patch
439c439
< zstyle -g existing_user_commands ':completion:*:*:git:*' user-commands
---
> zstyle -g existing_user_commands ':completion:*:*:g:*' user-commands
441c441
< zstyle ':completion:*:*:git:*' user-commands $existing_user_commands \
---
> zstyle ':completion:*:*:g:*' user-commands $existing_user_commands \
```

Thanks once again:) Closing.
