### ISSUE TITLE
DATA LOSS! Major bug in `git-delete-submodule`

### ISSUE THREAD

**Issue by hilbix** [tj/git-extras#799]
https://github.com/tj/git-extras/blob/a6a17540938971685cab13e55a996b39a689d135/bin/git-delete-submodule#L24

This is fundamentally incompatible to the `--name` option of `git submodule add`.

Consider

    git submodule add --name one ./ two
    git submodule add --name two ./ one
    git delete-submodule one

or

    git submodule add ./ one
    git mv one two
    git submodule add --name anotherone ./ one
    git delete-submodule one

And no, this is not an academical problem.

Recommendation:

Remove this line, as removing something below .git/modules/ can be considered harmful to the history and `git bisect`.

See https://stackoverflow.com/a/59034242/490291

**Comment by spacewander** [comment]
@hilbix 
Would you like to submit a pull request to fix it?

**Comment by spacewander** [comment]
@hilbix 
PR already submitted.
