### ISSUE TITLE
Would git bulk --clone <file> feature be useful?

### ISSUE THREAD

**Issue by roxchgt** [tj/git-extras#803]
I personally am working on a project with more than 12 git repositories and `git-bulk` is very handy in the existing development environment. However those repos hat to be cloned manually at the beginning one by one and it was a PITA!

Of course people who can do some scripting would make their life easier with a simple loop over lines of a file conatining the URLs of all those repos but would we want to extend git-bulk for those who aren't that much into scripting even though this use case occurs probably only once at the beginning of env setup?

I'm thinking of sth like:
```bash
# cd ~/workspace (of course)
git bulk --clone /path/to/file/containing/urls
```
which goes through all repository URLs and clone them under `~/workspace/` as subdirectories (and maybe add it as bulk workspace too) ??

Let's talk if such a feature would make git-bulk more useful and cooler for everyone

**Comment by spacewander** [comment]
What about changing the API to `--addworkspace <ws-name> <ws-root-directory> --from <url or file contains urls>`?

**Comment by roxchgt** [comment]
> What about changing the API to `--addworkspace <ws-name> <ws-root-directory> --from <url or file contains urls>`?

That's a brilliant idea. Open/Closed-friendly

**Comment by roxchgt** [comment]
@spacewander I just worked on it and I think it's fine. But maybe you'd take a look first before I make a pull request. Here is [the branch](https://github.com/roxchgt/git-extras/tree/addworkspace-from-source) in my fork. I could also go on and send the pull req (docs are not done yet)

**Comment by spacewander** [comment]
Solved.
