### ISSUE TITLE
git-bulk does not work outside a git repository on Windows

### ISSUE THREAD

**Issue by roxchgt** [tj/git-extras#805]
The main Intention of `git-bulk` is registering a directory which contains multiple git repositories as a workspace in order to run git operations on all those repos with one command. On Linux I have no issue with calling e.g. `git bulk --listall` or any other git-bulk function from anywhere on the system, even a non repo dir can be added as workspace. On Windows somehow it's not like that. Not only calling the git bulk doesn't work outside of a git repo, adding a non-git dir as workspace does not also work.
Message is: `Not a git repo!`

Anybody can reproduce this issue? Simply try to call `git bulk <--any>` from any dir which is not git repository...

**Comment by spacewander** [comment]
Need to change this line:
```
SET COMMANDS_WITHOUT_REPO=git-alias git-extras git-fork git-setup
```
https://github.com/tj/git-extras/blob/master/install.cmd#L107

We should read the command list from https://github.com/tj/git-extras/blob/master/not_need_git_repo instead of hard coding them.

**Comment by spacewander** [comment]
Solved.
