### ISSUE TITLE
Git-Ignore : incorrect '.git' directory when repo is a submodule

### ISSUE THREAD

**Issue by drasill** [tj/git-extras#807]
Hi,

when a repository is a submodule, the "git dir" is not actually in `.git`.

Instead, `.git` is a file containing the path of the git dir.

So, `git-ignore` fails.

It looks like reading `git rev-parse --git-dir` returns the correct git directory.

Changing the first line of `git-ignore` from :
`: ${GIT_DIR:=.git}`
To :
`: ${GIT_DIR:=$(git rev-parse --git-dir)}`

seems to work.

**Comment by spacewander** [comment]
@drasill 
Will you submit a PR to fix it?
Thank you!
