### ISSUE TITLE
Request: update epel-6 / 7 to include git-extras 5.x

### ISSUE THREAD

**Issue by joshka** [tj/git-extras#818]
I have a need to use epel-6 rather than the latest version and would like the latest git-extras installed. Can this be added please?

**Comment by spacewander** [comment]
Currently we only maintain the homebrew package. The package in epel-6/7 is not maintained by us.

There is a plan to provide our repo which contains the up-to-date version of git-extras: https://github.com/tj/git-extras/issues/766. However, I don't have enough spare time to invest in it.

**Comment by joshka** [comment]
No problem - this was a request from when I was at a previous job long ago
