### ISSUE TITLE
git browse: does not work 

### ISSUE THREAD

**Issue by xyyolab** [tj/git-extras#830]
I install git-extras through brew install, when I tried to explore some more features.
Followed this [manual](https://github.com/tj/git-extras/blob/dd0337c3cfa5201d391f6c1f5fc672fc42743bf4/man/git-browse.md).
Encountered this problem.
env: zsh, oh-my-zsh.

![Screenshot 2020-04-04 16 22 10](https://user-images.githubusercontent.com/48758247/78421234-0ab21580-7691-11ea-8372-3d1d38821c82.png)
 
Seems like renamed?

If `git browse` is renamed, I can pr to fix manual 😃

**Comment by spacewander** [comment]
`git browse` is newly added in the master branch. It hasn't been included in any release yet. So if you installed git-extras via package manager, you could not find it.

**Comment by xyyolab** [comment]
Understood, thanks ;)

**Comment by bethesque** [comment]
I'm super keen to use this - when is the next release schedule?

**Comment by spacewander** [comment]
@bethesque 
I don't have enough spare time to make a release this month. Maybe in July?
