### ISSUE TITLE
git-feature prefix needs config setting

### ISSUE THREAD

**Issue by jldugger** [tj/git-extras#834]
I commonly use a personal prefix for short lived branches, i.e. `jldugger/fix-bug-321`. git-feature supports a prefix option, but provides no means of setting a default. My first approach was to simply apply an alias, as one does in bash, to use the flag by default. However, this does not work, [by design](https://git-scm.com/docs/git-config#Documentation/git-config.txt-alias):

> To avoid confusion and troubles with script usage, aliases that hide existing Git commands are ignored. 

Can we add git config setting for this, so I can set a global default name for the prefix?

**Comment by spacewander** [comment]
You can use git config git-extras.feature.xxx to store the default prefix. Pull request is welcome!

**Comment by spacewander** [comment]
Solved.
