### ISSUE TITLE
git-pr doesn't provide a config option for default remote

### ISSUE THREAD

**Issue by jldugger** [tj/git-extras#835]
Using the github forking model, `origin` pretty much never contains any PRs I care about. Ideally I'd like to be able to configure the default to where `git pr 123` and `git pr 123 upstream` are the same command.

`git alias` does not work in this case --  it does not allow users to override commands [by design](https://git-scm.com/docs/git-config#Documentation/git-config.txt-alias):

> To avoid confusion and troubles with script usage, aliases that hide existing Git commands are ignored.

**Comment by spacewander** [comment]
I think you can use `git config git-extras.pr.xxx` to store the default remote. Pull request is welcome!

**Comment by spacewander** [comment]
Solved.
