### ISSUE TITLE
command "archive-file" does not work for branches created with "feature" command

### ISSUE THREAD

**Issue by toratora** [tj/git-extras#838]
The command `feature` (or `bug`, or `chore`) creates a branch name with "/" in it. The `archive-file` command appends the branch name to the file name which then has that "/" in it, which on most OSes is an invalid filename.

Propose replacing "/" in branch names with underscore, period, or dash when generating the archive name in command `archive-file`

Example:

For a project named `awesome-project` and branch named `awesome-new-feature` created with the `feature` command (and a tag and some commits after the tag), the `archive-file` command will attempt to create the file `awesome-project.1.5.0-3-gadc11c5.feature/awesome-new-feature.zip`

You'll get error output like
```
fatal: could not create archive file '/Users/awesome-user/Development/awesome-project/awesome-project.1.5.0-3-gadc11c5.feature/awesome-new-feature.zip': No such file or directory
du: /Users/awesome-user/Development/awesome-project/awesome-project.1.5.0-3-gadc11c5.feature/awesome-new-feature.zip: No such file or directory
```

due to the fact the OS thinks you're trying to create `awesome-new-feature.zip` in the directory `awesome-project.1.5.0-3-gadc11c5.feature`, which doesn't exist.

**Comment by spacewander** [comment]
I vote for replacing '/' with '-'. Will you submit a pull request? Thanks!

**Comment by spacewander** [comment]
@toratora 
I just submitted a pull request to fix the problem. Can you help us to verify it?

**Comment by toratora** [comment]
Verified on MacOS.

```shell
icarus:awesome-project toratora$ git archive-file
Building archive on branch "feature/android-base-power-methods"
Saved to "awesome-project.4.60-10-g477578e.feature-android-base-power-methods.zip" (512K)
```
