### ISSUE TITLE
git undo syntax

### ISSUE THREAD

**Issue by vr8hub** [tj/git-extras#848]
The help for git undo shows this as the syntax
````
git-undo [<commitcount>] [-s, --soft, -h, --hard]
````

That is, first parameter is an optional commit count, second parameter is an optional sort or hard.
That means that if there is a commit count, it should always be the first parameter. If the sort or hard are the first parameter, it means there wasn't a commit count, and so should be an implied 1.

However, the git undo code treats it as if it were the reverse, i.e. that the first parameter is soft/hard, and the second parameter the commitcount.

There is only a `case "$1"` in the code. In the cases for -h/--hard/-s/--soft, in each case it tests $2 and uses that for the commitcount. But per the syntax above, the commit count wasn't specified if the option is in $1, meaning the commitcount should be an implied 1.

Further, in the fall-through case `*)`, meaning the first parameter was presumably a number, it does a soft reset unconditionally. So a `git undo 2 --hard` is treated as a soft, not hard reset.

Given the code, I'm assuming the help syntax is wrong and should be instead:
````
git-undo [-s, --soft, -h, --hard] [<commitcount>]
````

**Comment by spacewander** [comment]
@vr8hub 
Good catch! Could you submit a pull request to fix the help? Thanks!

**Comment by spacewander** [comment]
Solved.
