### ISSUE TITLE
[/README.md] A part of the git-effort doc seems to be in git-repl doc

### ISSUE THREAD

**Issue by lemoinem** [tj/git-extras#85]
In /README.md, The two lines

By default git ls-files is used, however you may pass one or more files to git-effort(1), for example:
$ git effort bin/* lib/*

seem to be part of git-effort doc although they appear in git-repl section

**Comment by nicolaiskogheim** [comment]
Looks like there is a commit to fix this, but no PR.
@rkennedy ?

**Comment by rkennedy** [comment]
I'm not sure I understood how pull requests worked three years ago, but it would be pointless to do anything about this issue now since commit 7b8c38a4bdece2b996bdfe0d533c8238a9f91d22 has already fixed it.

**Comment by nicolaiskogheim** [comment]
Good. Thanks for the quick reply.

@lemoinem @tj
