### ISSUE TITLE
Lots of ssh login prompts

### ISSUE THREAD

**Issue by markg85** [tj/git-extras#851]
Hi,

I was just playing with some of the new commands that `get-extras` brings over vanilla git.
Namely `git create-branch` and `git delete-branch`

The `create-branch` command wants me to fill in my ssh passphrase 3 times.
The `delete-branch` command wants it only once.

I get why that's happening when looking at the commands that `create-branch` is executing.
The question is: Is there a way to more efficiently make use of commands to only require a user to fill in the passphrase once.

I am aware of ssh agents to manage your keys. This is **not** my intention here. That would get rid of all passphrase questions, but i kinda prefer to have that passphrase be asked to let me know that "something is going to do something on my remote repository now". Just only once.

Cheers,
Mark

**Comment by spacewander** [comment]
The `ssh login prompts` are triggered by the interaction with remote git server. They are not created by the git-extras itself. And we need several turns of interaction with remote git server to create branch. Therefore we can't change it.
You might need to change your ssh configure or git repo's configure.

**Comment by markg85** [comment]
Hi @spacewander 

I know that git-extras is not "creating" these prompts and that they instead are triggered by the git commands that do remote interactions. As i said in my initial post with this part: `I get why that's happening when looking at the commands that create-branch is executing.`

I'm wondering if there is an option to run multiple of those commands in **sequence** to only have **one** passphrase prompt.

So for example change:
```
		git push $REMOTE HEAD:refs/heads/$BRANCH
		git fetch $REMOTE
		git checkout --track -b $BRANCH $REMOTE/$BRANCH
```
to:
```
		git push $REMOTE HEAD:refs/heads/$BRANCH
  		&& git fetch $REMOTE
		&& git checkout --track -b $BRANCH $REMOTE/$BRANCH
```

Or something like:
```
		sh -c `git push $REMOTE HEAD:refs/heads/$BRANCH;
  		            git fetch $REMOTE;
		            git checkout --track -b $BRANCH $REMOTE/$BRANCH'
```

Note, i definitely can reduce ssh login prompts to probably just one by using a public url to pull and only using the ssh git@.... bla to push. That will work, but only in situations where you have public git repositories (vast majority of cases, probably).

**Comment by spacewander** [comment]
IMHO, tweaking the script to reduce the ssh prompts is just a workaround (or a hack).  You can use the SSH key to access private repo without even one prompt. I don't know which git server your company uses, but the majority of git servers (like GitLab) should support it.
