### ISSUE TITLE
Bug, chore, and refactor no longer working

### ISSUE THREAD

**Issue by Bodacious** [tj/git-extras#855]
Since updating to GitExtras version 6.0.0, the branch commands other than `feature` have stopped working.

### Example of bug command not working:

```
git bug my-bug
git: 'bug' is not a git command. See 'git --help'.

The most similar command is
	bulk
```

### Feature, and other git-extras commands still work

```
# This works as expected
git feature my-feature
```

### Versions

```
git --version
git version 2.27.0
```

```
git-extras --version
6.0.0
```

**Comment by spacewander** [comment]
@Bodacious 
The break change is intended. See https://github.com/tj/git-extras/issues/842 for the details.
This is why we made a release with major version number changed.

**Comment by Bodacious** [comment]
@spacewander Thanks for the info.

The last time I checked, the docs need to be updated to reflect this change.
