### ISSUE TITLE
Checkout branch of fork

### ISSUE THREAD

**Issue by jodyheavener** [tj/git-extras#857]
I did a quick check and couldn't see if this had been suggested before, so I'm curious if there would be value in a command to checkout the branch of a fork/different remote on your repo. I am frequently doing this to review contributor branches.

Command could look something like:

```shell
# cfb = checkout forked branch, but open to suggestions
git cfb {remote_name} {branch_name} [{remote_url}]
```

And the logic might look something like:

1. Check for existence of the `remote_name` remote.
2. Add it if non-existent (`remote_url` would be required for the first time)
3. Fetch from the remote
4. Set up new tracking branch for `branch_name` if non existent
5. Switch to the branch

If there's something similar in git-extras that I haven't seen, my apologies! But if not and this seems like a reasonable add I'd be happy to submit a PR for it.

**Comment by spacewander** [comment]
Isn't your requirement satisfied by `git-pr` or `git-mr`?

**Comment by jodyheavener** [comment]
Looks like they pretty cover it, with the exception that you already have the remote added if you're not using origin. Closing, thanks!
