### ISSUE TITLE
Add start-point option to `git feature`

### ISSUE THREAD

**Issue by smeijer** [tj/git-extras#861]
Currently, `git feature` creates a new branch based on the current active one. 

As `git flow` specifies that feature branches should be based on `develop`, it would be nice to be able to specify a `start-point`, so we don't need to switch branches first.

After finishing a feature, I currently need to run 3 commands to create my new feature branch:

```bash
git checkout develop
git pull
git feature my-feat
```

It would be awesome if we could simplify those 3 lines to a single command:

```bash
# git feature <branchname> [<start-point>]
  git feature my-feat develop 
```

Regardless of my active branch, `git feature my-feat develop` would:

- pull/fetch the commits from `origin`
- create a new branch with `develop` as `start-point`, 
- check out the new feature branch.

Does `git-extras` have global options? It would be awesome to be able to set the default `start-point` trough a global option

**Comment by spacewander** [comment]
You can use `git config git-extras.$cmd.$attr` to get the global option, like  `git config git-extras.create-branch.remote`.
BTW, I suggest to use `--from <start-point>`  instead of using it directly as argument.

**Comment by smeijer** [comment]
> You can use git config git-extras.$cmd.$attr to get the global option

Awesome! Thanks.

>  I suggest to use --from <start-point> 

`--from` sounds fine. That was even my original idea, but while composing this issue I remembered the signature of `git branch <branchname> [<start-point>]`

**Comment by spacewander** [comment]
I think it would be better to use `--xxx yyy` style for optional argument.
