### ISSUE TITLE
git pull-request - Github API decprication notice 

### ISSUE THREAD

**Issue by v-y-a-s** [tj/git-extras#863]
Could not find this in issues, pls close if duplicate. 

on using `git pull-request` I received the following content as email from github. 

can this feature have personal access tokens or ssh based authentication? 

```
Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

Thanks,
The GitHub Team
```

**Comment by spacewander** [comment]
@v-y-a-s 
Look like we need to change `-u "$user" ` to `-H 'Authorization: token my_access_token'`.
We can store the token in `git config git-extras.github_token`.
Pull request is welcome!

**Comment by v-y-a-s** [comment]
#864

**Comment by spacewander** [comment]
Solved.
