### ISSUE TITLE
cmd `delete-tag` assumes "origin" as remote for tags

### ISSUE THREAD

**Issue by elonderin** [tj/git-extras#870]
`delete-tag` the pushes the against the hard-coded remote 'origin' .

This failed for me b/c i renamed this usually to 'o' for laziness' sake ;)

`delete branch` figures the remote out from the branche's remote which doens't work for tags.
However, the current branch's remote could be used as a fall back which to me would make sense in most cases.

Another idea were to make the remote a CLI option or could be even put into the git config.
Note sure if this issue comes up in other extra commands as well in which case a consistent behavior across all commands would be appreciated

**Comment by spacewander** [comment]
We can store the default remote as `git config git-extras.default_remote`. PR is welcome!

**Comment by vanpipy** [comment]
A default remote is better. But I think a situation like `git-delete-tag --origin someRemote tagName` or `git-delete-tag tagName` with `git-extras.remote`.

I think to try to give a parameter will be more comfortable.

**Comment by vanpipy** [comment]
Follow the PR, I dont think to set a default remote is the best choice to take the laziness convenience.

The default remote is hard to explain bases on `git-extras`. On the other side, the `git-delete-tag tagName tagName tagName --origin remoteName` will be better.
