### ISSUE TITLE
Look up a new maintainer

### ISSUE THREAD

**Issue by spacewander** [tj/git-extras#876]
DON'T BE PANIC!
I am still maintaining the project and will continue to do so in a few years.
But I will spend more time in both work and family life, so the response here will be slower and slower.

It would be great if someone can offer his/her help and take the responsibility to maintain this project.
A new volunteer can start his/her job by looking the `pull request is welcome` issues and finish them:
https://github.com/tj/git-extras/issues?q=is%3Aopen+is%3Aissue+label%3A%22pull+request+is+welcome%22
Since I am still here, I will review your work and give some advices.

**Comment by elonderin** [comment]
i cant commit yet to become a maintainer but since i find this project useful i will support where i can

**Comment by alerque** [comment]
What's the current status? I might be interested in helping here. What's the status of the original repo owner @tj? Is it even possible to add maintainers or migrate the repository at this point?

**Comment by spacewander** [comment]
I am still maintaining the project. Due to getting a new job, I now have more time to maintain this project. Anyway, I am also looking forward to finding a new maintainer. More maintainers is good for this project.

**Comment by vanpipy** [comment]
I would like to be a maintainer, but I afraid of that no enough time to maintain it. So how and what is the main part todolist of the maintainer? Maybe a self-matching with the todolist will show a precise answer.

**Comment by spacewander** [comment]
@vanpipy 
Maybe you can think about how to provide an integration test for the git cmds in the CI.

**Comment by vanpipy** [comment]
> @vanpipy Maybe you can think about how to provide an integration test for the git cmds in the CI.

Good idea. I will try,

**Comment by hyperupcall** [comment]
@spacewander I would be interested in stepping up for some sort of co-maintainer role. I've been contributing to this repository [for almost a year](https://github.com/tj/git-extras/pull/1015), so I don't think that is too much of a surprise. Among other things, having the permissions will help me prune and rename older issues; I've been closing older, irrelevant issues through PRs, and that always feels quite messy.

**Comment by spacewander** [comment]
@hyperupcall 
Could you contact me via email? My email address is [spacewanderlzx AT gmail.com](mailto:spacewanderlzx@gmail.com)

**Comment by spacewander** [comment]
@hyperupcall and @vanpipy are now added as the new maintainers. Congratulations!
