### ISSUE TITLE
Git Browse Failed to Handle Brand New Repo

### ISSUE THREAD

**Issue by equt** [tj/git-extras#891]
Git browse would first check the current `HEAD` and output a git fatal for the following line.

https://github.com/tj/git-extras/blob/ad8c77bfa39c257ba7a7ea31ed5ce6fa3a699611/bin/git-browse#L5

```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

To reproduce, just run `git browse` inside a brand new git repo. Casting the error into `/dev/null` should fix it.

**Comment by spacewander** [comment]
Pull request is welcome!
