### ISSUE TITLE
Feature proposal: git-archive-file - archive all tracked files into a single zip archive

### ISSUE THREAD

**Issue by TheHippo** [tj/git-extras#90]
I have written a small scripts that archives all tracked files into a single zip archive with a useful name (e.g. `git_repo_name.v0.2.3-0-g6436ae9.zip`). I need this quite often, because I work with a lot of clients who do not use git, so I thought this might be useful for other people.

Do you think this would be a nice addition to have this in git-extras? If you think this is worthy to integrate into `git-extras` I will fork git-extras, figure out how to write the necessary files for man pages and and auto-completion and send you a pull request when I am done.

So let me know if you are interested in this.

Source: [`git-archive-file`] (https://github.com/TheHippo/git-archive-file)

**Comment by nicolaiskogheim** [comment]
@hemanth Close
