### ISSUE TITLE
Add a CI Process

### ISSUE THREAD

**Issue by agbell** [tj/git-extras#912]
It would be great to have a CI process for git-extras. Perhaps a simple one that calls `check_integrity.sh` and then a more complex one that tries to install it with the make file and tests specific aliases by calling them.

I would can work on this if it makes sense. I am thinking GitHub actions and using [earthly](https://github.com/earthly/earthly) inside of Github Actions for the more complex tests.

**Comment by spacewander** [comment]
We alreay have: https://github.com/tj/git-extras/blob/master/.github/workflows/ci.yml

**Comment by agbell** [comment]
Oh wow, I'm not sure how I missed that.
