### ISSUE TITLE
git fork directions need to be updated

### ISSUE THREAD

**Issue by duckunix** [tj/git-extras#927]
Hello!
I recently found these tools.  Thank you!  They are awesome.

I was playing with ```git fork```, and the directions need to be updated, I think.

I am using ```git-extras-git 6.2.0.r13.g206fe7c-1``` under ArchLinux.  When running ```git fork git@github.com:user/repo```, it asks for my username and then ```Enter github password for user "<user>"```.  The problem is, it seems the API has been updated to not take plain username/passwords, but now wants username/token.  Information on the [GitHub REST-API Access](https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api#authentication) has the details.

My question is, how would you like the fix?  A diff here, or a PR?  The changes would be in updating the command to ask for the token and not ask for the TFA token any more.

Thanks!

**Comment by bl-ue** [comment]
A PR would be great @duckunix!

**Comment by bl-ue** [comment]
I'd like to point out though that you should try https://github.com/cli/cli (`gh`), the official GitHub CLI.  It has lots of cool GitHub integration functionality including forking, and you can do that like this:
```
gh repo fork user/repo
```

**Comment by duckunix** [comment]
> I'd like to point out though that you should try https://github.com/cli/cli (`gh`), the official GitHub CLI. It has lots of cool GitHub integration functionality including forking, and you can do that like this:
> 
> ```
> gh repo fork user/repo
> ```

Well, if that is the route, then ```git-fork``` should be removed.  I will send a PR to fix it, however.

**Comment by duckunix** [comment]
Forgot to update, PR #928 s opened.

**Comment by duckunix** [comment]
Guess this needs to be closed since the PR was merged.
