### ISSUE TITLE
Installing via Homebrew doesn't install git-delete-squashed-branches

### ISSUE THREAD

**Issue by gdalmau** [tj/git-extras#931]
Mentioned previously in https://github.com/tj/git-extras/issues/16

The title is self explanatory, but [installing `git-extras` via Homebrew](https://github.com/tj/git-extras/blob/master/Installation.md#homebrew) doesn't install all the commands. It seems that the only command not installed is [`git delete-squashed-branches`](https://github.com/tj/git-extras/blob/master/Commands.md#git-delete-squashed-branches)

Version installed: 6.2.0

### Commands installed via Homebrew found in `/usr/local/bin`

<details><summary>List of commands</summary>
git-alias</br>
git-archive-file</br>
git-authors</br>
git-browse</br>
git-brv</br>
git-bulk</br>
git-changelog</br>
git-clear</br>
git-clear-soft</br>
git-coauthor</br>
git-commits-since</br>
git-contrib</br>
git-count</br>
git-cp</br>
git-create-branch</br>
git-delete-branch</br>
git-delete-merged-branches</br>
git-delete-submodule</br>
git-delete-tag</br>
git-delta</br>
git-effort</br>
git-extras</br>
git-feature</br>
git-force-clone</br>
git-fork</br>
git-fresh-branch</br>
git-gh-pages</br>
git-graft</br>
git-guilt</br>
git-ignore</br>
git-ignore-io</br>
git-info</br>
git-local-commits</br>
git-lock</br>
git-locked</br>
git-merge-into</br>
git-merge-repo</br>
git-missing</br>
git-mr</br>
git-obliterate</br>
git-paste</br>
git-pr</br>
git-psykorebase</br>
git-pull-request</br>
git-reauthor</br>
git-rebase-patch</br>
git-release</br>
git-rename-branch</br>
git-rename-remote</br>
git-rename-tag</br>
git-repl</br>
git-reset-file</br>
git-root</br>
git-rscp</br>
git-scp</br>
git-sed</br>
git-setup</br>
git-show-merged-branches</br>
git-show-tree</br>
git-show-unmerged-branches</br>
git-squash</br>
git-stamp</br>
git-standup</br>
git-summary</br>
git-sync</br>
git-touch</br>
git-undo</br>
git-unlock</br>
git-utimes
</details>

### Commands available in git-extras version 6.2.0

<details><summary>List of commands</summary>
git-alias</br>
git-archive-file</br>
git-authors</br>
git-browse</br>
git-bulk</br>
git-brv</br>
git-changelog</br>
git-clear</br>
git-clear-soft</br>
git-coauthor</br>
git-commits-since</br>
git-contrib</br>
git-count</br>
git-cp</br>
git-create-branch</br>
git-delete-branch</br>
git-delete-merged-branches</br>
git-delete-squashed-branches</br>
git-delete-submodule</br>
git-delete-tag</br>
git-delta</br>
git-effort</br>
git-extras</br>
git-feature</br>
git-force-clone</br>
git-fork</br>
git-fresh-branch</br>
git-gh-pages</br>
git-graft</br>
git-guilt</br>
git-ignore</br>
git-ignore-io</br>
git-info</br>
git-local-commits</br>
git-lock</br>
git-locked</br>
git-merge-into</br>
git-merge-repo</br>
git-missing</br>
git-mr</br>
git-obliterate</br>
git-paste</br>
git-pr</br>
git-psykorebase</br>
git-pull-request</br>
git-reauthor</br>
git-rebase-patch</br>
git-release</br>
git-rename-branch</br>
git-rename-tag</br>
git-rename-remote</br>
git-repl</br>
git-reset-file</br>
git-root</br>
git-rscp</br>
git-scp</br>
git-sed</br>
git-setup</br>
git-show-merged-branches</br>
git-show-tree</br>
git-show-unmerged-branches</br>
git-stamp</br>
git-squash</br>
git-standup</br>
git-summary</br>
git-sync</br>
git-touch</br>
git-undo</br>
git-unlock</br>
git-utimes
</details>

### Commands not installed

```
git-delete-squashed-branches
```

**Comment by spacewander** [comment]
git-delete-squashed-branches hasn't been in any release yet. It is only in the master branch.

**Comment by gdalmau** [comment]
Right! Thanks for the fast reply :)
