### ISSUE TITLE
git ignore-io no longer works

### ISSUE THREAD

**Issue by SwiftWinds** [tj/git-extras#952]
Running `git ignore-io -r macos,jetbrains` for example creates an empty .gitignore:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/12981958/149604268-ef4bcd8c-bb81-42b9-873d-8a76da7f0409.png">

**Comment by spacewander** [comment]
Can't reproduce it on my side.
Could you add `set -x` in https://github.com/tj/git-extras/blob/master/bin/git-ignore-io?

**Comment by SwiftWinds** [comment]
Nevermind, it turns out my `curl` installation was having some issues with certificates. I fixed it. Thanks!
