### ISSUE TITLE
xargs warning, conflicting options, when running git effort

### ISSUE THREAD

**Issue by epac-tom** [tj/git-extras#953]
I've just installed git-extras, great tool, but get an xargs warning when running commands like git effort:
`xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value`

Had a quick look and found this [https://www.gnu.org/software/findutils/manual/html_node/find_html/Conflicting-xargs-options.html](https://www.gnu.org/software/findutils/manual/html_node/find_html/Conflicting-xargs-options.html)

Running Windows
git version 2.35.0.windows.1
xargs (GNU findutils) 4.8.0

**Comment by duckunix** [comment]
Confirmed on a fully up to date Arch box w/ findutils 4.8.0-1

**Comment by spacewander** [comment]
I can't reproduce it in my machine with xargs 4.7.0
So it is a change introduced in 4.8.0

PR is welcome!

**Comment by tfendin** [comment]
This issue should've been fixed by PR #956. Can we close this issue?
