### ISSUE TITLE
Make vimeo introduction video not require login

### ISSUE THREAD

**Issue by manuel-wagesreither** [tj/git-extras#958]
Hi all,

this is to let you know the [vimeo video](https://vimeo.com/45506445) your `Readme.md` is linking to responds with `Video is not rated. Log in to watch.` I guess that's unintentional as it artifically lowers your projects visibility/reach.

Hence, letting you know. :)

All the best,
Manuel

**Comment by createyourpersonalaccount** [comment]
Works fine here.

**Comment by manuel-wagesreither** [comment]
> Works fine here.

Did you make sure you were logged out?

**Comment by LucasLarson** [comment]
> Did you make sure you were logged out?

It worked even when I was logged out. But you’re right.

The rating needs to be set to “All audiences”. Vimeo’s `man` pages say&nbsp;that:
> If you don’t rate your public videos, viewers in some countries (specifically in the UK and EU) will need to log into a Vimeo account to watch those videos per local&nbsp;regulations.

[[source](https://vimeo.zendesk.com/hc/articles/224818087#h_01FPB00R2EQ7HX1ESZPVKWVCQN)&nbsp;([archive](https://web.archive.org/web/20221103190259id_/vimeo.zendesk.com/hc/articles/224818087#h_01FPB00R2EQ7HX1ESZPVKWVCQN))].

**Comment by manuel-wagesreither** [comment]
> The rating needs to be set to “All audiences”. Vimeo’s `man` pages say that:
> 
> > If you don’t rate your public videos, viewers in some countries (specifically in the UK and EU) will need to log into a Vimeo account to watch those videos per local regulations.

I'm indeed in an EU country.

**Comment by LucasLarson** [comment]
These might be more widely accessible:

1. viewable in-browser: https://web.archive.org/web/20230219181235id_/vod-progressive.akamaized.net/exp=1676834145~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F4101%2F1%2F45506445%2F107111328.mp4~hmac=065b68f23c4b6a222463097b36d1c346995a9559baa9b819972da95550018471/vimeo-prod-skyfire-std-us/01/4101/1/45506445/107111328.mp4
2. will attempt to force a download of the video: https://web.archive.org/web/20230219181305id_/hsa63.w03.savethevideo.com/Git_Extras_-_Introduction-vimeo-45506445-dash-fastly_skyfire-video-79ddea2e.mp4?filename=Git_Extras_-_Introduction-vimeo-45506445-dash-fastly_skyfire-video-79ddea2e.mp4
