### ISSUE TITLE
cancel feature finish if branch is not commited

### ISSUE THREAD

**Issue by pgherveou** [tj/git-extras#96]
Hi TJ
Thks for the great tool
I noticed the other day that git feature finish does not check that you have committed all your changes before deleting the branch
I managed to restored the deleted branch but I think it could be useful to cancel action if not all changes have been committed

**Comment by nicolaiskogheim** [comment]
Hi,

I don't know how best to handle this. If you have staged changes, then you won't be able to `git checkout master`, so I guess this is about untracked files.  I imagine I'm not the only one who constantly has untracked files lying around, and I think aborting `git feature finish xxx` whenever there's an untracked file is too restricting.

I'm closing this until someone provides a concrete example on when we should abort the merge and deletion of the branch.
