### ISSUE TITLE
standup default value for -w

### ISSUE THREAD

**Issue by tfendin** [tj/git-extras#963]
The default value for -w should be `Mon-Fri` and/or it should be possible to set it in the config. (`-w Mon-Fri` causes standup to include commits made on Friday when called on a Monday, without the need to set the -d argument)

If it's added to the config and the -d argument is set, the implicit -w should be discarded (since -w and -d conflicts)

The -w option should also be added to the manual.

**Comment by tfendin** [comment]
Yes, that sets the default argument for -w (i.e. when no week-range was given.) I missed that before.

So my wish is that if neither -d or -w was given on the command line it would default to -w (perhaps together with configurable default week range).

**Comment by tfendin** [comment]
Scratch my previous wish.
If neither -d or -w was given on the command line I would like it to show what has been commited since the last working day. I.e. if it executed on a Monday it would show the commits made since Friday 00:00. If it's called on a Tuesday it would show commits made since Monday 00:00.

**Comment by spacewander** [comment]
Since standup already shows the last day's commit by default, I wonder whether it is acceptable to change it to the last working day. Anyway, I will keep this issue open to hear more voices.

**Comment by tfendin** [comment]
PR #966 shows how I would want it. With it an config option which could act as -w unless -w or -d is given on the command line.

**Comment by tfendin** [comment]
> Since standup already shows the last day's commit by default, I wonder whether it is acceptable to change it to the last working day. Anyway, I will keep this issue open to hear more voices.

With #965 and #966 merged my goals with this issue are fulfilled. Perhaps we can open a new issue for change the default to the last working day and close this issue.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if needed.

**Comment by spacewander** [comment]
@tfendin 
Thanks for your remind.
