### ISSUE TITLE
Show option: expand alias in terminal before it gets executed (like `abbr -a` in fish shell)

### ISSUE THREAD

**Issue by backermanbd** [tj/git-extras#968]
### Feature request
For only .gitconfig file, i want this feature
```
[alias]
    cl = clone
    ci = commit
```

- After typing `git cl` and press <kbd>space</kbd> key, alias should expand
  e.g `cl` option will turn into `clone`

- For some reason, if i made a mistake, i can press <kbd>Esc</kbd> or <kbd>Ctrl+space</kbd> to undo alias expansion
  e.g `clone` will revert back to `cl`

- Again correct it from `cl` to `ci` and press <kbd>space</kbd> key
  e.g `git ci` will turn into `git commit`

**Comment by spacewander** [comment]
Look like this feature can only be implemented in the shell.
