### ISSUE TITLE
[Feature request] git stash-staged

### ISSUE THREAD

**Issue by SwiftWinds** [tj/git-extras#973]
Would be an excellent addition! imo I would use this all the time and I can never seem to remember the steps: https://stackoverflow.com/questions/14759748/how-can-i-stash-only-staged-changes-in-git

**Comment by wpwoodjr** [comment]
Looks like that already is in git: https://stackoverflow.com/questions/14759748/how-can-i-stash-only-staged-changes-in-git/70231955#70231955

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if needed.

**Comment by SwiftWinds** [comment]
> Looks like that already is in git: https://stackoverflow.com/questions/14759748/how-can-i-stash-only-staged-changes-in-git/70231955#70231955

Oh, wow! That's really cool. Thanks for sharing it :)
