### ISSUE TITLE
`git-cp` does not preserve file history

### ISSUE THREAD

**Issue by joyt** [tj/git-extras#985]
The [man page](https://www.mankier.com/1/git-cp) states that using `git-cp` will "Copy a file keeping its history", however, the history is not preserved.

Repro steps:
1. Use git-cp to copy an existing file, e.g. `git cp 
2. Do `git diff HEAD^` - see that git considers the entire copied file to be completely new code authored by the current user

As you can see in the [source code](https://github.com/tj/git-extras/blob/master/bin/git-cp), rather than following the [process](https://stackoverflow.com/questions/16937359/git-copy-file-preserving-history/44036771#44036771) referenced by the [man page](https://www.mankier.com/1/git-cp#See_Also), the current implementation just simply copies the file using `cp -r` and adds a commit without any steps to keep the git file history.

**Comment by spacewander** [comment]
Yes. The bug is introduced in https://github.com/tj/git-extras/commit/91b3e47243b8c1ab549cb24a9271fda4a6fdd911
Would you like to fix it?
