### ISSUE TITLE
Idea: show how a feature was implemented

### ISSUE THREAD

**Issue by kaihendry** [tj/git-extras#998]
Say I have worked on a feature that is part of many commit messages like so [FOOBAR-1667].

I think I can clumsily search for it like so: `git log --grep=FOOBAR-1667`

I'm not sure why I can't see the patches: `git show --grep=FOOBAR-1667`

Nonetheless is there something like this in git-extras where a team in some sort of "code review" phase can examine what commits were made to realise a feature? Work out the cost / effort?

**Comment by spacewander** [comment]
> I'm not sure why I can't see the patches: git show --grep=FOOBAR-1667

There is no `--grep` option for show command.

**Comment by kaihendry** [comment]
To nicely view how something was implemented, I'm doing a:

    git rev-list --grep=FOOBAR-1667 HEAD | tig show --stdin
