### ISSUE TITLE
`git get` - checkout code in opinionated location

### ISSUE THREAD

**Issue by alexec** [tj/git-extras#999]
Golang requires all source code checked out in `~/go/src`. 

For example, https://github.com/tj/git-extras would be in  `~/go/src/github.com/tj/git-extras`.

I'd like a command to get it: 

```bash
git get https://github.com/tj/git-extras
```

**Comment by guenhter** [comment]
Wouldn't sound too complicated to do:

* the `git-get` script should require that the user defines an enviornment vairable like `GIT_EXTRA_DEFAULT_CLONE_PATH`
* if the path is not set -> error
* if the path is set, a the given path (https or git) must be a little bit parsed, directories must be created under `GIT_EXTRA_DEFAULT_CLONE_PATH` and then the clone can be done.

Would you mind creating a merge request for this?

**Comment by kang8** [comment]
@vanpipy `git-get` can be regarded as the alias of `git clone`

```sh
git get https://github.com/tj/git-extras

cd $GIT_EXTRA_DEFAULT_CLONE_PATH && git clone https://github.com/tj/git-extras
```

**Comment by vanpipy** [comment]
> @vanpipy `git-get` can be regarded as the alias of `git clone`
> 
> ```shell
> git get https://github.com/tj/git-extras
> 
> cd $GIT_EXTRA_DEFAULT_CLONE_PATH && git clone https://github.com/tj/git-extras
> ```

All right, and I try to review the PR, found the features about the `git-get`,

1. Set a git config variable as the clone path
2. Clone the repo to the path

But, something missing I thought here,

3. Get the repo without the git config, set it as the PWD when it is empty.
4. As the alias of the `git clone`, did it need to support the args of the `git clone`?

**Comment by kang8** [comment]
> As the alias of the `git clone`

It's just my understanding. 😉



> Get the repo without the git config, set it as the PWD when it is empty.


According to the description of this PR, `git-get` does not want to instead of `git clone` or implement the functionality of `git clone`. Therefore, must to set `clone-path` in `git-get` to use it.

**Comment by vanpipy** [comment]
Got your idea.

The `git-get` is not the alias of the `git-clone`, maybe the alias of the `go-get`. And i think the `go-get` mode is not good part for the git, so git-extras should not take this. But from another side `extras`, the `git-get` for the extras of the git makes sence.

Thanks your explains and everyone's effort for this :D.
